import { GrammarQuestion } from '../../types';

export const adjectiveQuizzes: Record<string, GrammarQuestion[]> = {
    "Bài tập 1": [
        { id: 'adj-450-1', questionText: "The restaurant had _______ service, and the food was delicious.", options: { A: 'quick', B: 'quickly', C: 'quicly', D: 'quicker' }, correctAnswer: 'A', explanation: "Danh từ 'service' cần một tính từ để mô tả nó. 'quick' là một tính từ, trong khi 'quickly' là một trạng từ." },
        { id: 'adj-450-2', questionText: "She was feeling _______ after a long day at work.", options: { A: 'tiring', B: 'tired', C: 'tireder', D: 'tiredest' }, correctAnswer: 'B', explanation: "Tính từ 'tired' (đuôi -ed) mô tả cảm xúc của một người. 'Tiring' (đuôi -ing) mô tả một cái gì đó gây ra cảm giác đó (ví dụ: 'một ngày mệt mỏi')." },
        { id: 'adj-450-3', questionText: "The weather was so _______ that we decided to stay indoors.", options: { A: 'beauty', B: 'beautiful', C: 'beautifully', D: 'beautify' }, correctAnswer: 'B', explanation: "Sau 'was so', cần một tính từ để mô tả 'the weather'. 'beautiful' là dạng tính từ đúng. 'beautifully' là một trạng từ." },
        { id: 'adj-450-4', questionText: "The movie was _______ that it made everyone laugh.", options: { A: 'funny', B: 'funniest', C: 'funnily', D: 'fun' }, correctAnswer: 'A', explanation: "Cần một tính từ sau động từ 'was' để mô tả chủ ngữ 'The movie'. 'funny' là tính từ đúng." },
        { id: 'adj-450-5', questionText: "It was a _______ event, with music, dancing, and great food.", options: { A: 'wonderful', B: 'wonderfully', C: 'wonder', D: 'wonderly' }, correctAnswer: 'A', explanation: "Cần một tính từ để mô tả danh từ 'event'. 'wonderful' là lựa chọn đúng." },
        { id: 'adj-450-6', questionText: "He was _______ in his approach to solving problems.", options: { A: 'creative', B: 'creatively', C: 'create', D: 'creation' }, correctAnswer: 'A', explanation: "Sau động từ 'was', cần một tính từ để mô tả chủ ngữ 'He'. 'creative' là dạng đúng." },
        { id: 'adj-450-7', questionText: "The new car is quite _______ on fuel, which is great for long trips.", options: { A: 'economic', B: 'economical', C: 'economically', D: 'economize' }, correctAnswer: 'B', explanation: "Cần một tính từ sau 'is quite'. 'Economical' có nghĩa là 'tiết kiệm nhiên liệu' hoặc 'tiết kiệm tiền'. 'Economic' liên quan đến nền kinh tế nói chung." },
        { id: 'adj-450-8', questionText: "My grandmother has a _______ collection of antique furniture.", options: { A: 'amazed', B: 'amazing', C: 'amazedly', D: 'amaze' }, correctAnswer: 'B', explanation: "Tính từ 'amazing' (đuôi -ing) được dùng để mô tả 'collection', có nghĩa là bộ sưu tập gây ra cảm giác kinh ngạc." },
        { id: 'adj-450-9', questionText: "The test was _______ that many students found it challenging.", options: { A: 'difficulty', B: 'difficult', C: 'difficultly', D: 'difficulties' }, correctAnswer: 'B', explanation: "Cần một tính từ sau động từ 'was' để mô tả chủ ngữ 'The test'. 'difficult' là lựa chọn đúng." },
        { id: 'adj-450-10', questionText: "We had a _______ day at the beach, playing in the sun and building sandcastles.", options: { A: 'fantastic', B: 'fantasticly', C: 'fantasy', D: 'fantasize' }, correctAnswer: 'A', explanation: "Cần một tính từ để bổ nghĩa cho danh từ 'day'. 'fantastic' là dạng tính từ đúng." }
    ],
    "Bài tập 2": [
        { id: 'adj-550-1', questionText: "The company implemented _______ measures to improve efficiency and reduce costs.", options: { A: 'loud', B: 'cost-saving', C: 'short', D: '' }, correctAnswer: 'B', explanation: "'Cost-saving' là một tính từ ghép được dùng để mô tả 'measures'. Nó có nghĩa là các biện pháp này được thiết kế để tiết kiệm tiền." },
        { id: 'adj-550-2', questionText: "Our company values _______ customer service, ensuring customer satisfaction is our top priority.", options: { A: 'exceptional', B: 'average', C: 'mediocre', D: '' }, correctAnswer: 'A', explanation: "Cần một tính từ để mô tả 'customer service'. 'Exceptional' có nghĩa là xuất sắc hoặc nổi bật." },
        { id: 'adj-550-3', questionText: "The CEO gave a _______ speech at the annual conference.", options: { A: 'inspire', B: 'inspiration', C: 'inspiring', D: '' }, correctAnswer: 'C', explanation: "Tính từ 'inspiring' (đuôi -ing) mô tả một cái gì đó gây ra cảm hứng. Bài phát biểu đã truyền cảm hứng cho khán giả." },
        { id: 'adj-550-4', questionText: "The team achieved _______ results, exceeding their sales targets for the quarter.", options: { A: 'impressive', B: 'flexible', C: 'reliable', D: '' }, correctAnswer: 'A', explanation: "Cần một tính từ để mô tả 'results'. 'Impressive' có nghĩa là gây ấn tượng." },
        { id: 'adj-550-5', questionText: "The hotel offers _______ amenities, including a swimming pool and a fitness center.", options: { A: 'vary', B: 'variably', C: 'various', D: '' }, correctAnswer: 'C', explanation: "Tính từ 'various' được dùng trước danh từ số nhiều ('amenities') có nghĩa là 'nhiều loại khác nhau'." },
        { id: 'adj-550-6', questionText: "John is _______ than his sister. He's the tallest person in the family.", options: { A: 'tall', B: 'taller', C: 'tallest', D: '' }, correctAnswer: 'B', explanation: "Từ 'than' cho thấy có sự so sánh giữa hai người (John và chị gái anh ấy), vì vậy dạng so sánh hơn 'taller' là bắt buộc." },
        { id: 'adj-550-7', questionText: "The new restaurant in town has a _______ menu with a wide range of international dishes.", options: { A: 'varied', B: 'variety', C: 'varying', D: '' }, correctAnswer: 'A', explanation: "Tính từ 'varied' được dùng để mô tả danh từ 'menu', có nghĩa là nó chứa nhiều món khác nhau." },
        { id: 'adj-550-8', questionText: "Our company aims to provide _______ customer service to ensure satisfaction.", options: { A: 'excellence', B: 'excellent', C: 'excellently', D: '' }, correctAnswer: 'B', explanation: "Cần một tính từ ('excellent') để bổ nghĩa cho cụm danh từ 'customer service'." },
        { id: 'adj-550-9', questionText: "The company's new product has _______ features that set it apart from competitors.", options: { A: 'unique', B: 'narrow', C: 'heavy', D: '' }, correctAnswer: 'A', explanation: "Tính từ 'unique' được dùng để mô tả 'features', cho thấy chúng là độc nhất vô nhị." },
        { id: 'adj-550-10', questionText: "The company offers _______ benefits, including healthcare coverage and retirement plans.", options: { A: 'basic', B: 'minimal', C: 'comprehensive', D: '' }, correctAnswer: 'C', explanation: "Tính từ 'comprehensive' có nghĩa là 'bao gồm mọi thứ cần thiết', phù hợp với ngữ cảnh các phúc lợi bao gồm bảo hiểm y tế và kế hoạch hưu trí." }
    ],
    "Bài tập 3": [
        { id: 'adj-600-1', questionText: "The company's new advertising campaign aims to create a _______ image for its brand.", options: { A: 'favorable', B: 'favorably', C: 'favored', D: 'favoring' }, correctAnswer: 'A', explanation: "Cần một tính từ ('favorable') để mô tả danh từ 'image'." },
        { id: 'adj-600-2', questionText: "The team was thrilled to receive _______ feedback from the client regarding their work.", options: { A: 'positive', B: 'positively', C: 'positiveness', D: 'positivist' }, correctAnswer: 'A', explanation: "Cần một tính từ ('positive') để bổ nghĩa cho danh từ 'feedback'." },
        { id: 'adj-600-3', questionText: "The project manager was impressed by the team's _______ performance, delivering the project ahead of schedule.", options: { A: 'exceptional', B: 'exceptionally', C: 'excepting', D: 'excepted' }, correctAnswer: 'A', explanation: "Cần một tính từ ('exceptional') để mô tả danh từ 'performance'." },
        { id: 'adj-600-4', questionText: "The training program provided participants with _______ skills in leadership and communication.", options: { A: 'valorous', B: 'valuableness', C: 'valuables', D: 'valuable' }, correctAnswer: 'D', explanation: "Cần một tính từ ('valuable') để bổ nghĩa cho danh từ 'skills'." },
        { id: 'adj-600-5', questionText: "The company's decision to implement sustainable practices reflects its _______ commitment to environmental stewardship.", options: { A: 'unwaveringness', B: 'unwaveringly', C: 'unwavering', D: 'unweaver' }, correctAnswer: 'C', explanation: "Cần một tính từ ('unwavering') để mô tả danh từ 'commitment'." },
        { id: 'adj-600-6', questionText: "The team's _______ efforts resulted in a successful product launch.", options: { A: 'collaboratively', B: 'collaborative', C: 'collaborativeness', D: 'collaborators' }, correctAnswer: 'B', explanation: "Cần một tính từ ('collaborative') để bổ nghĩa cho danh từ 'efforts'." },
        { id: 'adj-600-7', questionText: "The company's new CEO has a _______ vision for the future, aiming to expand into new markets.", options: { A: 'boldly', B: 'bold', C: 'boldness', D: 'bolder' }, correctAnswer: 'B', explanation: "Cần một tính từ ('bold') để mô tả danh từ 'vision'." },
        { id: 'adj-600-8', questionText: "The sales team exceeded their _______ targets for the quarter, demonstrating their strong performance.", options: { A: 'saleswoman', B: 'salesman', C: 'sales', D: 'salesmanship' }, correctAnswer: 'C', explanation: "Ở đây, danh từ 'sales' được dùng như một tính từ để bổ nghĩa cho danh từ 'targets', tạo thành một danh từ ghép." },
        { id: 'adj-600-9', questionText: "The organization values _______ employees who demonstrate a strong work ethic and dedication.", options: { A: 'dependable', B: 'dependably', C: 'dependability', D: 'dependables' }, correctAnswer: 'A', explanation: "Cần một tính từ ('dependable') để mô tả danh từ 'employees'." },
        { id: 'adj-600-10', questionText: "The team successfully completed the project with _______ results.", options: { A: 'outstanding', B: 'outstandingly', C: 'outstand', D: 'outstood' }, correctAnswer: 'A', explanation: "Cần một tính từ ('outstanding') để bổ nghĩa cho danh từ 'results'." },
        { id: 'adj-600-11', questionText: "The CEO's _______ leadership style inspired the entire organization.", options: { A: 'vision', B: 'visionarily', C: 'visionary', D: 'envisioned' }, correctAnswer: 'C', explanation: "Cần một tính từ ('visionary') để mô tả cụm danh từ 'leadership style'." },
        { id: 'adj-600-12', questionText: "The new marketing campaign has a _______ impact on brand awareness.", options: { A: 'significant', B: 'significantly', C: 'significance', D: 'signified' }, correctAnswer: 'A', explanation: "Cần một tính từ ('significant') để bổ nghĩa cho danh từ 'impact'." },
        { id: 'adj-600-13', questionText: "The team delivered a _______ presentation, impressing both clients and colleagues.", options: { A: 'compelled', B: 'compellingly', C: 'compel', D: 'compelling' }, correctAnswer: 'D', explanation: "Cần một tính từ để mô tả 'presentation'. Dạng -ing 'compelling' được dùng để mô tả một cái gì đó gây ra cảm giác hứng thú hoặc ngưỡng mộ." },
        { id: 'adj-600-14', questionText: "The company's new marketing strategy aims to reach a _______ audience.", options: { A: 'diversity', B: 'diversely', C: 'diverse', D: 'diversify' }, correctAnswer: 'C', explanation: "Cần một tính từ ('diverse') để bổ nghĩa cho danh từ 'audience'." },
        { id: 'adj-600-15', questionText: "The CEO expressed _______ optimism about the company's future prospects.", options: { A: 'cautious', B: 'cautiously', C: 'caution', D: 'cautionary' }, correctAnswer: 'A', explanation: "Cần một tính từ ('cautious') để mô tả danh từ 'optimism'." },
        { id: 'adj-600-16', questionText: "The project team demonstrated _______ problem-solving skills to overcome challenges.", options: { A: 'innovatively', B: 'innovative', C: 'innovation', D: 'innovate' }, correctAnswer: 'B', explanation: "Cần một tính từ ('innovative') để mô tả cụm danh từ 'problem-solving skills'." },
        { id: 'adj-600-17', questionText: "The candidate's _______ qualifications and experience make him a strong contender for the position.", options: { A: 'impressively', B: 'impressive', C: 'impress', D: 'impressed' }, correctAnswer: 'B', explanation: "Cần một tính từ ('impressive') để bổ nghĩa cho các danh từ 'qualifications and experience'." },
        { id: 'adj-600-18', questionText: "The organization values employees who exhibit _______ leadership qualities.", options: { A: 'effect', B: 'effectively', C: 'effective', D: 'affected' }, correctAnswer: 'C', explanation: "Cần một tính từ ('effective') để mô tả cụm danh từ 'leadership qualities'." },
        { id: 'adj-600-19', questionText: "The new software offers _______ features that enhance user experience.", options: { A: 'advanced', B: 'advancement', C: 'advancing', D: 'advance' }, correctAnswer: 'A', explanation: "Cần một tính từ ('advanced') để bổ nghĩa cho danh từ 'features'." },
        { id: 'adj-600-20', questionText: "The company is committed to maintaining _______ standards of quality and customer service.", options: { A: 'highly', B: 'high', C: 'height', D: 'heightened' }, correctAnswer: 'B', explanation: "Cần một tính từ ('high') để mô tả danh từ 'standards'." },
        { id: 'adj-600-21', questionText: "The project team delivered a _______ performance, completing the project ahead of schedule.", options: { A: 'stellar', B: 'stellary', C: 'stellarness', D: 'stellify' }, correctAnswer: 'A', explanation: "Cần một tính từ ('stellar', có nghĩa là xuất sắc) để mô tả danh từ 'performance'." },
        { id: 'adj-600-22', questionText: "The team successfully completed the project within the _______ timeframe.", options: { A: 'specified', B: 'specify', C: 'specifying', D: 'specifies' }, correctAnswer: 'A', explanation: "Quá khứ phân từ 'specified' được dùng như một tính từ để bổ nghĩa cho danh từ 'timeframe'." },
        { id: 'adj-600-23', questionText: "The new restaurant offers a _______ dining experience with its elegant decor and gourmet menu.", options: { A: 'sophisticate', B: 'sophistication', C: 'sophisticated', D: 'sophisticatedly' }, correctAnswer: 'C', explanation: "Cần một tính từ ('sophisticated') để mô tả cụm danh từ 'dining experience'." },
        { id: 'adj-600-24', questionText: "The CEO gave an _______ speech at the conference, inspiring the audience with his vision.", options: { A: 'inspiringly', B: 'inspiring', C: 'inspire', D: 'inspired' }, correctAnswer: 'B', explanation: "Cần một tính từ để mô tả 'speech'. Dạng -ing 'inspiring' được dùng vì bài phát biểu gây ra cảm hứng cho người khác." },
        { id: 'adj-600-25', questionText: "The company implemented _______ strategies to improve customer satisfaction.", options: { A: 'innovative', B: 'innovatively', C: 'innovation', D: 'innovate' }, correctAnswer: 'A', explanation: "Cần một tính từ ('innovative') để mô tả danh từ 'strategies'." },
        { id: 'adj-600-26', questionText: "The company's commitment to sustainability is reflected in its _______ practices.", options: { A: 'eco-friends', B: 'eco-friendliness', C: 'eco-friend', D: 'eco-friendly' }, correctAnswer: 'D', explanation: "Cần một tính từ ghép ('eco-friendly') để mô tả danh từ 'practices'." },
        { id: 'adj-600-27', questionText: "The company's new product offers _______ benefits for its customers, enhancing their overall experience.", options: { A: 'substantial', B: 'substantially', C: 'substance', D: 'substances' }, correctAnswer: 'A', explanation: "Cần một tính từ ('substantial') để bổ nghĩa cho danh từ 'benefits'." }
    ]
};
