// DEVELOPER NOTE:
// To use your own audio files for these exercises, follow these steps:
// 1. Place your MP3 audio files in the `public/audio/` directory.
// 2. For each exercise below, update the `audioSrc` property to the correct path.
//    For example: `audioSrc: '/audio/morning_routine.mp3'`
//
// By default, `audioSrc` is empty, and the application will use Text-to-Speech.

import { DictationPart } from '../types';

const exercises = {
    novaland1: {
        id: 101,
        title: "Novaland Call - Part 1",
        audioSrc: "",
        fullText: "Hi, you are calling the Novaland management office information line. Please be aware that there will be maintenance work to repave the entire parking garage adjacent to our building's front entrance on Friday, July third.",
        textWithBlanks: "Hi, you are calling the Novaland ____ office information line. Please be ____ that there will be ____ work to repave the entire parking ____ adjacent to our building's front ____ on Friday, July third.",
        missingWords: ["management", "aware", "maintenance", "garage", "entrance"],
    },
    novaland2: {
        id: 102,
        title: "Novaland Call - Part 2",
        audioSrc: "",
        fullText: "Vehicles of all Novaland residents are required to be moved before 9AM next Saturday because their parking slots will be changed.",
        textWithBlanks: "____ of all Novaland residents are ____ to be moved before 9AM next Saturday because their parking ____ will be changed.",
        missingWords: ["Vehicles", "required", "slots"],
    },
    novaland3: {
        id: 103,
        title: "Novaland Call - Part 3",
        audioSrc: "",
        fullText: "After 9AM, any cars left in the parking area will be towed and the owner will be responsible for the expense.",
        textWithBlanks: "After 9AM, any cars left in the parking area will be ____ and the owner will be ____ for the ____.",
        missingWords: ["towed", "responsible", "expense"],
    },
    novaland4: {
        id: 104,
        title: "Novaland Call - Part 4",
        audioSrc: "",
        fullText: "Finally, some alternative parking places will be posted in the building reception and I also will email it to all residents this afternoon.",
        textWithBlanks: "Finally, some ____ parking places will be posted in the building ____ and I also will email it to all ____ this afternoon.",
        missingWords: ["alternative", "reception", "residents"],
    },
    vacation: {
        id: 2,
        title: "Planning a Vacation",
        audioSrc: "",
        fullText: "Planning a vacation can be almost as exciting as the trip itself. First, you need to decide on a destination. Then, you should research flights and accommodation to find the best deals. Finally, creating a flexible itinerary helps ensure you see all the important sights without feeling rushed.",
        textWithBlanks: "Planning a ____ can be almost as ____ as the trip itself. First, you need to decide on a ____. Then, you should ____ flights and ____ to find the best deals. Finally, creating a flexible itinerary helps ensure you see all the important ____ without feeling ____.",
        missingWords: ["vacation", "exciting", "destination", "research", "accommodation", "sights", "rushed"],
    },
    reading: {
        id: 3,
        title: "The Benefits of Reading",
        audioSrc: "",
        fullText: "Reading is a wonderful hobby with numerous benefits. It improves your vocabulary and communication skills. Furthermore, it can reduce stress and provide a temporary escape from reality. Regular reading also enhances your analytical thinking and creativity.",
        textWithBlanks: "Reading is a ____ hobby with ____ benefits. It improves your ____ and communication skills. Furthermore, it can ____ stress and provide a temporary escape from reality. Regular reading also ____ your analytical thinking and ____.",
        missingWords: ["wonderful", "numerous", "vocabulary", "reduce", "enhances", "creativity"],
    },
    language: {
        id: 4,
        title: "Learning a New Language",
        audioSrc: "",
        fullText: "Learning a new language opens up a world of opportunities. It allows you to connect with different cultures and people. Consistency is crucial; practicing a little every day is more effective than one long session per week. Don't be afraid to make mistakes, as they are an essential part of the learning process.",
        textWithBlanks: "Learning a new ____ opens up a world of ____. It allows you to connect with different ____ and people. ____ is ____; practicing a little every day is more effective than one long session per week. Don't be afraid to make ____, as they are an essential part of the learning ____.",
        missingWords: ["language", "opportunities", "cultures", "Consistency", "crucial", "mistakes", "process"],
    },
    cooking: {
        id: 5,
        title: "Cooking at Home",
        audioSrc: "",
        fullText: "Cooking your own meals at home can be a rewarding experience. You have complete control over the ingredients, which often results in healthier food. It can also be a creative outlet and a great way to relax after a busy day. Plus, it's usually more affordable than eating out frequently.",
        textWithBlanks: "Cooking your own ____ at home can be a ____ experience. You have complete ____ over the ____, which often results in ____ food. It can also be a ____ outlet and a great way to relax after a busy day. Plus, it's usually more ____ than eating out frequently.",
        missingWords: ["meals", "rewarding", "control", "ingredients", "healthier", "creative", "affordable"],
    },
    q7: {
        id: 207,
        title: "Question 7",
        audioSrc: "",
        fullText: "How old is this building?\n(A) To ship some materials.\n(B) About ten years old.\n(C) Company offices, I think.",
        textWithBlanks: "How ___ is this ___?\n(A) To ship some ___.\n(B) About ten years ___.\n(C) Company ___, I think.",
        missingWords: ["old", "building", "materials", "old", "offices"],
    },
    q8: {
        id: 208,
        title: "Question 8",
        audioSrc: "",
        fullText: "Can you come to my jazz performance tonight?\n(A) I’m sorry I was late for the meeting.\n(B) Mostly just local musicians.\n(C) Sure, I'll be there!",
        textWithBlanks: "___ you come to my jazz ___ tonight?\n(A) I’m sorry I was ___ for the ___.\n(B) Mostly just local ___.\n(C) Sure, I'll be ___!",
        missingWords: ["Can", "performance", "late", "meeting", "musicians", "there"],
    },
    q9: {
        id: 209,
        title: "Question 9",
        audioSrc: "",
        fullText: "Which apartment submitted a work order?\n(A) It’s what you did for a living.\n(B) Submit your assignment here.\n(C) It came from the tenants in B23.",
        textWithBlanks: "Which apartment submitted a ___ ___?\n(A) It’s what you did for a ___.\n(B) Submit your ___ here.\n(C) It came from the ___ in B23.",
        missingWords: ["work", "order", "living", "assignment", "tenants"],
    },
    q10: {
        id: 210,
        title: "Question 10",
        audioSrc: "",
        fullText: "Will you contact the vendor about changing our delivery date?\n(A) Of course, I'll take care of it.\n(B) An e-mail receipt.\n(C) Could I get change for a dollar?",
        textWithBlanks: "___ you contact the vendor about ___ our ___ date?\n(A) Of course, I'll take ___ of it.\n(B) An e-mail ___.\n(C) Could I get ___ for a dollar?",
        missingWords: ["Will", "changing", "delivery", "care", "receipt", "change"],
    },
    q11: {
        id: 211,
        title: "Question 11",
        audioSrc: "",
        fullText: "Why was the maintenance worker here?\n(A) No, he didn’t.\n(B) From three o’clock until four.\n(C) Because a light needed to be fixed.",
        textWithBlanks: "___ was the ___ worker here?\n(A) No, he ___.\n(B) From three o’clock ___ four.\n(C) Because a ___ needed to be ___.",
        missingWords: ["Why", "maintenance", "didn’t", "until", "light", "fixed"],
    },
    q12: {
        id: 212,
        title: "Question 12",
        audioSrc: "",
        fullText: "Did management make a hiring decision yet?\n(A) Put it on the highest shelf.\n(B) The personnel department.\n(C) Yes, they chose Jacob Borgman.",
        textWithBlanks: "___ management make a hiring ___ yet?\n(A) Put it on the highest ___.\n(B) The ___ department.\n(C) Yes, they chose ___ ___.",
        missingWords: ["Did", "decision", "shelf", "personnel", "Jacob", "Borgman"],
    },
    q13: {
        id: 213,
        title: "Question 13",
        audioSrc: "",
        fullText: "Do you want to eat here in our cafeteria or go out?\n(A) He went there yesterday.\n(B) Well, maybe a sandwich.\n(C) Let’s eat here.",
        textWithBlanks: "___ you want to ___ here in our ___ or go out?\n(A) He went there ___.\n(B) Well, maybe a ___.\n(C) Let’s ___ here.",
        missingWords: ["Do", "eat", "cafeteria", "yesterday", "sandwich", "eat"],
    },
    q14: {
        id: 214,
        title: "Question 14",
        audioSrc: "",
        fullText: "Didn’t you e-mail the employment contract to Mr. Patel yesterday?\n(A) Yes, I would agree.\n(B) No, I'll send it now.\n(C) Check the employee manual.",
        textWithBlanks: "___ you e-mail the ___ ___ to Mr. Patel ___?\n(A) Yes, I would ___.\n(B) No, I'll ___ it ___.\n(C) Check the employee ___.",
        missingWords: ["Didn’t", "employment", "contract", "yesterday", "agree", "send", "now", "manual"],
    },
    q15: {
        id: 215,
        title: "Question 15",
        audioSrc: "",
        fullText: "Our division’s picnic is this Saturday, right?\n(A) There’s a lot of rain in the forecast.\n(B) Sure, I like salad.\n(C) At the end of this corridor.",
        textWithBlanks: "Our ___ picnic is this ___, right?\n(A) There’s a lot of rain in the ___.\n(B) Sure, I like salad.\n(C) At the end of this ___.",
        missingWords: ["division’s", "Saturday", "forecast", "corridor"],
    },
    q16: {
        id: 216,
        title: "Question 16",
        audioSrc: "",
        fullText: "Would you like coffee or tea?\n(A) Just water, please.\n(B) For a few dollars more.\n(C) A fifteen-minute break.",
        textWithBlanks: "___ you like coffee or tea?\n(A) Just ___, please.\n(B) For a few ___ more.\n(C) A ___-minute break.",
        missingWords: ["Would", "water", "dollars", "fifteen"],
    },
    q17: {
        id: 217,
        title: "Question 17",
        audioSrc: "",
        fullText: "We achieved our sales targets this month.\n(A) That’s excellent news!\n(B) A few times a day.\n(C) To the end of April.",
        textWithBlanks: "We ___ our ___ targets this ___.\n(A) That’s excellent ___.\n(B) A few ___ a day.\n(C) To the end of ___.",
        missingWords: ["achieved", "sales", "month", "news", "times", "April"],
    },
    q18: {
        id: 218,
        title: "Question 18",
        audioSrc: "",
        fullText: "How often do you travel for your job?\n(A) It turned out well.\n(B) Yes, I did find one.\n(C) About once a month.",
        textWithBlanks: "___ ___ do you ___ for your ___?\n(A) It ___ out well.\n(B) Yes, I did ___ one.\n(C) About ___ a ___.",
        missingWords: ["How", "often", "travel", "job", "turned", "find", "once", "month"],
    },
    q19: {
        id: 219,
        title: "Question 19",
        audioSrc: "",
        fullText: "We should hike the Wildflower Trail today.\n(A) This seat is available.\n(B) I didn’t bring boots.\n(C) At the visitors’ center.",
        textWithBlanks: "We ___ hike the Wildflower Trail ___.\n(A) This ___ is ___.\n(B) I didn’t bring ___.\n(C) At the visitors’ ___.",
        missingWords: ["should", "today", "seat", "available", "boots", "center"],
    },
    q20: {
        id: 220,
        title: "Question 20",
        audioSrc: "",
        fullText: "You’ve booked a hotel in London, haven’t you?\n(A) Very enjoyable, thanks.\n(B) He usually takes the train.\n(C) Yes, I made a reservation last week.",
        textWithBlanks: "You’ve ___ a hotel in London, ___ ___?\n(A) Very ___, thanks.\n(B) He ___ takes the train.\n(C) Yes, I made a ___ last ___.",
        missingWords: ["booked", "haven’t", "you", "enjoyable", "usually", "reservation", "week"],
    },
    q21: {
        id: 221,
        title: "Question 21",
        audioSrc: "",
        fullText: "Are there any tickets left for tonight’s concert?\n(A) It’s sold out.\n(B) He’s a concert violinist.\n(C) They already left.",
        textWithBlanks: "___ there any ___ left for tonight’s ___?\n(A) It’s ___ ___.\n(B) He’s a concert ___.\n(C) They already ___.",
        missingWords: ["Are", "tickets", "concert", "sold", "out", "violinist", "left"],
    },
    q22: {
        id: 222,
        title: "Question 22",
        audioSrc: "",
        fullText: "Haven't you used this software before?\n(A) Can I take your order?\n(B) I haven’t had the chance.\n(C) About 40 dollars.",
        textWithBlanks: "___ ___ you used this ___ before?\n(A) Can I take your ___?\n(B) I haven’t had the ___.\n(C) About ___ dollars.",
        missingWords: ["Haven't", "you", "software", "order", "chance", "40"],
    },
    q23: {
        id: 223,
        title: "Question 23",
        audioSrc: "",
        fullText: "When is the new blender going to be released?\n(A) Only with fruits and vegetables.\n(B) In the kitchen cabinet.\n(C) The prototype is still being tested.",
        textWithBlanks: "When is the new ___ going to be ___?\n(A) Only with ___ and ___.\n(B) In the kitchen ___.\n(C) The ___ is still being ___.",
        missingWords: ["blender", "released", "fruits", "vegetables", "cabinet", "prototype", "tested"],
    },
    q24: {
        id: 224,
        title: "Question 24",
        audioSrc: "",
        fullText: "Who’s picking up our clients at the airport?\n(A) They decided to drive.\n(B) At terminal 2.\n(C) It’s a marketing position.",
        textWithBlanks: "Who’s picking up our ___ at the ___?\n(A) They ___ to ___.\n(B) At ___ 2.\n(C) It’s a marketing ___.",
        missingWords: ["clients", "airport", "decided", "drive", "terminal", "position"],
    },
    q25: {
        id: 225,
        title: "Question 25",
        audioSrc: "",
        fullText: "Where are the red roses that came in this morning?\n(A) About three liters of water.\n(B) No, I didn’t check out the sale.\n(C) I needed some for a large bouquet.",
        textWithBlanks: "Where are the red ___ that ___ in this ___?\n(A) About three ___ of ___.\n(B) No, I didn’t check out the ___.\n(C) I ___ some for a ___ ___.",
        missingWords: ["roses", "came", "morning", "liters", "water", "sale", "needed", "large", "bouquet"],
    },
    q26: {
        id: 226,
        title: "Question 26",
        audioSrc: "",
        fullText: "This film has been nominated for several awards.\n(A) Why don’t we go see it?\n(B) After the announcement.\n(C) He made a great speech.",
        textWithBlanks: "This ___ has been ___ for several ___.\n(A) Why don’t we go ___ it?\n(B) After the ___.\n(C) He made a ___ ___.",
        missingWords: ["film", "nominated", "awards", "see", "announcement", "great", "speech"],
    },
    q27: {
        id: 227,
        title: "Question 27",
        audioSrc: "",
        fullText: "Who's interested in starting a car pool program?\n(A) Thanks, but I can't swim.\n(B) Clara’s already organizing one.\n(C) It’s a very interesting article.",
        textWithBlanks: "Who's ___ in ___ a ___ ___ program?\n(A) Thanks, but I can't ___.\n(B) Clara’s already ___ one.\n(C) It’s a very ___ ___.",
        missingWords: ["interested", "starting", "car", "pool", "swim", "organizing", "interesting", "article"],
    },
    q28: {
        id: 228,
        title: "Question 28",
        audioSrc: "",
        fullText: "Where will I teach my workshop this month?\n(A) We just sent an e-mail to all instructors.\n(B) Five to seven months.\n(C) Yes, it’s a beautiful building.",
        textWithBlanks: "___ will I ___ my ___ this month?\n(A) We just ___ an e-mail to all ___.\n(B) ___ to seven ___.\n(C) Yes, it’s a ___ ___.",
        missingWords: ["Where", "teach", "workshop", "sent", "instructors", "Five", "months", "beautiful", "building"],
    },
    q29: {
        id: 229,
        title: "Question 29",
        audioSrc: "",
        fullText: "Why are we moving these sweaters to the back of the store?\n(A) In the new shopping mall.\n(B) Yes, they come in other colors.\n(C) Our spring merchandise is arriving soon.",
        textWithBlanks: "___ are we ___ these ___ to the ___ of the ___?\n(A) In the new ___ ___.\n(B) Yes, they come in other ___.\n(C) Our spring ___ is ___ soon.",
        missingWords: ["Why", "moving", "sweaters", "back", "store", "shopping", "mall", "colors", "merchandise", "arriving"],
    },
    q30: {
        id: 230,
        title: "Question 30",
        audioSrc: "",
        fullText: "Would you be interested in working on some of these contracts?\n(A) Thank you for meeting me.\n(B) A contact lens prescription.\n(C) I have very limited time.",
        textWithBlanks: "___ you be ___ in ___ on some of these ___?\n(A) Thank you for ___ me.\n(B) A contact ___ ___.\n(C) I have very ___ ___.",
        missingWords: ["Would", "interested", "working", "contracts", "meeting", "lens", "prescription", "limited", "time"],
    },
    q31: {
        id: 231,
        title: "Question 31",
        audioSrc: "",
        fullText: "What type of job are you looking for?\n(A) No, at ten a.m.\n(B) I really like working with computers.\n(C) Just a résumé is needed.",
        textWithBlanks: "What type of ___ are you ___ ___?\n(A) No, at ___ a.m.\n(B) I really like working with ___.\n(C) Just a ___ is ___.",
        missingWords: ["job", "looking", "for", "ten", "computers", "résumé", "needed"],
    },
    // New exercises for Part 4, Test 1
    part4_q1: {
        id: 401,
        title: "Question 1",
        audioSrc: "",
        fullText: "Hi, you are calling the Novaland management office information line. Please be aware that there will be maintenance work to repave the entire parking garage adjacent to our building's front entrance on Friday, July third. Vehicles of all Novaland residents are required to be moved before 9AM next Saturday because their parking slots will be changed. After 9AM, any cars left in the parking area will be towed and the owner will be responsible for the expense. Finally, some alternative parking places will be posted in the building reception and I also will email it to all residents this afternoon.",
        textWithBlanks: "Hi, you are calling the Novaland ___ ___ information line. Please be aware that there will be ___ work to repave the entire parking ___ adjacent to our building's front ___ on Friday, July third. ___ of all Novaland residents are ___ to be moved before 9AM next Saturday because their parking slots will be changed. After 9AM, any cars left in the parking area will be ___ and the ___ will be ___ for the ___. Finally, some ___ parking places will be posted in the building ___ and I also will email it to all ___ this afternoon.",
        missingWords: ["management", "office", "maintenance", "garage", "entrance", "Vehicles", "required", "towed", "owner", "responsible", "expense", "alternative", "reception", "residents"],
    },
    part4_q2: {
        id: 402,
        title: "Question 2",
        audioSrc: "",
        fullText: "Welcome to House Help Channel. For today's episode, maintaining and making minor repairs to the roof of your home is what we'll go over. To begin, investing in a few special tools is the first thing to do, for example, a trowel and crowbar. Because you'll use them for many years, it's important to choose some that are high quality. You can seal any cracks or chips with your trowel and some roof cement. You can then replace loose shingles with the help of the crowbar after removing them. Now, every year, I highly recommend you take photos of your roof so that you can track its overall condition.",
        textWithBlanks: "Welcome to House Help Channel. For today's ___, maintaining and making ___ repairs to the ___ of your home is what we'll go over. To begin, ___ in a few special tools is the ___ thing to do, for example, a trowel and crowbar. Because you'll use them for many years, it's ___ to choose some that are ___ ___. You can seal any cracks or chips with your trowel and some roof cement. You can then ___ loose shingles with the help of the crowbar after ___ them. Now, every year, I ___ ___ you take ___ of your roof so that you can ___ its ___ ___.",
        missingWords: ["episode", "minor", "roof", "investing", "first", "important", "high", "quality", "replace", "removing", "highly", "recommend", "photos", "track", "overall", "condition"],
    },
    part4_q3: {
        id: 403,
        title: "Question 3",
        audioSrc: "",
        fullText: "Thanks again for joining the tour of the wonderful New York Conservatory with me today. I hope you enjoyed the species of plants and flowers that you saw and learned about. At the beginning of our tour, I mentioned the world-renowned botanist John Wick. At 2 o’clock, he will be giving a lecture on the care of flowering orchid plants. I highly recommend that you attend his speech because his work was in a famous documentary film named Plant Farmer. The conservatory's online gift shop is selling this, you can purchase it easily. Recently, I’ve learned many new things about the orchid species we have right here at the conservatory after watching this film.",
        textWithBlanks: "Thanks again for ___ the tour of the wonderful New York Conservatory with me ___. I hope you enjoyed the ___ of plants and flowers that you saw and learned about. At the ___ of our tour, I mentioned the world-___ botanist John Wick. At 2 o'clock, he will be giving a ___ on the care of ___ orchid plants. I highly recommend that you ___ his speech because his work was in a ___ documentary film named Plant Farmer. The conservatory's online ___ shop is selling this, you can ___ it easily. ___, I've ___ many new things about the orchid species we have ___ here at the conservatory after watching this film.",
        missingWords: ["joining", "today", "species", "beginning", "renowned", "lecture", "flowering", "attend", "famous", "gift", "purchase", "Recently", "learned", "right"],
    },
    part4_q4: {
        id: 404,
        title: "Question 4",
        audioSrc: "",
        fullText: "I want to thank you all again for helping the Wonder Community Center before the benefit concert begins. As I mentioned last month, some parts of our facility need to be repaired . In selling tickets, we have got 7000 dollars so far, but we still need more to achieve our target. Therefore, I highly recommend you buy some snacks or soda drinks in the concession stand before entering the concert. We will use 90 percent of the proceeds from this to cover the construction at our Wonder Community Center. I hope you have a great day!",
        textWithBlanks: "I want to thank you all again for helping the Wonder Community Center before the ___ ___ begins. As I mentioned last month, some parts of our facility need to be ___. In selling tickets, we have got ___ dollars so far, but we still need more to achieve our ___. Therefore, I highly recommend you buy some ___ or ___ ___ in the ___ ___ before entering the concert. We will use 90 ___ of the ___ from this to cover the construction at our Wonder Community Center. I hope you have a great day!",
        missingWords: ["benefit", "concert", "repaired", "7000", "target", "snacks", "soda", "drinks", "concession", "stand", "percent", "proceeds"],
    },
    part4_q5: {
        id: 405,
        title: "Question 5",
        audioSrc: "",
        fullText: "We appreciate you all being here for today's workshop. This session will be led by Thomas Frank and myself, and our focus will be on business owners using their time efficiently. For business success, planning and spending your time wisely is the key. In the packet we have handed to you during your arrival, there are some documents I’ll be referring to for the topic of our presentation today. If you haven't got one yet, Thomas is right at the green chair. Alright, to begin, I have an exercise to help us get to know one another better.",
        textWithBlanks: "We appreciate you all being here for today's ___. This session will be led by Thomas Frank and myself, and our ___ will be on ___ ___ using their time ___. For business success, ___ and ___ your time wisely is the ___. In the packet we have handed to you during your ___, there are some ___ I’ll be ___ to for the topic of our ___ today. If you haven't got one yet, Thomas is right at the green chair. Alright, to ___, I have an ___ to help us get to ___ one another better.",
        missingWords: ["workshop", "focus", "business", "owners", "efficiently", "planning", "spending", "key", "arrival", "documents", "referring", "presentation", "begin", "exercise", "know"],
    },
    part4_q6: {
        id: 406,
        title: "Question 6",
        audioSrc: "",
        fullText: "Archaeologists at this site have uncovered the remains of an eleventh-century marketplace, including colorful mosaic tiles on the walls. Even after all these centuries, you'll notice the vibrant colors. This is the most important part of these ruins. In the artists’ pictures, you can easily see the intricate details from daily life scenes. A roof has been constructed over the area, making the lights dim to protect these mosaics now. Also, no photos are allowed due to flash damage to the tiles. As we move forward, please use the handrails on both sides for staying on the path and protecting the surrounding ruins.",
        textWithBlanks: "Archaeologists at this site have ___ the ___ of an eleventh-century ___, including ___ mosaic ___ on the ___. Even ___ all these centuries, you'll ___ the vibrant colors. This is the most ___ part of these ruins. In the artists’ pictures, you can easily ___ the intricate ___ from daily life scenes. A ___ has been ___ over the area, making the lights dim to ___ these mosaics now. Also, no photos are ___ due to flash ___ to the ___. As we move forward, please use the ___ on both sides for staying on the ___ and protecting the surrounding ruins.",
        missingWords: ["uncovered", "remains", "marketplace", "colorful", "tiles", "walls", "after", "notice", "important", "see", "details", "roof", "constructed", "protect", "allowed", "damage", "tiles", "handrails", "path"],
    },
    part4_q7: {
        id: 407,
        title: "Question 7",
        audioSrc: "",
        fullText: "As you all know, our agency finally won the important advertising contract with McDonald Fast Food Company. What we need to develop is 5 advertisements in total. Three 45-second ads for a local supermarket to be released next two weeks and four additional 25-second ads for the next month. Although the schedule looks very tight, I know, we must prioritize this because it is the biggest contract for this year. The client has begun internal work, so we have a rough ad available for editing. Let’s focus on that now.",
        textWithBlanks: "As you all know, our ___ finally won the ___ advertising contract with McDonald Fast Food Company. What we need to develop is 5 ___ in total. Three 45-second ads for a ___ ___ to be ___ next two weeks and four ___ 25-second ads for the next month. Although the ___ looks very ___, I know, we must ___ this because it is the ___ contract for this year. The client has begun ___ work, so we have a ___ ad available for ___. Let’s ___ on that now.",
        missingWords: ["agency", "important", "advertisements", "local", "supermarket", "released", "additional", "schedule", "tight", "prioritize", "biggest", "internal", "rough", "editing", "focus"],
    },
    part4_q8: {
        id: 408,
        title: "Question 8",
        audioSrc: "",
        fullText: "Excuse me, nurses. Your attention please. I've been receiving complaints about the free snacks in the hospital break rooms. Some people have mentioned that they don't like the selection of snacks, and some have said that they don't get to eat them at all because they're gone by the time the evening shift starts. So I was thinking about putting some money into each of your staff spending accounts every month so that you can buy the snacks you want at the hospital cafeteria. That will require management approval, but I'll keep you posted.",
        textWithBlanks: "Excuse me, ___. Your attention please. I've been receiving ___ about the free snacks in the hospital break rooms. Some people have mentioned that they don't like the ___ of snacks, and some have said that they don't get to eat them at all because they're gone by the time the ___ ___ starts. So I was thinking about putting some ___ into each of your staff ___ ___ every month so that you can buy the snacks you want at the hospital ___. That will require management ___, but I'll keep you posted.",
        missingWords: ["nurses", "complaints", "selection", "evening", "shift", "money", "spending", "accounts", "cafeteria", "approval"],
    },
    part4_q9: {
        id: 409,
        title: "Question 9",
        audioSrc: "",
        fullText: "Hi all, it’s me again, the mayor of Hanoi city. I’m glad you are here to celebrate the recent renovation of Hanoi National Mountain in our town. The mountain has many new areas to explore. Therefore, we will take a long hike here. First, we will visit the biggest zoo and then will hike on the top of the mountain. Finally, we will end our tour at the picnic area in the middle of the stream. There we’ll have some free cookies and pies. If you take pictures, please put them on the city's website. We'd like to have a commemoration of this special day.",
        textWithBlanks: "Hi all, it’s me again, the ___ of Hanoi city. I’m glad you are here to celebrate the recent ___ of Hanoi National Mountain in our town. The mountain has many new ___ to explore. Therefore, we will take a long ___ here. First, we will visit the biggest zoo and then will hike on the top of the ___. Finally, we will end our ___ at the picnic area in the middle of the stream. There we’ll have some ___ cookies and pies. If you take ___, please put them on the city's website. We'd like to have a commemoration of this ___ day.",
        missingWords: ["mayor", "renovation", "areas", "hike", "mountain", "tour", "free", "pictures", "special"],
    },
    part4_q10: {
        id: 410,
        title: "Question 10",
        audioSrc: "",
        fullText: "Thank you all for being here at today's free public lecture, which is sponsored by the Springfield Farmers' Association. Many of you have asked for information about how to grow a fruit garden. People are interested in learning how to maintain their garden's health and achieve the fruits they want. First, we suggest starting with regular soil testing. Now we are in January, it’s important that all soil samples collected in the next few months come from the same depth, as shown on this chart. And don’t forget to sign up for our monthly email list before you leave, so you can receive updates on upcoming lectures.",
        textWithBlanks: "Thank you all for being here at today's free public ___, which is ___ by the Springfield Farmers' Association. Many of you have ___ for information about how to ___ a fruit garden. People are ___ in learning how to ___ their garden's ___ and ___ the ___ they want. First, we suggest starting with ___ soil testing. Now we are in January, it’s important that all ___ ___ collected in the next few months come from the same ___, as shown on this chart. And don’t forget to ___ ___ for our monthly email list ___ you ___, so you can ___ ___ on upcoming ___.",
        missingWords: ["lecture", "sponsored", "asked", "grow", "interested", "maintain", "health", "achieve", "fruits", "regular", "soil", "samples", "depth", "sign", "up", "before", "leave", "receive", "updates", "lectures"],
    }
};

export const dictationData: DictationPart[] = [
    {
        id: 1,
        title: "Part 1: Photographs",
        description: "Listen to descriptions of a photograph and identify the correct one.",
        tests: [
            { id: 1, title: "Test 1", exercises: [exercises.novaland1, exercises.novaland2] },
            { id: 2, title: "Test 2", exercises: [exercises.novaland3, exercises.novaland4] },
            { id: 3, title: "Test 3", exercises: [exercises.vacation] },
            { id: 4, title: "Test 4", exercises: [exercises.reading] },
            { id: 5, title: "Test 5", exercises: [exercises.language] },
        ]
    },
    {
        id: 2,
        title: "Part 2: Question-Response",
        description: "Listen to a question and choose the most appropriate response from three options.",
        tests: [
            { id: 1, title: "Test 1", exercises: [
                exercises.q7, exercises.q8, exercises.q9, exercises.q10, exercises.q11,
                exercises.q12, exercises.q13, exercises.q14, exercises.q15, exercises.q16,
                exercises.q17, exercises.q18, exercises.q19, exercises.q20, exercises.q21,
                exercises.q22, exercises.q23, exercises.q24, exercises.q25, exercises.q26,
                exercises.q27, exercises.q28, exercises.q29, exercises.q30, exercises.q31
            ] },
            { id: 2, title: "Test 2", exercises: [exercises.vacation] },
            { id: 3, title: "Test 3", exercises: [exercises.novaland1] },
            { id: 4, title: "Test 4", exercises: [exercises.novaland2] },
            { id: 5, title: "Test 5", exercises: [exercises.reading] },
        ]
    },
    {
        id: 3,
        title: "Part 3: Short Conversations",
        description: "Listen to short conversations between two or three people and answer questions.",
        tests: [
            { id: 1, title: "Test 1", exercises: [exercises.language] },
            { id: 2, title: "Test 2", exercises: [exercises.cooking] },
            { id: 3, title: "Test 3", exercises: [exercises.novaland3, exercises.novaland4] },
            { id: 4, title: "Test 4", exercises: [exercises.vacation] },
            { id: 5, title: "Test 5", exercises: [exercises.reading] },
        ]
    },
    {
        id: 4,
        title: "Part 4: Short Talks",
        description: "Listen to short talks given by a single speaker and answer related questions.",
        tests: [
            { id: 1, title: "Test 1", exercises: [
                exercises.part4_q1, exercises.part4_q2, exercises.part4_q3, exercises.part4_q4, exercises.part4_q5,
                exercises.part4_q6, exercises.part4_q7, exercises.part4_q8, exercises.part4_q9, exercises.part4_q10
            ] },
            { id: 2, title: "Test 2", exercises: [exercises.language] },
            { id: 3, title: "Test 3", exercises: [exercises.cooking] },
            { id: 4, title: "Test 4", exercises: [exercises.reading] },
            { id: 5, title: "Test 5", exercises: [exercises.vacation] },
        ]
    },
];