import { DictationPart } from '../types';

// TOEIC TEST 5 EXERCISES - PART 2
const t5p2q7 = { id: 5207, title: "Test 5 - Part 2 - Q7", audioSrc: "", fullText: "There's a meeting in the conference room soon, right? (A) Yes, it's for the whole department. (B) No, put it in the closet. (C) The rent is too high.", textWithBlanks: "There's a ____ in the ____ room soon, right? (A) Yes, it's for the ____ department. (B) No, put it in the ____. (C) The ____ is too ____.", missingWords: ["meeting", "conference", "whole", "closet", "rent", "high"] };
const t5p2q8 = { id: 5208, title: "Test 5 - Part 2 - Q8", audioSrc: "", fullText: "Why hasn't the mural in the lobby been painted yet? (A) Red and yellow. (B) Please pick up the ladder. (C) Because the artist is out of town.", textWithBlanks: "Why hasn't the ____ in the ____ been ____ yet? (A) Red and ____. (B) Please pick up the ____. (C) Because the ____ is out of ____.", missingWords: ["mural", "lobby", "painted", "yellow", "ladder", "artist", "town"] };
const t5p2q9 = { id: 5209, title: "Test 5 - Part 2 - Q9", audioSrc: "", fullText: "Do you prefer writing in the morning or the afternoon? (A) My publisher requested edits. (B) Thanks for providing a solution. (C) Mornings are usually better for me.", textWithBlanks: "Do you ____ writing in the ____ or the ____? (A) My ____ requested edits. (B) Thanks for ____ a solution. (C) ____ are usually ____ for me.", missingWords: ["prefer", "morning", "afternoon", "publisher", "providing", "Mornings", "better"] };
const t5p2q10 = { id: 5210, title: "Test 5 - Part 2 - Q10", audioSrc: "", fullText: "I suggest we paint the waiting room light blue. (A) Doctor Park has an opening at three. (B) That's a good idea. (C) I prefer the red jacket.", textWithBlanks: "I ____ we ____ the ____ room light blue. (A) Doctor Park has an ____ at three. (B) That's a ____ idea. (C) I ____ the red ____.", missingWords: ["suggest", "paint", "waiting", "opening", "good", "prefer", "jacket"] };
const t5p2q11 = { id: 5211, title: "Test 5 - Part 2 - Q11", audioSrc: "", fullText: "Did you know that the music school is closed on Sundays? (A) Forty dollars an hour. (B) No, I didn't know that. (C) I saw the piano recital.", textWithBlanks: "Did you ____ that the ____ school is ____ on Sundays? (A) ____ dollars an hour. (B) No, I didn't ____ that. (C) I saw the piano ____.", missingWords: ["know", "music", "closed", "Forty", "know", "recital"] };
const t5p2q12 = { id: 5212, title: "Test 5 - Part 2 - Q12", audioSrc: "", fullText: "How do I find the office manager? (A) The receptionist would know. (B) Desk lamps and headsets. (C) Twelve euros.", textWithBlanks: "How do I ____ the office ____? (A) The ____ would know. (B) Desk ____ and ____. (C) Twelve ____.", missingWords: ["find", "manager", "receptionist", "lamps", "headsets", "euros"] };
const t5p2q13 = { id: 5213, title: "Test 5 - Part 2 - Q13", audioSrc: "", fullText: "When did you place the order for the lumber? (A) Yes, it's a great place for hiking. (B) It's out of stock right now. (C) The warehouse on William Street.", textWithBlanks: "When did you ____ the ____ for the ____? (A) Yes, it's a great ____ for hiking. (B) It's out of ____ right now. (C) The ____ on William Street.", missingWords: ["place", "order", "lumber", "place", "stock", "warehouse"] };
const t5p2q14 = { id: 5214, title: "Test 5 - Part 2 - Q14", audioSrc: "", fullText: "Where is the new packaging machine? (A) Ten packages a minute. (B) We met last Thursday. (C) We decided to keep the old one.", textWithBlanks: "Where is the new ____ machine? (A) Ten ____ a minute. (B) We ____ last Thursday. (C) We ____ to keep the ____ one.", missingWords: ["packaging", "packages", "met", "decided", "old"] };
const t5p2q15 = { id: 5215, title: "Test 5 - Part 2 - Q15", audioSrc: "", fullText: "I'll be out of the office this afternoon. (A) An awfully long commute. (B) OK—I'll update your schedule. (C) It's right down the hallway.", textWithBlanks: "I'll be ____ of the office this ____. (A) An awfully long ____. (B) OK—I'll ____ your ____. (C) It's right down the ____.", missingWords: ["out", "afternoon", "commute", "update", "schedule", "hallway"] };
const t5p2q16 = { id: 5216, title: "Test 5 - Part 2 - Q16", audioSrc: "", fullText: "Are you taking a vacation once this project is over? (A) Yes—I’m planning a trip to Barcelona. (B) This is your second time, isn’t it? (C) Blueprints for a high-rise building.", textWithBlanks: "Are you ____ a ____ once this ____ is over? (A) Yes—I’m ____ a trip to Barcelona. (B) This is your ____ time, isn’t it? (C) ____ for a high-rise ____.", missingWords: ["taking", "vacation", "project", "planning", "second", "Blueprints", "building"] };
const t5p2q17 = { id: 5217, title: "Test 5 - Part 2 - Q17", audioSrc: "", fullText: "Let's post the sales report to our team's Web page. (A) We're sharing a taxi to the airport. (B) I can do that. (C) A recent hiring decision.", textWithBlanks: "Let's ____ the sales ____ to our team's Web page. (A) We're ____ a taxi to the ____. (B) I can do that. (C) A ____ hiring ____.", missingWords: ["post", "report", "sharing", "airport", "recent", "decision"] };
const t5p2q18 = { id: 5218, title: "Test 5 - Part 2 - Q18", audioSrc: "", fullText: "Which airline are you planning on using? (A) The usual one. (B) A one-way ticket. (C) Yes, you can use mine.", textWithBlanks: "Which ____ are you ____ on ____? (A) The ____ one. (B) A one-way ____. (C) Yes, you can use ____.", missingWords: ["airline", "planning", "using", "usual", "ticket", "mine"] };
const t5p2q19 = { id: 5219, title: "Test 5 - Part 2 - Q19", audioSrc: "", fullText: "Where's this shipment of parts being sent? (A) Around five thirty this evening. (B) To the assembly plant in Dublin. (C) Just half the order.", textWithBlanks: "Where's this ____ of parts being ____? (A) Around five thirty this ____. (B) To the ____ plant in Dublin. (C) Just ____ the order.", missingWords: ["shipment", "sent", "evening", "assembly", "half"] };
const t5p2q20 = { id: 5220, title: "Test 5 - Part 2 - Q20", audioSrc: "", fullText: "Who paid for lunch? (A) I just ate. (B) It closes at five. (C) Alberto did.", textWithBlanks: "Who ____ for ____? (A) I just ____. (B) It ____ at five. (C) ____ did.", missingWords: ["paid", "lunch", "ate", "closes", "Alberto"] };
const t5p2q21 = { id: 5221, title: "Test 5 - Part 2 - Q21", audioSrc: "", fullText: "How many employees work in your department? (A) I don't mind taking notes at the meeting. (B) A couple dozen, I think. (C) It's seven meters long.", textWithBlanks: "How many ____ work in your ____? (A) I don't ____ taking notes at the ____. (B) A couple ____, I think. (C) It's seven ____ long.", missingWords: ["employees", "department", "mind", "meeting", "dozen", "meters"] };
const t5p2q22 = { id: 5222, title: "Test 5 - Part 2 - Q22", audioSrc: "", fullText: "We should leave for our training course soon, shouldn't we? (A) We still have a few minutes. (B) There's a map on the wall. (C) Two sessions per day.", textWithBlanks: "We should ____ for our ____ course soon, shouldn't we? (A) We still have a few ____. (B) There's a ____ on the wall. (C) Two ____ per day.", missingWords: ["leave", "training", "minutes", "map", "sessions"] };
const t5p2q23 = { id: 5223, title: "Test 5 - Part 2 - Q23", audioSrc: "", fullText: "Isn't there a limit on travel expenses? (A) To fix the vending machine. (B) One hundred dollars per day. (C) Next to the travel agency.", textWithBlanks: "Isn’t there a ____ on travel ____? (A) To ____ the vending machine. (B) One ____ dollars per day. (C) Next to the travel ____.", missingWords: ["limit", "expenses", "fix", "hundred", "agency"] };
const t5p2q24 = { id: 5224, title: "Test 5 - Part 2 - Q24", audioSrc: "", fullText: "When should I tell the director that I'm interested in the management position? (A) Yes, we're extending our business hours. (B) Didn't Andrey direct the play? (C) I'm not on the hiring team.", textWithBlanks: "When should I tell the ____ that I’m ____ in the ____ position? (A) Yes, we’re ____ our business hours. (B) Didn’t Andrey ____ the play? (C) I’m not on the ____ team.", missingWords: ["director", "interested", "management", "extending", "direct", "hiring"] };
const t5p2q25 = { id: 5225, title: "Test 5 - Part 2 - Q25", audioSrc: "", fullText: "The layout of the footwear department has changed. (A) There's a charging station in the café. (B) Yes, a three-bedroom apartment. (C) The store has a new manager.", textWithBlanks: "The ____ of the ____ department has ____. (A) There’s a ____ station in the café. (B) Yes, a three-bedroom ____. (C) The store has a new ____.", missingWords: ["layout", "footwear", "changed", "charging", "apartment", "manager"] };
const t5p2q26 = { id: 5226, title: "Test 5 - Part 2 - Q26", audioSrc: "", fullText: "Can you look at this month's revenue report? (A) The news program is informative. (B) I have some free time tomorrow afternoon. (C) He started that position in July.", textWithBlanks: "Can you ____ at this month’s ____ report? (A) The news program is ____. (B) I have some ____ time tomorrow afternoon. (C) He ____ that ____ in July.", missingWords: ["look", "revenue", "informative", "free", "started", "position"] };
const t5p2q27 = { id: 5227, title: "Test 5 - Part 2 - Q27", audioSrc: "", fullText: "Why haven't the windows been replaced yet? (A) Not too much wind, no. (B) Look in the filing cabinet. (C) Did you see the cost estimate?", textWithBlanks: "Why haven't the ____ been ____ yet? (A) Not too much ____, no. (B) Look in the ____ cabinet. (C) Did you see the cost ____?", missingWords: ["windows", "replaced", "wind", "filing", "estimate"] };
const t5p2q28 = { id: 5228, title: "Test 5 - Part 2 - Q28", audioSrc: "", fullText: "Isn't your suitcase going to be heavier than the permitted weight? (A) The building permit arrived today. (B) There are seats in the lobby. (C) I'll have to pay a little bit extra.", textWithBlanks: "Isn’t your ____ going to be ____ than the ____ weight? (A) The building ____ arrived today. (B) There are ____ in the lobby. (C) I’ll have to ____ a little bit ____.", missingWords: ["suitcase", "heavier", "permitted", "permit", "seats", "pay", "extra"] };
const t5p2q29 = { id: 5229, title: "Test 5 - Part 2 - Q29", audioSrc: "", fullText: "Who manufactures the engines for our machines? (A) Koji is in charge of supplier contracts. (B) I'm sorry—the storage room is full. (C) That's a cargo airplane.", textWithBlanks: "Who ____ the ____ for our machines? (A) Koji is in charge of ____ contracts. (B) I’m sorry—the ____ room is full. (C) That’s a ____ airplane.", missingWords: ["manufactures", "engines", "supplier", "storage", "cargo"] };
const t5p2q30 = { id: 5230, title: "Test 5 - Part 2 - Q30", audioSrc: "", fullText: "Should we meet at the department store on Fifth Street or the one on Grover Lane? (A) Let's ask Patricia first. (B) No, I don't mind. (C) How much does it cost?", textWithBlanks: "Should we ____ at the ____ store on Fifth Street or the one on Grover Lane? (A) Let’s ____ Patricia first. (B) No, I don’t ____. (C) How much does it ____?", missingWords: ["meet", "department", "ask", "mind", "cost"] };
const t5p2q31 = { id: 5231, title: "Test 5 - Part 2 - Q31", audioSrc: "", fullText: "Which band is playing at the club tonight? (A) There's always a comedy show on Thursday nights. (B) Yes, I've played the piano for many years. (C) Their number one hit.", textWithBlanks: "Which ____ is playing at the ____ tonight? (A) There’s always a ____ show on Thursday nights. (B) Yes, I’ve ____ the piano for many years. (C) Their ____ one hit.", missingWords: ["band", "club", "comedy", "played", "number"] };

// TOEIC TEST 2 EXERCISES - PART 2
const t2p2q7 = { id: 2207, title: "Question 7", audioSrc: "", fullText: "Have the machines on the factory floor been cleaned?\n(A) No, not yet.\n(B) It's in the shipping container.\n(C) I just put it in the trash bin.", textWithBlanks: "Have the ____ on the ____ floor been ____?\n(A) No, not yet.\n(B) It's in the shipping ____.\n(C) I just put it in the ____ bin.", missingWords: ["machines", "factory", "cleaned", "container", "trash"] };
const t2p2q8 = { id: 2208, title: "Question 8", audioSrc: "", fullText: "How much will the budget increase next year?\n(A) About 10 percent.\n(B) Three hours, I think.\n(C) At the bank's main branch.", textWithBlanks: "How much will the ____ increase next ____?\n(A) About 10 ____.\n(B) Three ____, I think.\n(C) At the bank's main ____.", missingWords: ["budget", "year", "percent", "hours", "branch"] };
const t2p2q9 = { id: 2209, title: "Question 9", audioSrc: "", fullText: "You're going to water the plants before you leave, aren't you?\n(A) I walked the whole way.\n(B) Yes, right after lunch.\n(C) In the breakroom.", textWithBlanks: "You're going to ____ the plants before you ____, aren't you?\n(A) I ____ the whole way.\n(B) Yes, right after ____.\n(C) In the ____.", missingWords: ["water", "leave", "walked", "lunch", "breakroom"] };
const t2p2q10 = { id: 2210, title: "Question 10", audioSrc: "", fullText: "Aren't you going to schedule an eye doctor appointment?\n(A) Those glasses look nice on you.\n(B) I already scheduled one.\n(C) The seminar is three days long.", textWithBlanks: "Aren't you going to ____ an eye doctor ____?\n(A) Those ____ look nice on you.\n(B) I already ____ one.\n(C) The ____ is three days long.", missingWords: ["schedule", "appointment", "glasses", "scheduled", "seminar"] };
const t2p2q11 = { id: 2211, title: "Question 11", audioSrc: "", fullText: "I'm going to try to fix this printer.\n(A) You're right, it doesn't fit.\n(B) Double-sided copies.\n(C) Are you sure it can be repaired?", textWithBlanks: "I'm going to ____ to ____ this printer.\n(A) You're right, it doesn't ____.\n(B) Double-sided ____.\n(C) Are you sure it can be ____?", missingWords: ["try", "fix", "fit", "copies", "repaired"] };
const t2p2q12 = { id: 2212, title: "Question 12", audioSrc: "", fullText: "What should we do with these brochures?\n(A) A trip to the seashore.\n(B) Yes, I found it already.\n(C) I'll leave them at the front desk.", textWithBlanks: "What should we do with these ____?\n(A) A ____ to the seashore.\n(B) Yes, I ____ it already.\n(C) I'll ____ them at the front ____.", missingWords: ["brochures", "trip", "found", "leave", "desk"] };
const t2p2q13 = { id: 2213, title: "Question 13", audioSrc: "", fullText: "Has the policy meeting been rescheduled?\n(A) We have lots of desk calendar designs.\n(B) Yes, it's happening tomorrow instead.\n(C) This soup I ordered is delicious.", textWithBlanks: "Has the ____ meeting been ____?\n(A) We have lots of desk ____ designs.\n(B) Yes, it's ____ tomorrow instead.\n(C) This soup I ordered is ____.", missingWords: ["policy", "rescheduled", "calendar", "happening", "delicious"] };
const t2p2q14 = { id: 2214, title: "Question 14", audioSrc: "", fullText: "Why don't we stop by the office cafeteria on our way to the workshop?\n(A) Sure, we have time for that.\n(B) A full-service buffet.\n(C) The topic is professional networking.", textWithBlanks: "Why don't we ____ by the office ____ on our way to the ____?\n(A) Sure, we have ____ for that.\n(B) A full-service ____.\n(C) The topic is ____ networking.", missingWords: ["stop", "cafeteria", "workshop", "time", "buffet", "professional"] };
const t2p2q15 = { id: 2215, title: "Question 15", audioSrc: "", fullText: "Have you tried our famous pasta dish?\n(A) We need a table for five.\n(B) Yes, it was delicious.\n(C) I'll try to make it on time.", textWithBlanks: "Have you ____ our ____ pasta ____?\n(A) We need a ____ for five.\n(B) Yes, it was ____.\n(C) I'll try to make it on ____.", missingWords: ["tried", "famous", "dish", "table", "delicious", "time"] };
const t2p2q16 = { id: 2216, title: "Question 16", audioSrc: "", fullText: "Who's the opening act at tonight's concert?\n(A) Could you turn up the volume?\n(B) A jazz singer from France.\n(C) The position has been filled.", textWithBlanks: "Who's the ____ act at tonight's ____?\n(A) Could you turn up the ____?\n(B) A jazz ____ from France.\n(C) The ____ has been filled.", missingWords: ["opening", "concert", "volume", "singer", "position"] };
const t2p2q17 = { id: 2217, title: "Question 17", audioSrc: "", fullText: "When do the product demonstrations start?\n(A) The schedule was e-mailed last Friday.\n(B) Some innovative features.\n(C) In room 202, I think.", textWithBlanks: "When do the product ____ start?\n(A) The ____ was e-mailed last Friday.\n(B) Some ____ features.\n(C) In room 202, I ____.", missingWords: ["demonstrations", "schedule", "innovative", "think"] };
const t2p2q18 = { id: 2218, title: "Question 18", audioSrc: "", fullText: "I tried updating the Web site, but it didn't work.\n(A) That date works for me.\n(B) Usually our online reviews.\n(C) Just send me the changes you want.", textWithBlanks: "I ____ updating the Web site, but it didn't ____.\n(A) That ____ works for me.\n(B) Usually our online ____.\n(C) Just send me the ____ you want.", missingWords: ["tried", "work", "date", "reviews", "changes"] };
const t2p2q19 = { id: 2219, title: "Question 19", audioSrc: "", fullText: "Did you hire a new welding specialist?\n(A) The part's back-ordered.\n(B) Yes, he starts tomorrow.\n(C) No, it should be higher.", textWithBlanks: "Did you ____ a new ____ specialist?\n(A) The part's back-____.\n(B) Yes, he ____ tomorrow.\n(C) No, it should be ____.", missingWords: ["hire", "welding", "ordered", "starts", "higher"] };
const t2p2q20 = { id: 2220, title: "Question 20", audioSrc: "", fullText: "How was the color palette for the lobby chosen?\n(A) Blue and orange.\n(B) It was fine, thanks.\n(C) I wasn't involved.", textWithBlanks: "How was the color ____ for the ____ chosen?\n(A) Blue and ____.\n(B) It was ____, thanks.\n(C) I wasn't ____.", missingWords: ["palette", "lobby", "orange", "fine", "involved"] };
const t2p2q21 = { id: 2221, title: "Question 21", audioSrc: "", fullText: "When are we ordering more supplies for the office?\n(A) In the storage closet.\n(B) Next week on Monday.\n(C) The new desk looks great!", textWithBlanks: "When are we ____ more ____ for the office?\n(A) In the ____ closet.\n(B) Next week on ____.\n(C) The new desk looks ____!", missingWords: ["ordering", "supplies", "storage", "Monday", "great"] };
const t2p2q22 = { id: 2222, title: "Question 22", audioSrc: "", fullText: "The battery for the water pump is going to be solar powered, right?\n(A) We're still in the planning stages.\n(B) A hundred and forty dollars per year.\n(C) Yes, I'd love a glass of water.", textWithBlanks: "The ____ for the water ____ is going to be ____ powered, right?\n(A) We're still in the ____ stages.\n(B) A hundred and forty dollars per ____.\n(C) Yes, I'd love a glass of ____.", missingWords: ["battery", "pump", "solar", "planning", "year", "water"] };
const t2p2q23 = { id: 2223, title: "Question 23", audioSrc: "", fullText: "Where can I buy a charger for this laptop?\n(A) Around three o'clock.\n(B) I can order one for you.\n(C) A limited return policy.", textWithBlanks: "Where can I ____ a ____ for this laptop?\n(A) Around three o'clock.\n(B) I can ____ one for you.\n(C) A ____ return policy.", missingWords: ["buy", "charger", "order", "limited"] };
const t2p2q24 = { id: 2224, title: "Question 24", audioSrc: "", fullText: "Do I need to reserve a meeting room?\n(A) Yes, let me show you how.\n(B) The service is good.\n(C) My slide presentation.", textWithBlanks: "Do I need to ____ a ____ room?\n(A) Yes, let me ____ you how.\n(B) The ____ is good.\n(C) My slide ____.", missingWords: ["reserve", "meeting", "show", "service", "presentation"] };
const t2p2q25 = { id: 2225, title: "Question 25", audioSrc: "", fullText: "When's the new department director supposed to start?\n(A) It's an hour long.\n(B) Ms. Pavlova isn't retiring for several weeks.\n(C) No, that department's upstairs.", textWithBlanks: "When's the new ____ director ____ to start?\n(A) It's an hour ____.\n(B) Ms. Pavlova isn't ____ for several weeks.\n(C) No, that department's ____.", missingWords: ["department", "supposed", "long", "retiring", "upstairs"] };
const t2p2q26 = { id: 2226, title: "Question 26", audioSrc: "", fullText: "Should I deliver these pizzas, or will you?\n(A) No thanks-I'm not hungry.\n(B) Ten dollars for two.\n(C) They're being picked up.", textWithBlanks: "Should I ____ these ____, or will you?\n(A) No thanks-I'm not ____.\n(B) Ten dollars for two.\n(C) They're being ____ up.", missingWords: ["deliver", "pizzas", "hungry", "picked"] };
const t2p2q27 = { id: 2227, title: "Question 27", audioSrc: "", fullText: "This month's shipment schedule has been revised.\n(A) I couldn't find them either.\n(B) Which dates have been changed?\n(C) Two dollars per pound.", textWithBlanks: "This month's ____ schedule has been ____.\n(A) I couldn't ____ them either.\n(B) Which ____ have been changed?\n(C) Two dollars per ____.", missingWords: ["shipment", "revised", "find", "dates", "pound"] };
const t2p2q28 = { id: 2228, title: "Question 28", audioSrc: "", fullText: "How much will the repairs cost?\n(A) The work is covered under the warranty plan.\n(B) Yes, it's also available in red.\n(C) In about two weeks.", textWithBlanks: "How much will the ____ cost?\n(A) The work is ____ under the ____ plan.\n(B) Yes, it's also ____ in red.\n(C) In about two ____.", missingWords: ["repairs", "covered", "warranty", "available", "weeks"] };
const t2p2q29 = { id: 2229, title: "Question 29", audioSrc: "", fullText: "Why don't we provide more samples of the wallpaper patterns?\n(A) The newspaper is delivered daily.\n(B) An interior design course.\n(C) There are plenty in the binders.", textWithBlanks: "Why don't we ____ more ____ of the ____ patterns?\n(A) The newspaper is ____ daily.\n(B) An interior design ____.\n(C) There are ____ in the binders.", missingWords: ["provide", "samples", "wallpaper", "delivered", "course", "plenty"] };
const t2p2q30 = { id: 2230, title: "Question 30", audioSrc: "", fullText: "Can you give me a tour of the property this afternoon?\n(A) Sorry, I won't have time until tomorrow.\n(B) It has a very modern design.\n(C) A house on Maple Street.", textWithBlanks: "Can you give me a ____ of the ____ this afternoon?\n(A) Sorry, I won't have ____ until tomorrow.\n(B) It has a very ____ design.\n(C) A ____ on Maple Street.", missingWords: ["tour", "property", "time", "modern", "house"] };
const t2p2q31 = { id: 2231, title: "Question 31", audioSrc: "", fullText: "Who's scheduled to test the product today?\n(A) We're waiting for confirmation.\n(B) It's a great album, right?\n(C) About six weeks ago.", textWithBlanks: "Who's ____ to test the ____ today?\n(A) We're ____ for confirmation.\n(B) It's a great ____, right?\n(C) About six weeks ____.", missingWords: ["scheduled", "product", "waiting", "album", "ago"] };

// TOEIC TEST 3 EXERCISES - PART 2
const t3p2q7 = { id: 3207, title: "Question 7", audioSrc: "", fullText: "Why is there no flour on the shelf?\n(A) Because it's out of stock.\n(B) Those roses smell nice.\n(C) No, the other cake.", textWithBlanks: "Why is there no ____ on the ____?\n(A) Because it's out of ____.\n(B) Those ____ smell nice.\n(C) No, the other ____.", missingWords: ["flour", "shelf", "stock", "roses", "cake"] };
const t3p2q8 = { id: 3208, title: "Question 8", audioSrc: "", fullText: "When will the catering company arrive?\n(A) At four o'clock.\n(B) That's a delicious flavor.\n(C) Many vegetarian options.", textWithBlanks: "When will the ____ company ____?\n(A) At four o'clock.\n(B) That's a delicious ____.\n(C) Many ____ options.", missingWords: ["catering", "arrive", "flavor", "vegetarian"] };
const t3p2q9 = { id: 3209, title: "Question 9", audioSrc: "", fullText: "When's the meeting scheduled to start?\n(A) At a networking event.\n(B) I started this job six years ago.\n(C) Right after lunch.", textWithBlanks: "When's the ____ scheduled to ____?\n(A) At a ____ event.\n(B) I started this job six years ____.\n(C) Right after ____.", missingWords: ["meeting", "start", "networking", "ago", "lunch"] };
const t3p2q10 = { id: 3210, title: "Question 10", audioSrc: "", fullText: "How much will the repairs cost?\n(A) I have two pairs of shoes.\n(B) Around 200 dollars.\n(C) The restaurant downtown.", textWithBlanks: "How much will the ____ cost?\n(A) I have two ____ of shoes.\n(B) Around 200 ____.\n(C) The ____ downtown.", missingWords: ["repairs", "pairs", "dollars", "restaurant"] };
const t3p2q11 = { id: 3211, title: "Question 11", audioSrc: "", fullText: "You went to the dentist this morning, didn't you?\n(A) Oh, I've already had breakfast.\n(B) Yes, for an annual checkup.\n(C) Let's take the bus.", textWithBlanks: "You ____ to the ____ this morning, didn't you?\n(A) Oh, I've already had ____.\n(B) Yes, for an ____ checkup.\n(C) Let's take the ____.", missingWords: ["went", "dentist", "breakfast", "annual", "bus"] };
const t3p2q12 = { id: 3212, title: "Question 12", audioSrc: "", fullText: "Where should we put the new printer?\n(A) In the corner by the stairs.\n(B) The third page of the document.\n(C) A reusable ink cartridge.", textWithBlanks: "Where should we ____ the new ____?\n(A) In the ____ by the stairs.\n(B) The third page of the ____.\n(C) A reusable ink ____.", missingWords: ["put", "printer", "corner", "document", "cartridge"] };
const t3p2q13 = { id: 3213, title: "Question 13", audioSrc: "", fullText: "What type of plant do you have in your office?\n(A) Whenever I sit at my desk.\n(B) Thanks-I just bought it.\n(C) One that doesn't require much water.", textWithBlanks: "What ____ of ____ do you have in your office?\n(A) ____ I sit at my desk.\n(B) Thanks-I just ____ it.\n(C) One that doesn't ____ much water.", missingWords: ["type", "plant", "Whenever", "bought", "require"] };
const t3p2q14 = { id: 3214, title: "Question 14", audioSrc: "", fullText: "There was a sale at the furniture store.\n(A) No, it wasn't in storage.\n(B) Did you buy anything?\n(C) Some old receipts.", textWithBlanks: "There was a ____ at the ____ store.\n(A) No, it wasn't in ____.\n(B) Did you ____ anything?\n(C) Some old ____.", missingWords: ["sale", "furniture", "storage", "buy", "receipts"] };
const t3p2q15 = { id: 3215, title: "Question 15", audioSrc: "", fullText: "Can you show me how to submit a tech help ticket?\n(A) Let me send you the link.\n(B) A broken power cable.\n(C) No, over ten minutes.", textWithBlanks: "Can you ____ me how to ____ a tech help ____?\n(A) Let me ____ you the link.\n(B) A ____ power cable.\n(C) No, over ten ____.", missingWords: ["show", "submit", "ticket", "send", "broken", "minutes"] };
const t3p2q16 = { id: 3216, title: "Question 16", audioSrc: "", fullText: "Where is the power button on this device?\n(A) I've never used that model before.\n(B) Ten euros per hour.\n(C) We charge more for color photographs.", textWithBlanks: "Where is the ____ button on this ____?\n(A) I've never ____ that model before.\n(B) Ten ____ per hour.\n(C) We ____ more for color ____.", missingWords: ["power", "device", "used", "euros", "charge", "photographs"] };
const t3p2q17 = { id: 3217, title: "Question 17", audioSrc: "", fullText: "Do you want to take a walk now, or would later be better?\n(A) A nearby lake.\n(B) I'm free to walk now.\n(C) No, I don't use a fitness tracker.", textWithBlanks: "Do you want to ____ a walk now, or would ____ be better?\n(A) A ____ lake.\n(B) I'm ____ to walk now.\n(C) No, I don't use a ____ tracker.", missingWords: ["take", "later", "nearby", "free", "fitness"] };
const t3p2q18 = { id: 3218, title: "Question 18", audioSrc: "", fullText: "I ordered some new equipment for the factory.\n(A) The news program on Channel Ten.\n(B) Great-I can't wait to use it.\n(C) The car dealership.", textWithBlanks: "I ____ some new ____ for the factory.\n(A) The news ____ on Channel Ten.\n(B) Great-I can't ____ to use it.\n(C) The car ____.", missingWords: ["ordered", "equipment", "program", "wait", "dealership"] };
const t3p2q19 = { id: 3219, title: "Question 19", audioSrc: "", fullText: "There's a nice place to rent on Mercer Street.\n(A) I just renewed my current lease.\n(B) It was a great show.\n(C) A standard rental application.", textWithBlanks: "There's a nice ____ to ____ on Mercer Street.\n(A) I just ____ my current lease.\n(B) It was a ____ show.\n(C) A ____ rental application.", missingWords: ["place", "rent", "renewed", "great", "standard"] };
const t3p2q20 = { id: 3220, title: "Question 20", audioSrc: "", fullText: "Is the heating system working?\n(A) Yes, that's my Web site.\n(B) A five-kilometer run.\n(C) I just called maintenance.", textWithBlanks: "Is the ____ system ____?\n(A) Yes, that's my Web ____.\n(B) A five-kilometer ____.\n(C) I just ____ maintenance.", missingWords: ["heating", "working", "site", "run", "called"] };
const t3p2q21 = { id: 3221, title: "Question 21", audioSrc: "", fullText: "Isn't the roadwork in front of city hall finished yet?\n(A) I just finished my conference presentation.\n(B) A lot of traffic in the evening.\n(C) No, they still have another month to go.", textWithBlanks: "Isn't the ____ in front of city hall ____ yet?\n(A) I just ____ my conference presentation.\n(B) A lot of ____ in the evening.\n(C) No, they still have another ____ to go.", missingWords: ["roadwork", "finished", "finished", "traffic", "month"] };
const t3p2q22 = { id: 3222, title: "Question 22", audioSrc: "", fullText: "Who will lead the new-employee training today?\n(A) We're using a recorded video.\n(B) Yes, right after lunch.\n(C) Classroom 124.", textWithBlanks: "Who will ____ the new-employee ____ today?\n(A) We're using a ____ video.\n(B) Yes, right after ____.\n(C) ____ 124.", missingWords: ["lead", "training", "recorded", "lunch", "Classroom"] };
const t3p2q23 = { id: 3223, title: "Question 23", audioSrc: "", fullText: "Is the safety inspection scheduled for this month or next month?\n(A) I thought I saved the file.\n(B) The factory supervisor.\n(C) It's this Wednesday.", textWithBlanks: "Is the safety ____ scheduled for this ____ or next month?\n(A) I thought I ____ the file.\n(B) The factory ____.\n(C) It's this ____.", missingWords: ["inspection", "month", "saved", "supervisor", "Wednesday"] };
const t3p2q24 = { id: 3224, title: "Question 24", audioSrc: "", fullText: "When is the harvest festival taking place?\n(A) It's a week from tomorrow.\n(B) Sure, I can take it.\n(C) The park next to the art museum.", textWithBlanks: "When is the ____ festival ____ place?\n(A) It's a ____ from tomorrow.\n(B) Sure, I can take it.\n(C) The ____ next to the art museum.", missingWords: ["harvest", "taking", "week", "park"] };
const t3p2q25 = { id: 3225, title: "Question 25", audioSrc: "", fullText: "Was your new laptop expensive?\n(A) Do you have a new password?\n(B) I had a discount coupon.\n(C) On top of the cabinet.", textWithBlanks: "Was your new laptop ____?\n(A) Do you have a new ____?\n(B) I had a ____ coupon.\n(C) On ____ of the cabinet.", missingWords: ["expensive", "password", "discount", "top"] };
const t3p2q26 = { id: 3226, title: "Question 26", audioSrc: "", fullText: "Why don't we go on our camping trip next weekend?\n(A) Yes, that table lamp is quite nice.\n(B) Should we go left or right?\n(C) I have a performance scheduled with my band.", textWithBlanks: "Why don't we go on our ____ trip next ____?\n(A) Yes, that table ____ is quite nice.\n(B) Should we go ____ or right?\n(C) I have a ____ scheduled with my band.", missingWords: ["camping", "weekend", "lamp", "left", "performance"] };
const t3p2q27 = { id: 3227, title: "Question 27", audioSrc: "", fullText: "The workshop for this afternoon was postponed, wasn't it?\n(A) At the post office.\n(B) I haven't checked my e-mail.\n(C) A ticket for two o'clock, please.", textWithBlanks: "The ____ for this afternoon was ____, wasn't it?\n(A) At the post ____.\n(B) I haven't ____ my e-mail.\n(C) A ____ for two o'clock, please.", missingWords: ["workshop", "postponed", "office", "checked", "ticket"] };
const t3p2q28 = { id: 3228, title: "Question 28", audioSrc: "", fullText: "How were our production figures last month?\n(A) They produce electric cars.\n(B) Nine o'clock in the morning.\n(C) We were closed down for a week.", textWithBlanks: "How were our ____ figures last ____?\n(A) They ____ electric cars.\n(B) Nine o'clock in the ____.\n(C) We were ____ down for a week.", missingWords: ["production", "month", "produce", "morning", "closed"] };
const t3p2q29 = { id: 3229, title: "Question 29", audioSrc: "", fullText: "When can I see the speech therapist?\n(A) A one-hour session.\n(B) Just a microphone.\n(C) How about tomorrow afternoon?", textWithBlanks: "When can I ____ the speech ____?\n(A) A one-hour ____.\n(B) Just a ____.\n(C) How about tomorrow ____?", missingWords: ["see", "therapist", "session", "microphone", "afternoon"] };
const t3p2q30 = { id: 3230, title: "Question 30", audioSrc: "", fullText: "Aren't you picking up the clients from the airport?\n(A) A product demonstration.\n(B) No, I believe Tomoko is doing that.\n(C) He prefers an aisle seat.", textWithBlanks: "Aren't you ____ up the clients from the ____?\n(A) A product ____.\n(B) No, I ____ Tomoko is doing that.\n(C) He prefers an ____ seat.", missingWords: ["picking", "airport", "demonstration", "believe", "aisle"] };
const t3p2q31 = { id: 3231, title: "Question 31", audioSrc: "", fullText: "How was your morning client meeting?\n(A) It's great to meet you.\n(B) No, over in conference room two.\n(C) The contract is now officially signed.", textWithBlanks: "How was your ____ client meeting?\n(A) It's ____ to meet you.\n(B) No, over in ____ room two.\n(C) The ____ is now officially ____.", missingWords: ["morning", "great", "conference", "contract", "signed"] };

// TOEIC TEST 4 EXERCISES - PART 2
const t4p2q7 = { id: 4207, title: "Question 7", audioSrc: "", fullText: "Does the shop open on Sundays?\n(A) Yes, at one o'clock.\n(B) Because we drove.\n(C) I'd like to return this item, please.", textWithBlanks: "Does the ____ open on ____?\n(A) Yes, at one o'clock.\n(B) Because we ____.\n(C) I'd like to ____ this item, please.", missingWords: ["shop", "Sundays", "drove", "return"] };
const t4p2q8 = { id: 4208, title: "Question 8", audioSrc: "", fullText: "Where did these oranges come from?\n(A) Here's a basket you can use.\n(B) From a supplier in California.\n(C) That umbrella is a nice color.", textWithBlanks: "Where did these ____ come from?\n(A) Here's a ____ you can use.\n(B) From a ____ in California.\n(C) That ____ is a nice color.", missingWords: ["oranges", "basket", "supplier", "umbrella"] };
const t4p2q9 = { id: 4209, title: "Question 9", audioSrc: "", fullText: "Should I make the dinner reservation for Friday or Saturday?\n(A) The Beachside Bistro.\n(B) Saturday is better.\n(C) A large plate of pasta.", textWithBlanks: "Should I make the ____ reservation for ____ or Saturday?\n(A) The Beachside ____.\n(B) Saturday is ____.\n(C) A large ____ of pasta.", missingWords: ["dinner", "Friday", "Bistro", "better", "plate"] };
const t4p2q10 = { id: 4210, title: "Question 10", audioSrc: "", fullText: "Will Dr. Ivanova be late today?\n(A) No, you shouldn't have to wait long.\n(B) It's just under the desk.\n(C) Sure, I can do that for you.", textWithBlanks: "Will Dr. Ivanova be ____ today?\n(A) No, you shouldn't have to ____ long.\n(B) It's just ____ the desk.\n(C) Sure, I can do that for you.", missingWords: ["late", "wait", "under"] };
const t4p2q11 = { id: 4211, title: "Question 11", audioSrc: "", fullText: "Aren't there locker rooms at this gym?\n(A) These socks are quite comfortable.\n(B) She teaches an exercise class.\n(C) Yes, they're on the lower floor.", textWithBlanks: "Aren't there ____ rooms at this ____?\n(A) These ____ are quite comfortable.\n(B) She ____ an exercise class.\n(C) Yes, they're on the ____ floor.", missingWords: ["locker", "gym", "socks", "teaches", "lower"] };
const t4p2q12 = { id: 4212, title: "Question 12", audioSrc: "", fullText: "Who needs a copy of my safety training certificate?\n(A) Maksim does.\n(B) You can hang your vest on that hook.\n(C) No, I'm certain about that.", textWithBlanks: "Who ____ a copy of my ____ training certificate?\n(A) Maksim does.\n(B) You can ____ your vest on that hook.\n(C) No, I'm ____ about that.", missingWords: ["needs", "safety", "hang", "certain"] };
const t4p2q13 = { id: 4213, title: "Question 13", audioSrc: "", fullText: "Could you phone Mr. Feras and let him know we're in the hotel lobby?\n(A) Thank you, it was just renovated.\n(B) A free continental breakfast.\n(C) Yes, of course.", textWithBlanks: "Could you ____ Mr. Feras and let him ____ we're in the hotel ____?\n(A) Thank you, it was just ____.\n(B) A free continental ____.\n(C) Yes, of course.", missingWords: ["phone", "know", "lobby", "renovated", "breakfast"] };
const t4p2q14 = { id: 4214, title: "Question 14", audioSrc: "", fullText: "Where does she sell her handmade jewelry?\n(A) They'll give you a discount.\n(B) A pair of earrings.\n(C) At a store in the city center.", textWithBlanks: "Where does she ____ her ____ jewelry?\n(A) They'll give you a ____.\n(B) A pair of ____.\n(C) At a ____ in the city center.", missingWords: ["sell", "handmade", "discount", "earrings", "store"] };
const t4p2q15 = { id: 4215, title: "Question 15", audioSrc: "", fullText: "You're taking a business class in the afternoon, aren't you?\n(A) Actually, it's in the morning.\n(B) That office is on the corner.\n(C) I have the train schedule here.", textWithBlanks: "You're ____ a business ____ in the afternoon, aren't you?\n(A) ____, it's in the morning.\n(B) That office is on the ____.\n(C) I have the ____ schedule here.", missingWords: ["taking", "class", "Actually", "corner", "train"] };
const t4p2q16 = { id: 4216, title: "Question 16", audioSrc: "", fullText: "Could I see some sample floral arrangements before I order?\n(A) It's for an award ceremony.\n(B) A charge for expedited delivery.\n(C) Certainly, I have some right here.", textWithBlanks: "Could I ____ some sample ____ arrangements before I order?\n(A) It's for an ____ ceremony.\n(B) A ____ for expedited delivery.\n(C) ____, I have some right here.", missingWords: ["see", "floral", "award", "charge", "Certainly"] };
const t4p2q17 = { id: 4217, title: "Question 17", audioSrc: "", fullText: "Don't you want to buy the black sofa?\n(A) Some customer reviews.\n(B) We already have one.\n(C) I take my coffee with sugar.", textWithBlanks: "Don't you ____ to buy the black ____?\n(A) Some customer ____.\n(B) We already have one.\n(C) I take my ____ with sugar.", missingWords: ["want", "sofa", "reviews", "coffee"] };
const t4p2q18 = { id: 4218, title: "Question 18", audioSrc: "", fullText: "Do you have this jacket in a larger size?\n(A) Oh, I'm not a sales associate.\n(B) I've read the information packet.\n(C) A very large uniform.", textWithBlanks: "Do you have this ____ in a ____ size?\n(A) Oh, I'm not a ____ associate.\n(B) I've ____ the information packet.\n(C) A very large ____.", missingWords: ["jacket", "larger", "sales", "read", "uniform"] };
const t4p2q19 = { id: 4219, title: "Question 19", audioSrc: "", fullText: "Where did you first learn about the job opening?\n(A) Are there any outdoor tables available?\n(B) The door to the building is still open.\n(C) I read an online newspaper every morning.", textWithBlanks: "Where did you first ____ about the job ____?\n(A) Are there any ____ tables available?\n(B) The ____ to the building is still open.\n(C) I ____ an online newspaper every morning.", missingWords: ["learn", "opening", "outdoor", "door", "read"] };
const t4p2q20 = { id: 4220, title: "Question 20", audioSrc: "", fullText: "Should I bring anything to the meeting?\n(A) Probably in the conference room.\n(B) They were hired by our manager.\n(C) Do we have enough handouts?", textWithBlanks: "Should I ____ anything to the ____?\n(A) ____ in the conference room.\n(B) They were ____ by our manager.\n(C) Do we have ____ handouts?", missingWords: ["bring", "meeting", "Probably", "hired", "enough"] };
const t4p2q21 = { id: 4221, title: "Question 21", audioSrc: "", fullText: "What was the total charge for the hotel stay?\n(A) I'd have to look at the receipt.\n(B) The fitness center is across from the reception desk.\n(C) I'll be eating breakfast in my room.", textWithBlanks: "What was the total ____ for the ____ stay?\n(A) I'd have to look at the ____.\n(B) The fitness ____ is across from the reception desk.\n(C) I'll be ____ breakfast in my room.", missingWords: ["charge", "hotel", "receipt", "center", "eating"] };
const t4p2q22 = { id: 4222, title: "Question 22", audioSrc: "", fullText: "Why did you pursue a career in video game design?\n(A) Because I have a talent for it.\n(B) This is my new laptop.\n(C) It's on the other shelf.", textWithBlanks: "Why did you ____ a ____ in video game design?\n(A) Because I have a ____ for it.\n(B) This is my new ____.\n(C) It's on the other ____.", missingWords: ["pursue", "career", "talent", "laptop", "shelf"] };
const t4p2q23 = { id: 4223, title: "Question 23", audioSrc: "", fullText: "I'd like to attend the job fair next month.\n(A) The speech was inspiring.\n(B) Tunji updated the memo.\n(C) Registration closed yesterday.", textWithBlanks: "I'd like to ____ the job ____ next month.\n(A) The ____ was inspiring.\n(B) Tunji ____ the memo.\n(C) ____ closed yesterday.", missingWords: ["attend", "fair", "speech", "updated", "Registration"] };
const t4p2q24 = { id: 4224, title: "Question 24", audioSrc: "", fullText: "Hasn't anyone called you back for the second interview yet?\n(A) A new phone number.\n(B) Yes, any available position.\n(C) I'm still waiting.", textWithBlanks: "Hasn't anyone ____ you back for the second ____ yet?\n(A) A new phone ____.\n(B) Yes, any ____ position.\n(C) I'm still ____.", missingWords: ["called", "interview", "number", "available", "waiting"] };
const t4p2q25 = { id: 4225, title: "Question 25", audioSrc: "", fullText: "How many tickets do we need for tonight's concert?\n(A) The theater is on Johnson Avenue.\n(B) At seven thirty sharp.\n(C) I'll buy mine at the door.", textWithBlanks: "How many ____ do we need for tonight's ____?\n(A) The ____ is on Johnson Avenue.\n(B) At seven thirty ____.\n(C) I'll ____ mine at the door.", missingWords: ["tickets", "concert", "theater", "sharp", "buy"] };
const t4p2q26 = { id: 4226, title: "Question 26", audioSrc: "", fullText: "When are they going to decide who to hire?\n(A) A much higher salary.\n(B) A lot of good résumés have come in.\n(C) In the building across the street.", textWithBlanks: "When are they going to ____ who to ____?\n(A) A much higher ____.\n(B) A lot of good ____ have come in.\n(C) In the ____ across the street.", missingWords: ["decide", "hire", "salary", "résumés", "building"] };
const t4p2q27 = { id: 4227, title: "Question 27", audioSrc: "", fullText: "I had a chance to look over the contract this morning.\n(A) Their contact information.\n(B) Early next week.\n(C) What did you think of it?", textWithBlanks: "I had a ____ to look over the ____ this morning.\n(A) Their ____ information.\n(B) ____ next week.\n(C) What did you ____ of it?", missingWords: ["chance", "contract", "contact", "Early", "think"] };
const t4p2q28 = { id: 4228, title: "Question 28", audioSrc: "", fullText: "How are the database updates coming along?\n(A) I've been really busy with the Williams account.\n(B) Some customer addresses.\n(C) She arrives on Wednesday.", textWithBlanks: "How are the ____ updates ____ along?\n(A) I've been really ____ with the Williams account.\n(B) Some customer ____.\n(C) She ____ on Wednesday.", missingWords: ["database", "coming", "busy", "addresses", "arrives"] };
const t4p2q29 = { id: 4229, title: "Question 29", audioSrc: "", fullText: "When can I bring these boxes into the warehouse?\n(A) Ten in a package.\n(B) Thanks-I just bought it.\n(C) We'll need to clear some space.", textWithBlanks: "When can I ____ these boxes into the ____?\n(A) Ten in a ____.\n(B) Thanks-I just ____ it.\n(C) We'll need to ____ some space.", missingWords: ["bring", "warehouse", "package", "bought", "clear"] };
const t4p2q30 = { id: 4230, title: "Question 30", audioSrc: "", fullText: "The market on Fifth Street is closed for a week.\n(A) Some new clothes.\n(B) Is there another one nearby?\n(C) The price has been marked down.", textWithBlanks: "The ____ on Fifth Street is ____ for a week.\n(A) Some new ____.\n(B) Is there another one ____?\n(C) The ____ has been marked down.", missingWords: ["market", "closed", "clothes", "nearby", "price"] };
const t4p2q31 = { id: 4231, title: "Question 31", audioSrc: "", fullText: "Does the company pay for professional-development courses?\n(A) Insook helped develop a new product.\n(B) We do have a significant budget surplus.\n(C) He's always so professional.", textWithBlanks: "Does the ____ pay for professional-____ courses?\n(A) Insook helped ____ a new product.\n(B) We do have a ____ budget surplus.\n(C) He's always so ____.", missingWords: ["company", "development", "develop", "significant", "professional"] };

// BASE EXERCISES - PART 2
const q7 = { id: 207, title: "Question 7", audioSrc: "", fullText: "How old is this building?\n(A) To ship some materials.\n(B) About ten years old.\n(C) Company offices, I think.", textWithBlanks: "How ____ is this ____?\n(A) To ____ some materials.\n(B) About ten ____ old.\n(C) Company ____, I think.", missingWords: ["old", "building", "ship", "years", "offices"] };
const q8 = { id: 208, title: "Question 8", audioSrc: "", fullText: "Can you come to my jazz performance tonight?\n(A) I’m sorry I was late for the meeting.\n(B) Mostly just local musicians.\n(C) Sure, I'll be there!", textWithBlanks: "Can you ____ to my jazz ____ tonight?\n(A) I’m ____ I was late for the meeting.\n(B) ____ just local musicians.\n(C) Sure, I'll be ____!", missingWords: ["come", "performance", "sorry", "Mostly", "there"] };
const q9 = { id: 209, title: "Question 9", audioSrc: "", fullText: "Which apartment submitted a work order?\n(A) It’s what you did for a living.\n(B) Submit your assignment here.\n(C) It came from the tenants in B23.", textWithBlanks: "Which ____ submitted a work ____?\n(A) It’s what you did for a ____.\n(B) ____ your assignment here.\n(C) It came from the ____ in B23.", missingWords: ["apartment", "order", "living", "Submit", "tenants"] };
const q10 = { id: 210, title: "Question 10", audioSrc: "", fullText: "Will you contact the vendor about changing our delivery date?\n(A) Of course, I'll take care of it.\n(B) An e-mail receipt.\n(C) Could I get change for a dollar?", textWithBlanks: "Will you ____ the ____ about changing our ____ date?\n(A) Of course, I'll take ____ of it.\n(B) An e-mail ____.\n(C) Could I get ____ for a dollar?", missingWords: ["contact", "vendor", "delivery", "care", "receipt", "change"] };
const q11 = { id: 211, title: "Question 11", audioSrc: "", fullText: "Why was the maintenance worker here?\n(A) No, he didn’t.\n(B) From three o’clock until four.\n(C) Because a light needed to be fixed.", textWithBlanks: "Why was the ____ worker here?\n(A) No, he didn’t.\n(B) From three o’clock ____ four.\n(C) Because a ____ needed to be ____.", missingWords: ["maintenance", "until", "light", "fixed"] };
const q12 = { id: 212, title: "Question 12", audioSrc: "", fullText: "Did management make a hiring decision yet?\n(A) Put it on the highest shelf.\n(B) The personnel department.\n(C) Yes, they chose Jacob Borgman.", textWithBlanks: "Did ____ make a ____ decision yet?\n(A) Put it on the ____ shelf.\n(B) The ____ department.\n(C) Yes, they ____ Jacob Borgman.", missingWords: ["management", "hiring", "highest", "personnel", "chose"] };
const q13 = { id: 213, title: "Question 13", audioSrc: "", fullText: "Do you want to eat here in our cafeteria or go out?\n(A) He went there yesterday.\n(B) Well, maybe a sandwich.\n(C) Let’s eat here.", textWithBlanks: "Do you want to ____ here in our ____ or go out?\n(A) He ____ there yesterday.\n(B) Well, maybe a ____.\n(C) Let’s ____ here.", missingWords: ["eat", "cafeteria", "went", "sandwich", "eat"] };
const q14 = { id: 214, title: "Question 14", audioSrc: "", fullText: "Didn’t you e-mail the employment contract to Mr. Patel yesterday?\n(A) Yes, I would agree.\n(B) No, I'll send it now.\n(C) Check the employee manual.", textWithBlanks: "Didn’t you e-mail the ____ contract to Mr. Patel ____?\n(A) Yes, I would ____.\n(B) No, I'll ____ it now.\n(C) ____ the employee manual.", missingWords: ["employment", "yesterday", "agree", "send", "Check"] };
const q15 = { id: 215, title: "Question 15", audioSrc: "", fullText: "Our division’s picnic is this Saturday, right?\n(A) There’s a lot of rain in the forecast.\n(B) Sure, I like salad.\n(C) At the end of this corridor.", textWithBlanks: "Our ____ picnic is this ____, right?\n(A) There’s a lot of ____ in the forecast.\n(B) Sure, I like ____.\n(C) At the ____ of this corridor.", missingWords: ["division’s", "Saturday", "rain", "salad", "end"] };
const q16 = { id: 216, title: "Question 16", audioSrc: "", fullText: "Would you like coffee or tea?\n(A) Just water, please.\n(B) For a few dollars more.\n(C) A fifteen-minute break.", textWithBlanks: "Would you like ____ or ____?\n(A) Just ____, please.\n(B) For a few ____ more.\n(C) A fifteen-minute ____.", missingWords: ["coffee", "tea", "water", "dollars", "break"] };
const q17 = { id: 217, title: "Question 17", audioSrc: "", fullText: "We achieved our sales targets this month.\n(A) That’s excellent news!\n(B) A few times a day.\n(C) To the end of April.", textWithBlanks: "We ____ our sales ____ this month.\n(A) That’s ____ news!\n(B) A few ____ a day.\n(C) To the end of ____.", missingWords: ["achieved", "targets", "excellent", "times", "April"] };
const q18 = { id: 218, title: "Question 18", audioSrc: "", fullText: "How often do you travel for your job?\n(A) It turned out well.\n(B) Yes, I did find one.\n(C) About once a month.", textWithBlanks: "How ____ do you ____ for your job?\n(A) It ____ out well.\n(B) Yes, I did ____ one.\n(C) About ____ a month.", missingWords: ["often", "travel", "turned", "find", "once"] };
const q19 = { id: 219, title: "Question 19", audioSrc: "", fullText: "We should hike the Wildflower Trail today.\n(A) This seat is available.\n(B) I didn’t bring boots.\n(C) At the visitors’ center.", textWithBlanks: "We should ____ the Wildflower ____ today.\n(A) This ____ is available.\n(B) I didn’t ____ boots.\n(C) At the ____ center.", missingWords: ["hike", "Trail", "seat", "bring", "visitors’"] };
const q20 = { id: 220, title: "Question 20", audioSrc: "", fullText: "You’ve booked a hotel in London, haven’t you?\n(A) Very enjoyable, thanks.\n(B) He usually takes the train.\n(C) Yes, I made a reservation last week.", textWithBlanks: "You’ve ____ a hotel in London, ____ you?\n(A) Very ____, thanks.\n(B) He ____ takes the train.\n(C) Yes, I ____ a reservation last week.", missingWords: ["booked", "haven’t", "enjoyable", "usually", "made"] };
const q21 = { id: 221, title: "Question 21", audioSrc: "", fullText: "Are there any tickets left for tonight’s concert?\n(A) It’s sold out.\n(B) He’s a concert violinist.\n(C) They already left.", textWithBlanks: "Are there any ____ left for tonight’s ____?\n(A) It’s ____ out.\n(B) He’s a concert ____.\n(C) They already ____.", missingWords: ["tickets", "concert", "sold", "violinist", "left"] };
const q22 = { id: 222, title: "Question 22", audioSrc: "", fullText: "Haven't you used this software before?\n(A) Can I take your order?\n(B) I haven’t had the chance.\n(C) About 40 dollars.", textWithBlanks: "Haven't you ____ this ____ before?\n(A) Can I take your ____?\n(B) I haven’t had the ____.\n(C) About 40 ____.", missingWords: ["used", "software", "order", "chance", "dollars"] };
const q23 = { id: 223, title: "Question 23", audioSrc: "", fullText: "When is the new blender going to be released?\n(A) Only with fruits and vegetables.\n(B) In the kitchen cabinet.\n(C) The prototype is still being tested.", textWithBlanks: "When is the new ____ going to be ____?\n(A) Only with ____ and vegetables.\n(B) In the kitchen ____.\n(C) The ____ is still being tested.", missingWords: ["blender", "released", "fruits", "cabinet", "prototype"] };
const q24 = { id: 224, title: "Question 24", audioSrc: "", fullText: "Who’s picking up our clients at the airport?\n(A) They decided to drive.\n(B) At terminal 2.\n(C) It’s a marketing position.", textWithBlanks: "Who’s ____ up our ____ at the airport?\n(A) They ____ to drive.\n(B) At ____ 2.\n(C) It’s a marketing ____.", missingWords: ["picking", "clients", "decided", "terminal", "position"] };
const q25 = { id: 225, title: "Question 25", audioSrc: "", fullText: "Where are the red roses that came in this morning?\n(A) About three liters of water.\n(B) No, I didn’t check out the sale.\n(C) I needed some for a large bouquet.", textWithBlanks: "Where are the red ____ that came in this ____?\n(A) About three ____ of water.\n(B) No, I didn’t ____ out the sale.\n(C) I ____ some for a large ____.", missingWords: ["roses", "morning", "liters", "check", "needed", "bouquet"] };
const q26 = { id: 226, title: "Question 26", audioSrc: "", fullText: "This film has been nominated for several awards.\n(A) Why don’t we go see it?\n(B) After the announcement.\n(C) He made a great speech.", textWithBlanks: "This ____ has been ____ for several ____.\n(A) Why don’t we go ____ it?\n(B) After the ____.\n(C) He made a great ____.", missingWords: ["film", "nominated", "awards", "see", "announcement", "speech"] };
const q27 = { id: 227, title: "Question 27", audioSrc: "", fullText: "Who's interested in starting a car pool program?\n(A) Thanks, but I can't swim.\n(B) Clara’s already organizing one.\n(C) It’s a very interesting article.", textWithBlanks: "Who's ____ in starting a car ____ program?\n(A) Thanks, but I can't ____.\n(B) Clara’s already ____ one.\n(C) It’s a very ____ article.", missingWords: ["interested", "pool", "swim", "organizing", "interesting"] };
const q28 = { id: 228, title: "Question 28", audioSrc: "", fullText: "Where will I teach my workshop this month?\n(A) We just sent an e-mail to all instructors.\n(B) Five to seven months.\n(C) Yes, it’s a beautiful building.", textWithBlanks: "Where will I ____ my ____ this month?\n(A) We just ____ an e-mail to all instructors.\n(B) Five to seven ____.\n(C) Yes, it’s a ____ building.", missingWords: ["teach", "workshop", "sent", "months", "beautiful"] };
const q29 = { id: 229, title: "Question 29", audioSrc: "", fullText: "Why are we moving these sweaters to the back of the store?\n(A) In the new shopping mall.\n(B) Yes, they come in other colors.\n(C) Our spring merchandise is arriving soon.", textWithBlanks: "Why are we ____ these sweaters to the ____ of the store?\n(A) In the new ____ mall.\n(B) Yes, they come in other ____.\n(C) Our ____ merchandise is arriving soon.", missingWords: ["moving", "back", "shopping", "colors", "spring"] };
const q30 = { id: 230, title: "Question 30", audioSrc: "", fullText: "Would you be interested in working on some of these contracts?\n(A) Thank you for meeting me.\n(B) A contact lens prescription.\n(C) I have very limited time.", textWithBlanks: "Would you be ____ in ____ on some of these contracts?\n(A) Thank you for ____ me.\n(B) A contact lens ____.\n(C) I have very ____ time.", missingWords: ["interested", "working", "meeting", "prescription", "limited"] };
const q31 = { id: 231, title: "Question 31", audioSrc: "", fullText: "What type of job are you looking for?\n(A) No, at ten a.m.\n(B) I really like working with computers.\n(C) Just a résumé is needed.", textWithBlanks: "What ____ of job are you ____ for?\n(A) No, at ____ a.m.\n(B) I really ____ working with computers.\n(C) Just a résumé is ____.", missingWords: ["type", "looking", "ten", "like", "needed"] };


export const dictationPart2Data: DictationPart = {
    id: 2,
    title: "Part 2: Question-Response",
    description: "Listen to a question and choose the most appropriate response from three options.",
    tests: [
        { id: 1, title: "Test 1", exercises: [
            q7, q8, q9, q10, q11,
            q12, q13, q14, q15, q16,
            q17, q18, q19, q20, q21,
            q22, q23, q24, q25, q26,
            q27, q28, q29, q30, q31
        ] },
        { id: 2, title: "Test 2", exercises: [
            t2p2q7, t2p2q8, t2p2q9, t2p2q10, t2p2q11, t2p2q12, t2p2q13, t2p2q14, t2p2q15, t2p2q16, 
            t2p2q17, t2p2q18, t2p2q19, t2p2q20, t2p2q21, t2p2q22, t2p2q23, t2p2q24, t2p2q25, t2p2q26, 
            t2p2q27, t2p2q28, t2p2q29, t2p2q30, t2p2q31
        ] },
        { id: 3, title: "Test 3", exercises: [
            t3p2q7, t3p2q8, t3p2q9, t3p2q10, t3p2q11, t3p2q12, t3p2q13, t3p2q14, t3p2q15, t3p2q16,
            t3p2q17, t3p2q18, t3p2q19, t3p2q20, t3p2q21, t3p2q22, t3p2q23, t3p2q24, t3p2q25, t3p2q26,
            t3p2q27, t3p2q28, t3p2q29, t3p2q30, t3p2q31
        ] },
        { id: 4, title: "Test 4", exercises: [
            t4p2q7, t4p2q8, t4p2q9, t4p2q10, t4p2q11, t4p2q12, t4p2q13, t4p2q14, t4p2q15, t4p2q16,
            t4p2q17, t4p2q18, t4p2q19, t4p2q20, t4p2q21, t4p2q22, t4p2q23, t4p2q24, t4p2q25, t4p2q26,
            t4p2q27, t4p2q28, t4p2q29, t4p2q30, t4p2q31
        ] },
        { id: 5, title: "Test 5", exercises: [t5p2q7, t5p2q8, t5p2q9, t5p2q10, t5p2q11, t5p2q12, t5p2q13, t5p2q14, t5p2q15, t5p2q16, t5p2q17, t5p2q18, t5p2q19, t5p2q20, t5p2q21, t5p2q22, t5p2q23, t5p2q24, t5p2q25, t5p2q26, t5p2q27, t5p2q28, t5p2q29, t5p2q30, t5p2q31] },
        { id: 6, title: "Test 6", exercises: [
            t2p2q7, t2p2q8, t2p2q9, t2p2q10, t2p2q11, t2p2q12, t2p2q13, t2p2q14, t2p2q15, t2p2q16, 
            t2p2q17, t2p2q18, t2p2q19, t2p2q20, t2p2q21, t2p2q22, t2p2q23, t2p2q24, t2p2q25, t2p2q26, 
            t2p2q27, t2p2q28, t2p2q29, t2p2q30, t2p2q31
        ] },
        { id: 7, title: "Test 7", exercises: [
            t3p2q7, t3p2q8, t3p2q9, t3p2q10, t3p2q11, t3p2q12, t3p2q13, t3p2q14, t3p2q15, t3p2q16, 
            t3p2q17, t3p2q18, t3p2q19, t3p2q20, t3p2q21, t3p2q22, t3p2q23, t3p2q24, t3p2q25, t3p2q26, 
            t3p2q27, t3p2q28, t3p2q29, t3p2q30, t3p2q31
        ] },
        { id: 8, title: "Test 8", exercises: [
            t2p2q7, t2p2q8, t2p2q9, t2p2q10, t2p2q11, t2p2q12, t2p2q13, t2p2q14, t2p2q15, t2p2q16, 
            t2p2q17, t2p2q18, t2p2q19, t2p2q20, t2p2q21, t2p2q22, t2p2q23, t2p2q24, t2p2q25, t2p2q26, 
            t2p2q27, t2p2q28, t2p2q29, t2p2q30, t2p2q31
        ] },
    ]
};
