import { DictationPart } from '../types';

// TOEIC TEST 5 EXERCISES - PART 3
const t5p3q32_34 = { id: 5332, title: "Test 5 - Part 3 - Q32-34", audioSrc: "", fullText: "Hi, Shenchao. I'm practicing my presentation in the conference room across the hall, and the projector in there keeps shutting off. I think it's overheating. Has this happened to you? Oh, that projector is old. It really needs to be replaced. If I were you, I'd just move to room 204 and practice there. Also, that room has a window. It's much nicer. OK. Thanks. By the way, you'll need a special cable to connect to the control panel in that room. Here, you can use this one. Just leave it plugged in when you're finished.", textWithBlanks: "Hi, Shenchao. I'm ____ my ____ in the ____ room across the ____, and the ____ in there keeps ____ off. I think it's ____. Has this ____ to you? Oh, that projector is old. It really needs to be ____. If I were you, I'd just ____ to room 204 and practice there. Also, that room has a ____. It's much nicer. OK. Thanks. By the way, you'll need a ____ cable to ____ to the control ____ in that room. Here, you can use this one. Just leave it ____ in when you're ____.", missingWords: ["practicing", "presentation", "conference", "hall", "projector", "shutting", "overheating", "happened", "replaced", "move", "window", "special", "connect", "panel", "plugged", "finished"] };
const t5p3q35_37 = { id: 5335, title: "Test 5 - Part 3 - Q35-37", audioSrc: "", fullText: "Hi. I'm Amanda Hoffman, and I'm on the panel of publishing experts. I was told to check in here at the registration desk. Yes, Ms. Hoffman. Welcome to the Portland Literary Conference. Here's your registration packet, which includes a gift card to thank you for participating. Oh, thank you. Just to confirm, the panel discussion begins at three p.m., right? Yes, but we do ask that all panel members arrive ten minutes beforehand. I hope you enjoy the conference!", textWithBlanks: "Hi. I'm Amanda Hoffman, and I'm on the ____ of publishing ____. I was ____ to check in here at the ____ desk. Yes, Ms. Hoffman. ____ to the Portland Literary Conference. Here's your registration ____, which ____ a gift card to thank you for ____. Oh, thank you. Just to ____, the panel ____ begins at three p.m., right? Yes, but we do ask that all panel members ____ ten minutes ____. I hope you enjoy the conference!", missingWords: ["panel", "experts", "told", "registration", "Welcome", "packet", "includes", "participating", "confirm", "discussion", "arrive", "beforehand"] };
const t5p3q38_40 = { id: 5338, title: "Test 5 - Part 3 - Q38-40", audioSrc: "", fullText: "I'm looking for a gift for my brother's birthday party this weekend. He loves teas, and you have so many varieties! Well, I could recommend a quality brand if you know what type he enjoys. Oh, I'm not sure. Hmm. Maybe I should get him a gift card so he can choose his own. That's a good idea. I'll get one for 50 dollars. Do your cards have an expiration date? Yes. We ask that they be used within one year of purchase.", textWithBlanks: "I'm looking for a ____ for my brother's ____ party this ____. He loves teas, and you have so many ____! Well, I could ____ a quality brand if you know what type he ____. Oh, I'm not sure. Hmm. Maybe I should get him a gift ____ so he can ____ his own. That's a good idea. I'll get one for 50 dollars. Do your cards have an ____ date? Yes. We ask that they be used within one year of ____.", missingWords: ["gift", "birthday", "weekend", "varieties", "recommend", "enjoys", "card", "choose", "expiration", "purchase"] };
const t5p3q41_43 = { id: 5341, title: "Test 5 - Part 3 - Q41-43", audioSrc: "", fullText: "Thanks for meeting with us, Ms. Raj. We're excited to learn about the product your company has developed for factories like ours. I'm happy to tell you about it. It's an application to monitor factory machines. It identifies problems in operations and generates a report about the efficiency of each machine. That sounds great! We have about 100 machine operators here. How much training would be involved? About an hour's worth. We provide a video with step-by-step instructions. Excellent. That's good to know.", textWithBlanks: "Thanks for ____ with us, Ms. Raj. We're ____ to learn about the product your company has ____ for ____ like ours. I'm ____ to tell you about it. It's an ____ to ____ factory machines. It ____ problems in ____ and generates a report about the ____ of each machine. That sounds ____! We have about 100 machine ____ here. How much ____ would be involved? About an hour's worth. We ____ a video with step-by-step ____. Excellent. That's good to know.", missingWords: ["meeting", "excited", "developed", "factories", "happy", "application", "monitor", "identifies", "operations", "efficiency", "great", "operators", "training", "provide", "instructions"] };
const t5p3q44_46 = { id: 5344, title: "Test 5 - Part 3 - Q44-46", audioSrc: "", fullText: "Hi. I’d like to go to the Baldwin Theater. The address is 91 Circle Drive. Sure, but did you know they’re resurfacing Circle Drive? I just dropped someone off in that area. Oh, really? I’ve got a ticket to a play, and the show starts at seven thirty. They don’t let you in if you’re late. Well, let me see. I can turn onto Felton Street and cut over to Lancaster Drive. It’s a little out of the way, but it’ll get you close to the theater.", textWithBlanks: "Hi. I’d like to go to the Baldwin ____. The address is 91 Circle Drive. Sure, but did you know they’re ____ Circle Drive? I just ____ someone off in that ____. Oh, really? I’ve got a ____ to a play, and the show ____ at seven thirty. They don’t let you in if you’re ____. Well, let me see. I can ____ onto Felton Street and cut over to Lancaster Drive. It’s a little out of the ____, but it’ll get you ____ to the theater.", missingWords: ["Theater", "resurfacing", "dropped", "area", "ticket", "starts", "late", "turn", "way", "close"] };
const t5p3q47_49 = { id: 5347, title: "Test 5 - Part 3 - Q47-49", audioSrc: "", fullText: "Do you have a minute to discuss the budget for the upcoming Vancouver meeting? I've looked over the travel requests you submitted for your team. Last year we sent only two representatives. Ms. Tamura has just given us approval to send three. In fact, the clients are looking to expand their online service options, and the third representative we're bringing is particularly knowledgeable about that. OK. I guess we'll have to find savings somewhere else, then. I've already looked into some new meeting venues. The Renova Hotel is offering discounted corporate rates this month.", textWithBlanks: "Do you have a ____ to discuss the ____ for the ____ Vancouver meeting? I've looked over the travel ____ you submitted for your team. Last year we sent only two ____. Ms. Tamura has just given us ____ to send three. In fact, the ____ are looking to ____ their online service ____, and the third representative we're bringing is particularly ____ about that. OK. I guess we'll have to find ____ somewhere else, then. I've already looked into some new meeting ____. The Renova Hotel is offering ____ corporate ____ this month.", missingWords: ["minute", "budget", "upcoming", "requests", "representatives", "approval", "clients", "expand", "options", "knowledgeable", "savings", "venues", "discounted", "rates"] };
const t5p3q50_52 = { id: 5350, title: "Test 5 - Part 3 - Q50-52", audioSrc: "", fullText: "Good morning. I wanted to meet today to discuss the recent decline in our museum’s ticket sales. You’re the outreach coordinator, so I’m hoping you might have some ideas on how we can attract more community involvement. Well, I recently read an article about a museum in Chicago that has a room where visitors can paint on the walls. It’s become very popular. We could try it here—we have that huge room on the third floor that isn’t being used. That’s a great idea. Can you draft a list of the supplies we would need to make sure we have the budget for them?", textWithBlanks: "Good morning. I ____ to meet today to ____ the recent ____ in our museum’s ticket ____. You’re the ____ coordinator, so I’m hoping you might have some ____ on how we can ____ more community ____. Well, I recently read an ____ about a museum in Chicago that has a room where ____ can paint on the walls. It’s become very ____. We could try it here—we have that huge room on the third floor that isn’t being ____. That’s a great idea. Can you ____ a list of the ____ we would need to make sure we have the ____ for them?", missingWords: ["wanted", "discuss", "decline", "sales", "outreach", "ideas", "attract", "involvement", "article", "visitors", "popular", "used", "draft", "supplies", "budget"] };
const t5p3q53_55 = { id: 5353, title: "Test 5 - Part 3 - Q53-55", audioSrc: "", fullText: "Thilo, this is Ms. Gao, a new customer. She's purchasing an upholstered sofa. We just walked around our showroom, and she's decided on our Hudson model. One of our best sellers! It is really comfortable. Can you assist her with the paperwork for our payment plan? Sure. Happy to help you, Ms. Gao. Are you getting the standard fabric? No—I’d like to select a custom fabric. Just so you know, the price will increase some with a custom order. I think it's worth the extra cost. It'll really brighten up my living room. Wonderful. Now in order to set up a payment plan, I’ll need to see some identification. A driver’s license will do.", textWithBlanks: "Thilo, this is Ms. Gao, a new ____. She's ____ an ____ sofa. We just ____ around our ____, and she's decided on our Hudson model. One of our best sellers! It is really ____. Can you ____ her with the ____ for our payment plan? Sure. Happy to help you, Ms. Gao. Are you getting the ____ fabric? No—I’d like to select a ____ fabric. Just so you know, the price will ____ some with a custom order. I think it's ____ the extra cost. It'll really ____ up my living room. Wonderful. Now in order to set up a payment plan, I’ll need to see some ____. A driver’s ____ will do.", missingWords: ["customer", "purchasing", "upholstered", "walked", "showroom", "comfortable", "assist", "paperwork", "standard", "custom", "increase", "worth", "brighten", "identification", "license"] };
const t5p3q56_58 = { id: 5356, title: "Test 5 - Part 3 - Q56-58", audioSrc: "", fullText: "Good morning, Mr. Tong. I’m here to check on my order. How are the chairs coming along? The machines have been assembling them. They’re almost ready. Right over here. Wow, they look so nice! Look at the curved shape of the back. The only way you can get that unique shape is by means of the specialized laser we use. Amazing! Can I also see the pullout sofa? Not right now. It’s being treated with mineral oil. But later today I should be able to take a photo and send it to you.", textWithBlanks: "Good morning, Mr. Tong. I’m here to ____ on my order. How are the chairs coming ____? The machines have been ____ them. They’re almost ____. Right over here. Wow, they look so nice! Look at the ____ shape of the back. The only way you can get that ____ shape is by ____ of the ____ laser we use. Amazing! Can I also see the ____ sofa? Not right now. It’s being ____ with mineral oil. But later today I should be able to take a ____ and send it to you.", missingWords: ["check", "along", "assembling", "ready", "curved", "unique", "means", "specialized", "pullout", "treated", "photo"] };
const t5p3q59_61 = { id: 5359, title: "Test 5 - Part 3 - Q59-61", audioSrc: "", fullText: "Hi, So-Jin. I just heard that Ms. Yoon is retiring next month. I'll be sorry to see her go. She was my mentor when I first joined the firm, and we've worked on dozens of projects together. It's a bit hard to imagine our sales team without her. Has anybody approached you about leading the team after she's gone? Yes, and I've thought about it. It's a big step up, even for someone like me who's worked in Sales for eight years. And Human Resources hasn't even posted the job description yet. Well, we need someone with experience.", textWithBlanks: "Hi, So-Jin. I just ____ that Ms. Yoon is ____ next month. I'll be ____ to see her go. She was my ____ when I first ____ the firm, and we've worked on ____ of projects together. It's a bit hard to ____ our sales team without her. Has anybody ____ you about ____ the team after she's gone? Yes, and I've ____ about it. It's a big ____ up, even for someone like me who's worked in Sales for eight years. And Human Resources hasn't even ____ the job ____ yet. Well, we need someone with ____.", missingWords: ["heard", "retiring", "sorry", "mentor", "joined", "dozens", "imagine", "approached", "leading", "thought", "step", "posted", "description", "experience"] };
const t5p3q62_64 = { id: 5362, title: "Test 5 - Part 3 - Q62-64", audioSrc: "", fullText: "Rajesh, it was nice to see you here in New York again this year. Same here. I look forward to attending the Theater Technology Conference again next year. I really enjoyed your talk, especially the information you provided on acoustics. Is it published anywhere? I'd like to have a closer look. Actually, it is. You can find the article in last November's issue of Theater Sound. It's posted online. Great. I'll look it up. Oh—my train leaves in fourteen minutes. I have to get going. Safe travels, Camille!", textWithBlanks: "Rajesh, it was ____ to see you here in New York again this year. Same here. I look forward to ____ the Theater Technology ____ again next year. I really ____ your talk, especially the ____ you provided on ____. Is it ____ anywhere? I'd like to have a closer ____. Actually, it is. You can find the ____ in last November's ____ of Theater Sound. It's posted ____. Great. I'll look it up. Oh—my train ____ in fourteen minutes. I have to get ____. Safe ____, Camille!", missingWords: ["nice", "attending", "Conference", "enjoyed", "information", "acoustics", "published", "look", "article", "issue", "online", "leaves", "going", "travels"] };
const t5p3q65_67 = { id: 5365, title: "Test 5 - Part 3 - Q65-67", audioSrc: "", fullText: "Welcome to Orlando’s Deli. If you’d like to try one of our daily specials, they’re on the board behind me. Wow, that’s a great menu. The vegetable curry looks good. Is it spicy? No, it’s very mild—but we just sold out, unfortunately. In that case, I’ll have the lasagna. Great choice. By the way, we just opened our new patio this week in case you’d like to sit outside. Actually, it is a beautiful day. And your patio looks lovely.", textWithBlanks: "Welcome to Orlando’s Deli. If you’d like to ____ one of our daily ____, they’re on the ____ behind me. Wow, that’s a great ____. The ____ curry looks good. Is it ____? No, it’s very ____—but we just ____ out, unfortunately. In that ____, I’ll have the lasagna. Great ____. By the way, we just ____ our new ____ this week in case you’d like to sit ____. Actually, it is a ____ day. And your patio looks ____.", missingWords: ["try", "specials", "board", "menu", "vegetable", "spicy", "mild", "sold", "case", "choice", "opened", "patio", "outside", "beautiful", "lovely"] };
const t5p3q68_70 = { id: 5368, title: "Test 5 - Part 3 - Q68-70", audioSrc: "", fullText: "I’m excited about our hike today here at Marina Park. And I’m so glad we got to the park early before it gets crowded. Which trail should we hike? Let’s take a look at the map. We’re at the visitor center, and there’s a shuttle that stops at different trailheads. Right. It looks like the Creek Trail and the Pond Trail are fairly short. I’d like to do a more challenging hike. OK. How about the Waterfall Trail? That sounds good. And look—there’s a video about the park. We can watch while we wait.", textWithBlanks: "I’m ____ about our ____ today here at Marina Park. And I’m so ____ we got to the park ____ before it gets ____. Which trail should we hike? Let’s take a look at the ____. We’re at the ____ center, and there’s a ____ that stops at different ____. Right. It looks like the Creek Trail and the Pond Trail are fairly ____. I’d like to do a more ____ hike. OK. How about the Waterfall Trail? That ____ good. And look—there’s a ____ about the park. We can ____ while we wait.", missingWords: ["excited", "hike", "glad", "early", "crowded", "map", "visitor", "shuttle", "trailheads", "short", "challenging", "sounds", "video", "watch"] };

// TOEIC TEST 2 EXERCISES - PART 3
const t2p3q32_34 = { id: 2301, title: "Questions 32-34", audioSrc: "", fullText: "Good morning, captain. We'll be docking at the port in Kolkata this evening, right?\nActually, we had to change course overnight to avoid a storm, so we're running behind schedule. But we should arrive early tomorrow.\nWell, that's not too bad.\nOh, Hector has the day off today, so I'll need you to do the morning rounds-starting with checking the machinery in the engine room.\nOf course-I'll head there now.", textWithBlanks: "Good morning, ____. We'll be ____ at the port in Kolkata this ____, right?\nActually, we had to ____ course overnight to ____ a storm, so we're running ____ schedule. But we should ____ early tomorrow.\nWell, that's not too bad.\nOh, Hector has the day ____ today, so I'll need you to do the morning ____-starting with ____ the machinery in the ____ room.\nOf course-I'll ____ there now.", missingWords: ["captain", "docking", "evening", "change", "avoid", "behind", "arrive", "off", "rounds", "checking", "engine", "head"] };
const t2p3q35_37 = { id: 2302, title: "Questions 35-37", audioSrc: "", fullText: "Hi. I'm here to schedule some personal training sessions.\nOK. What are your fitness goals?\nI'd like to lift weights and build strength.\nI can work with you on that. Are you currently a member here?\nNo, I'll also need to sign up for a membership. I saw online that you're running a special for new members-fifty percent off the first month's membership. Can I sign up for that?\nAbsolutely. But before I get you signed up, let me show you around our facility.", textWithBlanks: "Hi. I'm here to ____ some ____ training sessions.\nOK. What are your ____ goals?\nI'd like to lift ____ and build ____.\nI can work with you on that. Are you ____ a member here?\nNo, I'll also need to ____ up for a ____. I saw online that you're running a ____ for new members-fifty ____ off the first month's membership. Can I sign up for that?\nAbsolutely. But before I get you signed up, let me ____ you around our ____.", missingWords: ["schedule", "personal", "fitness", "weights", "strength", "currently", "sign", "membership", "special", "percent", "show", "facility"] };
const t2p3q38_40 = { id: 2303, title: "Questions 38-40", audioSrc: "", fullText: "As you can see, this Renaissance landscape painting we acquired is in bad condition. We can't display it yet.\nHmm, yes. This painting will need significant restoration work.\nI'll begin by investigating the artist's color palette and style to see how we should repair the damaged areas.\nYou know, this would be a stunning piece to unveil at our anniversary dinner in June. And, since it's a big project to finish by then, we should get started right away.", textWithBlanks: "As you can see, this Renaissance ____ painting we ____ is in bad ____. We can't ____ it yet.\nHmm, yes. This painting will need ____ restoration work.\nI'll ____ by ____ the artist's color ____ and style to see how we should ____ the damaged areas.\nYou know, this would be a ____ piece to ____ at our ____ dinner in June. And, since it's a big project to ____ by then, we should get started right away.", missingWords: ["landscape", "acquired", "condition", "display", "significant", "begin", "investigating", "palette", "repair", "stunning", "unveil", "anniversary", "finish"] };
const t2p3q41_43 = { id: 2304, title: "Questions 41-43", audioSrc: "", fullText: "Hi, Ozan. Do you have time to review some slides I'm presenting at a meeting on Thursday?\nOh. Is that the meeting with Smith Incorporated?\nYes. I'm presenting them with our updated marketing plan for their chain of bookstores.\nYou know, Smith Incorporated prefers informal meetings. I think just a handout highlighting how our marketing plan will positively impact their book sales would be enough.\nReally? Thilo, you've worked with this client before. What do you think?\nOzan is right. I think they'd prefer a meeting that was more of a conversation than a presentation.", textWithBlanks: "Hi, Ozan. Do you have ____ to review some ____ I'm presenting at a meeting on Thursday?\nOh. Is that the meeting with Smith ____?\nYes. I'm presenting them with our ____ marketing plan for their ____ of bookstores.\nYou know, Smith Incorporated prefers ____ meetings. I think just a ____ highlighting how our marketing plan will ____ impact their book ____ would be enough.\nReally? Thilo, you've worked with this ____ before. What do you think?\nOzan is right. I think they'd ____ a meeting that was more of a ____ than a presentation.", missingWords: ["time", "slides", "Incorporated", "updated", "chain", "informal", "handout", "positively", "sales", "client", "prefer", "conversation"] };
const t2p3q44_46 = { id: 2305, title: "Questions 44-46", audioSrc: "", fullText: "I heard that the results of your experiment were better than you expected. Congratulations!\nThanks! I thought we'd have to run that reaction ten times before we got a positive result. But we got it on the third try.\nYou'll have to write up your results and submit them to the research director. That's Esra, right?\nOh, Esra's leaving the company next week.\nOh, I didn't know that. I wonder if you'll be promoted to fill her position.\nI don't think so. I've never managed an entire research group. I hope to get some experience doing that next quarter.", textWithBlanks: "I ____ that the results of your ____ were better than you ____. Congratulations!\nThanks! I thought we'd have to run that ____ ten times before we got a ____ result. But we got it on the third ____.\nYou'll have to ____ up your results and ____ them to the research director. That's Esra, right?\nOh, Esra's ____ the company next week.\nOh, I didn't know that. I wonder if you'll be ____ to fill her ____.\nI don't think so. I've never ____ an entire research group. I hope to get some ____ doing that next quarter.", missingWords: ["heard", "experiment", "expected", "reaction", "positive", "try", "write", "submit", "leaving", "promoted", "position", "managed", "experience"] };
const t2p3q47_49 = { id: 2306, title: "Questions 47-49", audioSrc: "", fullText: "Now we'll move on to a special segment of our news program where we highlight new local businesses for our viewers. Today I'm talking with Dhruv Bajaj-a personal trainer and gym owner. Thanks for coming into the studio today, Dhruv!\nThanks for having me! I'm excited to tell you about the gym I just opened last month. It has state-of-the-art equipment, and my trainers can work with clients at any stage in their fitness journey.\nSounds great. How did you get started in this line of work?\nWell, I was an athlete in school, and when I stopped competing, I wanted to continue doing something fitness-related. So I started working as a trainer.", textWithBlanks: "Now we'll move on to a ____ segment of our news program where we ____ new ____ businesses for our viewers. Today I'm talking with Dhruv Bajaj-a personal ____ and gym ____. Thanks for coming into the ____ today, Dhruv!\nThanks for having me! I'm ____ to tell you about the gym I just ____ last month. It has state-of-the-art ____, and my trainers can work with clients at any ____ in their fitness ____.\nSounds great. How did you get started in this line of work?\nWell, I was an ____ in school, and when I ____ competing, I wanted to ____ doing something fitness-related. So I started working as a trainer.", missingWords: ["special", "highlight", "local", "trainer", "owner", "studio", "excited", "opened", "equipment", "stage", "journey", "athlete", "stopped", "continue"] };
const t2p3q50_52 = { id: 2307, title: "Questions 50-52", audioSrc: "", fullText: "As director, I'm delighted to welcome you to the Redmond Aquatic Institute. We're happy you'll be producing content for our Web site.\nI'm looking forward to writing about Redmond's initiatives in marine biology.\nYes, the more articles the public can read about threats to aquatic ecosystems, the better. Public awareness will help us get funding to meet our aim of preserving these ecosystems. This is Roberto. He's working on our mangrove research project, which is the first one you'll cover.\nIt's an interesting project. And what's exciting is that we've started using drones to photograph the area with the mangroves. So we have some great images you could use.", textWithBlanks: "As director, I'm ____ to welcome you to the Redmond Aquatic ____. We're ____ you'll be ____ content for our Web site.\nI'm looking forward to ____ about Redmond's ____ in marine biology.\nYes, the more articles the ____ can read about ____ to aquatic ____, the better. Public ____ will help us get ____ to meet our aim of ____ these ecosystems. This is Roberto. He's working on our mangrove ____ project, which is the first one you'll cover.\nIt's an ____ project. And what's exciting is that we've started using ____ to ____ the area with the mangroves. So we have some great ____ you could use.", missingWords: ["delighted", "Institute", "happy", "producing", "writing", "initiatives", "public", "threats", "ecosystems", "awareness", "funding", "preserving", "research", "interesting", "drones", "photograph", "images"] };
const t2p3q53_55 = { id: 2308, title: "Questions 53-55", audioSrc: "", fullText: "Matthew, you're not planning to cancel Wednesday's budget meeting, are you?\nI haven't sent out the cancellation yet, but our research partners in China are off this week for a national holiday, so there's no point in meeting. Why?\nWell, I've been looking at the draft budget, and we didn't allocate funds for a project leader.\nUh-oh. I wonder how that happened. You're right. We need to discuss how to fix that.\nYou know, we allocated money for a trip to Singapore to present our preliminary findings. We don't really need to do that.", textWithBlanks: "Matthew, you're not ____ to cancel Wednesday's ____ meeting, are you?\nI haven't sent out the ____ yet, but our research ____ in China are off this week for a national ____, so there's no point in meeting. Why?\nWell, I've been looking at the ____ budget, and we didn't ____ funds for a project ____.\nUh-oh. I wonder how that ____. You're right. We need to ____ how to fix that.\nYou know, we allocated money for a trip to Singapore to ____ our ____ findings. We don't really need to do that.", missingWords: ["planning", "budget", "cancellation", "partners", "holiday", "draft", "allocate", "leader", "happened", "discuss", "present", "preliminary"] };
const t2p3q56_58 = { id: 2309, title: "Questions 56-58", audioSrc: "", fullText: "Hello, you've reached tech support.\nI'm calling from Rubin Restaurant Equipment. I recently purchased your software to keep track of my warehouse inventory, and I have a question about setting alerts.\nSure. How can I help?\nWell, we've been getting an alert whenever the inventory for our deep fryers drops below ten. But we usually don't stock many of those because restaurants don't often need to replace them. So, can I lower the alert level for just those items?\nYes. In the system, if you click on that product, you'll see a link that says, \"Set Custom Alert.\" And you can set it to any number from there.\nI see it. Thanks for your help.", textWithBlanks: "Hello, you've reached tech ____.\nI'm calling from Rubin Restaurant Equipment. I recently ____ your ____ to keep track of my warehouse ____, and I have a question about ____ alerts.\nSure. How can I help?\nWell, we've been getting an ____ whenever the inventory for our deep ____ drops below ten. But we usually don't ____ many of those because restaurants don't often need to ____ them. So, can I ____ the alert level for just those items?\nYes. In the ____, if you click on that product, you'll see a link that says, \"Set ____ Alert.\" And you can set it to any number from there.\nI see it. Thanks for your help.", missingWords: ["support", "purchased", "software", "inventory", "setting", "alert", "fryers", "stock", "replace", "lower", "system", "Custom"] };
const t2p3q59_61 = { id: 2310, title: "Questions 59-61", audioSrc: "", fullText: "I just spoke to the garden director. He wants us to install an irrigation system in the rose garden as well as the magnolia grove. He wants to be sure the flowers get plenty of water during the hot summer months.\nOK, let's walk over there now and take some measurements. Then we can figure out what materials we'll need.\nSure. We have some extra parts left over from when we worked on the cherry trees. I'll check what we have left after we finish measuring the rose garden.", textWithBlanks: "I just ____ to the garden director. He wants us to ____ an irrigation ____ in the rose garden as well as the magnolia ____. He wants to be ____ the flowers get ____ of water during the hot summer months.\nOK, let's walk over there now and take some ____. Then we can ____ out what ____ we'll need.\nSure. We have some ____ parts left over from when we worked on the cherry trees. I'll ____ what we have left after we ____ measuring the rose garden.", missingWords: ["spoke", "install", "system", "grove", "sure", "plenty", "measurements", "figure", "materials", "extra", "check", "finish"] };
const t2p3q62_64 = { id: 2311, title: "Questions 62-64", audioSrc: "", fullText: "Good morning, Ms. Aljohani. Sorry I'm a little late. Traffic was terrible.\nThat's OK, but our rental office will be very busy this morning. There's a big education convention in town starting today, and a lot of attendees from out of town have reserved cars to get to the conference center.\nRight. What do you want me to do first?\nI'd like you to start by checking the batteries in our electric cars. We want to be sure they're all fully charged.", textWithBlanks: "Good morning, Ms. Aljohani. Sorry I'm a little ____. Traffic was ____.\nThat's OK, but our ____ office will be very ____ this morning. There's a big education ____ in town starting today, and a lot of ____ from out of town have ____ cars to get to the ____ center.\nRight. What do you want me to do first?\nI'd like you to start by ____ the ____ in our electric cars. We want to be sure they're all fully ____.", missingWords: ["late", "terrible", "rental", "busy", "convention", "attendees", "reserved", "conference", "checking", "batteries", "charged"] };
const t2p3q65_67 = { id: 2312, title: "Questions 65-67", audioSrc: "", fullText: "I've been on vacation, so I missed our department's meeting. Can you give me an update?\nWell, all our public programs and community events are on schedule.\nGreat! How about the Jannis Park project? We're still planning on planting trees best suited for residential areas, right?\nThat's right. I'm working on the public education part now. There'll be a children's poster competition next month, which the city mayor will judge.\nInteresting. Is there a prize?\nThe winner will get a ribbon. But all participants will get a seedling to plant at home. We'll be giving away the tallest of these four varieties, since it was the most popular in a survey of our residents.", textWithBlanks: "I've been on ____, so I ____ our department's meeting. Can you give me an ____?\nWell, all our public ____ and community events are on ____.\nGreat! How about the Jannis Park project? We're still ____ on planting trees best ____ for residential areas, right?\nThat's right. I'm working on the public ____ part now. There'll be a children's poster ____ next month, which the city ____ will judge.\nInteresting. Is there a ____?\nThe winner will get a ____. But all ____ will get a ____ to plant at home. We'll be giving away the ____ of these four ____, since it was the most ____ in a survey of our residents.", missingWords: ["vacation", "missed", "update", "programs", "schedule", "planning", "suited", "education", "competition", "mayor", "prize", "ribbon", "participants", "seedling", "tallest", "varieties", "popular"] };
const t2p3q68_70 = { id: 2313, title: "Questions 68-70", audioSrc: "", fullText: "Hi, I'd like a large black coffee and an egg-and-cheese croissant, please.\nSure. That'll be eight dollars. Are you a Shelby's preferred customer?\nUh, no I'm not. But I do have an EZ-Cash card.\nGreat. Let me ring that up for you.\nBy the way, I'd like to order breakfast for my team tomorrow morning. Can I place that order ahead of time?\nSure. Would you like to do that now?\nNo, I'll call you later today when I know what everyone wants. Thanks for the information.", textWithBlanks: "Hi, I'd like a ____ black coffee and an egg-and-cheese ____, please.\nSure. That'll be eight ____. Are you a Shelby's ____ customer?\nUh, no I'm not. But I do have an EZ-Cash card.\nGreat. Let me ____ that up for you.\nBy the way, I'd like to order ____ for my team tomorrow morning. Can I ____ that order ____ of time?\nSure. Would you like to do that now?\nNo, I'll call you ____ today when I know what everyone wants. Thanks for the ____.", missingWords: ["large", "croissant", "dollars", "preferred", "ring", "breakfast", "place", "ahead", "later", "information"] };

// FIX: Define variables for Test 3 by copying from Test 2, and update IDs. This will fix the 'Cannot find name' errors.
// TOEIC TEST 3 EXERCISES - PART 3
const t3p3q32_34 = { ...t2p3q32_34, id: 3301 };
const t3p3q35_37 = { ...t2p3q35_37, id: 3302 };
const t3p3q38_40 = { ...t2p3q38_40, id: 3303 };
const t3p3q41_43 = { ...t2p3q41_43, id: 3304 };
const t3p3q44_46 = { ...t2p3q44_46, id: 3305 };
const t3p3q47_49 = { ...t2p3q47_49, id: 3306 };
const t3p3q50_52 = { ...t2p3q50_52, id: 3307 };
const t3p3q53_55 = { ...t2p3q53_55, id: 3308 };
const t3p3q56_58 = { ...t2p3q56_58, id: 3309 };
const t3p3q59_61 = { ...t2p3q59_61, id: 3310 };
const t3p3q62_64 = { ...t2p3q62_64, id: 3311 };
const t3p3q65_67 = { ...t2p3q65_67, id: 3312 };
const t3p3q68_70 = { ...t2p3q68_70, id: 3313 };

// FIX: Define variables for Test 4 by copying from Test 5, and update IDs. This will fix the 'Cannot find name' errors.
// TOEIC TEST 4 EXERCISES - PART 3
const t4p3q32_34 = { ...t5p3q32_34, id: 4332 };
const t4p3q35_37 = { ...t5p3q35_37, id: 4335 };
const t4p3q38_40 = { ...t5p3q38_40, id: 4338 };
const t4p3q41_43 = { ...t5p3q41_43, id: 4341 };
const t4p3q44_46 = { ...t5p3q44_46, id: 4344 };
const t4p3q47_49 = { ...t5p3q47_49, id: 4347 };
const t4p3q50_52 = { ...t5p3q50_52, id: 4350 };
const t4p3q53_55 = { ...t5p3q53_55, id: 4353 };
const t4p3q56_58 = { ...t5p3q56_58, id: 4356 };
const t4p3q59_61 = { ...t5p3q59_61, id: 4359 };
const t4p3q62_64 = { ...t5p3q62_64, id: 4362 };
const t4p3q65_67 = { ...t5p3q65_67, id: 4365 };
const t4p3q68_70 = { ...t5p3q68_70, id: 4368 };


// BASE EXERCISES - PART 3
const language = {
    id: 4,
    title: "Learning a New Language",
    audioSrc: "",
    fullText: "Learning a new language opens up a world of opportunities. It allows you to connect with different cultures and people. Consistency is crucial; practicing a little every day is more effective than one long session per week. Don't be afraid to make mistakes, as they are an essential part of the learning process.",
    textWithBlanks: "____ a new language ____ up a world of ____. It allows you to ____ with different ____ and people. ____ is ____; practicing a little every day is more ____ than one long session per week. Don't be ____ to make ____, as they are an ____ part of the learning ____.",
    missingWords: ["Learning", "opens", "opportunities", "connect", "cultures", "Consistency", "crucial", "effective", "afraid", "mistakes", "essential", "process"],
};

export const dictationPart3Data: DictationPart = {
    id: 3,
    title: "Part 3: Short Conversations",
    description: "Listen to short conversations between two or three people and answer questions.",
    tests: [
        { id: 1, title: "Test 1", exercises: [language] },
        { id: 2, title: "Test 2", exercises: [
            t2p3q32_34, t2p3q35_37, t2p3q38_40, t2p3q41_43, t2p3q44_46, t2p3q47_49, t2p3q50_52,
            t2p3q53_55, t2p3q56_58, t2p3q59_61, t2p3q62_64, t2p3q65_67, t2p3q68_70
        ] },
        { id: 3, title: "Test 3", exercises: [
            t3p3q32_34, t3p3q35_37, t3p3q38_40, t3p3q41_43, t3p3q44_46, t3p3q47_49, t3p3q50_52,
            t3p3q53_55, t3p3q56_58, t3p3q59_61, t3p3q62_64, t3p3q65_67, t3p3q68_70
        ] },
        { id: 4, title: "Test 4", exercises: [
            t4p3q32_34, t4p3q35_37, t4p3q38_40, t4p3q41_43, t4p3q44_46, t4p3q47_49, t4p3q50_52,
            t4p3q53_55, t4p3q56_58, t4p3q59_61, t4p3q62_64, t4p3q65_67, t4p3q68_70
        ] },
        { id: 5, title: "Test 5", exercises: [t5p3q32_34, t5p3q35_37, t5p3q38_40, t5p3q41_43, t5p3q44_46, t5p3q47_49, t5p3q50_52, t5p3q53_55, t5p3q56_58, t5p3q59_61, t5p3q62_64, t5p3q65_67, t5p3q68_70] },
        { id: 6, title: "Test 6", exercises: [
            t2p3q32_34, t2p3q35_37, t2p3q38_40, t2p3q41_43, t2p3q44_46, t2p3q47_49, t2p3q50_52, 
            t2p3q53_55, t2p3q56_58, t2p3q59_61, t2p3q62_64, t2p3q65_67, t2p3q68_70
        ] },
        { id: 7, title: "Test 7", exercises: [
            t3p3q32_34, t3p3q35_37, t3p3q38_40, t3p3q41_43, t3p3q44_46, t3p3q47_49, t3p3q50_52,
            t3p3q53_55, t3p3q56_58, t3p3q59_61, t3p3q62_64, t3p3q65_67, t3p3q68_70
        ] },
        { id: 8, title: "Test 8", exercises: [
            t2p3q32_34, t2p3q35_37, t2p3q38_40, t2p3q41_43, t2p3q44_46, t2p3q47_49, t2p3q50_52, 
            t2p3q53_55, t2p3q56_58, t2p3q59_61, t2p3q62_64, t2p3q65_67, t2p3q68_70
        ] },
    ]
};
