import { DictationPart } from '../types';

// TOEIC TEST 5 EXERCISES - PART 4
const t5p4q71_73 = { id: 5471, title: "Test 5 - Part 4 - Q71-73", audioSrc: "", fullText: "Hi, Ms. Cho. I'm calling from Springdale Lights. Yesterday, you ordered 24 of our purple solar lanterns for your upcoming event. Unfortunately, our supplier won't be able to get us purple lanterns for another three weeks, so we only have yellow ones in stock. We would like to offer you a ten percent discount on them to apologize for this. Please call us back to confirm whether you'd like the yellow solar lights, and we'll set them aside for you.", textWithBlanks: "Hi, Ms. Cho. I'm ____ from Springdale Lights. ____, you ____ 24 of our purple solar ____ for your ____ event. ____, our ____ won't be able to get us purple lanterns for another three weeks, so we only have yellow ones in ____. We would like to ____ you a ten percent ____ on them to ____ for this. Please call us back to ____ whether you'd like the yellow solar lights, and we'll set them ____ for you.", missingWords: ["calling", "Yesterday", "ordered", "lanterns", "upcoming", "Unfortunately", "supplier", "stock", "offer", "discount", "apologize", "confirm", "aside"] };
const t5p4q74_76 = { id: 5474, title: "Test 5 - Part 4 - Q74-76", audioSrc: "", fullText: "Welcome to Osterwind Estate. The former owner, Ms. Yuping Wei, was a famous painter. What's special about this estate is that Ms. Wei designed it herself, including the landscaping. We're asking volunteers to clear debris from the walkways around the gardens in preparation for the estate's first season as a public park. You can pick up a bag and gloves from the patio area. And remember, be sure to see me as you check out before you leave. All volunteers are eligible for a complimentary visitor pass that you can use to access the estate and attend any events held here all summer long.", textWithBlanks: "Welcome to Osterwind Estate. The ____ owner, Ms. Yuping Wei, was a ____ painter. What's ____ about this estate is that Ms. Wei ____ it herself, including the ____. We're asking ____ to clear ____ from the walkways around the gardens in ____ for the estate's first season as a ____ park. You can pick up a bag and ____ from the patio area. And remember, be sure to see me as you ____ out before you leave. All volunteers are ____ for a ____ visitor pass that you can use to ____ the estate and ____ any events held here all summer long.", missingWords: ["former", "famous", "special", "designed", "landscaping", "volunteers", "debris", "preparation", "public", "gloves", "check", "eligible", "complimentary", "access", "attend"] };
const t5p4q77_79 = { id: 5477, title: "Test 5 - Part 4 - Q77-79", audioSrc: "", fullText: "Good morning, Ms. Espinosa. This is Marcel Fournier. It’s Saturday morning, and I’m on my way to the airport. This is a little out of the ordinary, but I’m calling because in my haste I left a note with Mr. Hang’s mobile phone number on my office desk. He’s picking me up from the airport, and I’ll be stuck if I can’t reach him. I’ll need you to go into the office and text me with the number. I know this is inconvenient. I’ll check my messages once I land in San Diego.", textWithBlanks: "Good morning, Ms. Espinosa. This is Marcel Fournier. It’s Saturday morning, and I’m on my way to the ____. This is a little out of the ____, but I’m calling because in my ____ I left a note with Mr. Hang’s ____ phone number on my office ____. He’s ____ me up from the airport, and I’ll be ____ if I can’t ____ him. I’ll need you to go into the office and ____ me with the number. I know this is ____. I’ll check my ____ once I ____ in San Diego.", missingWords: ["airport", "ordinary", "haste", "mobile", "desk", "picking", "stuck", "reach", "text", "inconvenient", "messages", "land"] };
const t5p4q80_82 = { id: 5480, title: "Test 5 - Part 4 - Q80-82", audioSrc: "", fullText: "Hi, everyone! Thanks for watching today. If you’re new to my channel, you should know that my videos focus on ways that we can repurpose common objects so that they don’t end up in landfills. In this video, you’ll learn how to make candles from old and leftover crayons. Your first step is to collect the items you’ll need. You may already have some old crayons around the house, or you can ask your friends and neighbors for theirs. I’ll be covering a lot of steps, but don’t worry, a full written version of the instructions is available on my Web site. I recommend downloading those later for future reference.", textWithBlanks: "Hi, everyone! Thanks for ____ today. If you’re new to my ____, you should know that my videos ____ on ways that we can ____ common objects so that they don’t end up in ____. In this video, you’ll ____ how to make ____ from old and ____ crayons. Your first ____ is to ____ the items you’ll need. You may already have some old crayons around the house, or you can ask your friends and ____ for theirs. I’ll be ____ a lot of steps, but don’t worry, a full ____ version of the ____ is ____ on my Web site. I recommend ____ those later for future ____.", missingWords: ["watching", "channel", "focus", "repurpose", "landfills", "learn", "candles", "leftover", "step", "collect", "neighbors", "covering", "written", "instructions", "available", "downloading", "reference"] };
const t5p4q83_85 = { id: 5483, title: "Test 5 - Part 4 - Q83-85", audioSrc: "", fullText: "Thank you all for coming to this press conference. As you know, the Grand Falls Bridge improvement work has been underway for almost a year. We're nearing the final stage of sanding and painting the newly built portions. I know the fishing community has expressed concern over the potential environmental impact of this project on our local marine life. Well, all required studies were conducted a year ago. I'll take some questions now. After that, our special-events coordinator will discuss the bridge-opening ceremony that's being planned.", textWithBlanks: "Thank you all for ____ to this press ____. As you know, the Grand Falls Bridge ____ work has been ____ for almost a year. We're ____ the final ____ of sanding and painting the newly built ____. I know the fishing ____ has expressed ____ over the ____ environmental ____ of this project on our local ____ life. Well, all ____ studies were ____ a year ago. I'll take some questions now. After that, our special-events ____ will discuss the bridge-opening ____ that's being ____.", missingWords: ["coming", "conference", "improvement", "underway", "nearing", "stage", "portions", "community", "concern", "potential", "impact", "marine", "required", "conducted", "coordinator", "ceremony", "planned"] };
const t5p4q86_88 = { id: 5486, title: "Test 5 - Part 4 - Q86-88", audioSrc: "", fullText: "Hello, Mr. Smith. I hope you're getting settled into your office space in our building. I'm calling about some large packages that arrived for your company last week. We're keeping them for you in the storage room downstairs. The lease agreement says management will hold packages for five days. It's been ten days. Please give me a call and let me know when you can come down to claim them so I can be there to open the storage room door for you.", textWithBlanks: "Hello, Mr. Smith. I hope you're getting ____ into your office ____ in our building. I'm ____ about some large ____ that ____ for your company last week. We're ____ them for you in the ____ room downstairs. The ____ agreement says ____ will hold packages for five days. It's been ten days. Please give me a call and let me know when you can come down to ____ them so I can be there to ____ the storage room door for you.", missingWords: ["settled", "space", "calling", "packages", "arrived", "keeping", "storage", "lease", "management", "claim", "open"] };
const t5p4q89_91 = { id: 5489, title: "Test 5 - Part 4 - Q89-91", audioSrc: "", fullText: "Our next story concerns Ferndale Valley. It's well-known that the area is one of the windiest locations in the region, and one company would like to take advantage of that natural energy source. Breeze Capture hopes to install dozens of wind turbines by the end of next year. The company is looking for local farmers who are interested in leasing some of their land for the project. In addition to being paid for the land use, participants will also be compensated for the energy that is generated by the turbines. For more information, e-mail info@breezecapture.com.", textWithBlanks: "Our next story ____ Ferndale Valley. It's well-known that the area is one of the ____ locations in the ____, and one company would like to take ____ of that ____ energy ____. Breeze Capture hopes to ____ dozens of wind ____ by the end of next year. The company is looking for local ____ who are ____ in ____ some of their land for the project. In ____ to being paid for the land use, ____ will also be ____ for the energy that is ____ by the turbines. For more ____, e-mail info@breezecapture.com.", missingWords: ["concerns", "windiest", "region", "advantage", "natural", "source", "install", "turbines", "farmers", "interested", "leasing", "addition", "participants", "compensated", "generated", "information"] };
const t5p4q92_94 = { id: 5492, title: "Test 5 - Part 4 - Q92-94", audioSrc: "", fullText: "Hello, Mr. Kimura. I'm calling from Feras Portable Storage. You recently ordered a container to store and move your household belongings in. I'm calling to confirm that your container will be delivered tomorrow morning at nine o'clock. The driver will place it in your driveway. After the delivery, if you could, please complete the customer feedback survey that we'll e-mail you. It will help us to improve our service. Thanks.", textWithBlanks: "Hello, Mr. Kimura. I'm calling from Feras ____ Storage. You recently ____ a ____ to store and move your household ____ in. I'm calling to ____ that your container will be ____ tomorrow morning at nine o'clock. The ____ will place it in your ____. After the delivery, if you could, please ____ the customer ____ survey that we'll e-mail you. It will help us to ____ our service. Thanks.", missingWords: ["Portable", "ordered", "container", "belongings", "confirm", "delivered", "driver", "driveway", "complete", "feedback", "improve"] };
const t5p4q95_97 = { id: 5495, title: "Test 5 - Part 4 - Q95-97", audioSrc: "", fullText: "This is the custodial staff's cabinet for cleaning supplies. As part of your training, you'll be expected to learn which cleaning solutions are used for different surfaces in the hotel, such as carpet and tile flooring. The spray bottle on the top shelf, Baxlon, is for glass surfaces. The product directly under the spray bottle is brand new. It was just released this month, and it's excellent for polishing furniture. Oh, and every Tuesday at one o'clock, a delivery truck brings any supplies that we're low on. Don't forget to check that.", textWithBlanks: "This is the ____ staff's ____ for cleaning ____. As part of your ____, you'll be ____ to learn which cleaning ____ are used for ____ surfaces in the hotel, such as ____ and tile flooring. The spray ____ on the top shelf, Baxlon, is for glass surfaces. The ____ directly under the spray bottle is brand new. It was just ____ this month, and it's ____ for ____ furniture. Oh, and every Tuesday at one o'clock, a ____ truck brings any supplies that we're ____ on. Don't forget to check that.", missingWords: ["custodial", "cabinet", "supplies", "training", "expected", "solutions", "different", "carpet", "bottle", "product", "released", "excellent", "polishing", "delivery", "low"] };
const t5p4q98_100 = { id: 5498, title: "Test 5 - Part 4 - Q98-100", audioSrc: "", fullText: "Welcome back to this professional development workshop. We'll continue from where we left off in our discussion on advertising through social media using videos, and we'll end today's meeting by performing a group task. Last week, we discussed the planning phase for a video marketing campaign. Today, we'll move on to the production phase. During this phase, you'll need to ensure that high-quality equipment is used for lighting and camera work and that you have the best video editors you can get for the job. We're very lucky to have an expert here today to talk about her experience with the process. Please give your attention to Usha Madan.", textWithBlanks: "Welcome back to this ____ development ____. We'll ____ from where we left off in our ____ on ____ through social media using videos, and we'll end today's meeting by ____ a group task. Last week, we ____ the ____ phase for a video marketing campaign. Today, we'll move on to the ____ phase. During this phase, you'll need to ____ that high-quality ____ is used for ____ and camera work and that you have the best video ____ you can get for the job. We're very ____ to have an ____ here today to talk about her ____ with the process. Please give your ____ to Usha Madan.", missingWords: ["professional", "workshop", "continue", "discussion", "advertising", "performing", "discussed", "planning", "production", "ensure", "equipment", "lighting", "editors", "lucky", "expert", "experience", "attention"] };

// TOEIC TEST 2 EXERCISES - PART 4
const t2p4q71_73 = { id: 2401, title: "Questions 71-73", audioSrc: "", fullText: "Hi, Amina. This is Sabine calling from Blue Drop Creations. I just put the earrings and necklaces that you ordered from me in the mail. Because you've been a customer for over ten years, I've also included a special gift in the package for you. It's a case for your jewelry. This is a new product that I'm starting to offer, so please call me back after you receive it. I'd really like to hear your thoughts on it.", textWithBlanks: "Hi, Amina. This is Sabine ____ from Blue Drop Creations. I just put the ____ and ____ that you ordered from me in the ____. Because you've been a ____ for over ten years, I've also ____ a special ____ in the package for you. It's a ____ for your jewelry. This is a new ____ that I'm starting to offer, so please call me back after you ____ it. I'd really like to hear your ____ on it.", missingWords: ["calling", "earrings", "necklaces", "mail", "customer", "included", "gift", "case", "product", "receive", "thoughts"] };
const t2p4q74_76 = { id: 2402, title: "Questions 74-76", audioSrc: "", fullText: "Good morning, this is Brandon from Dakota Framing Company, returning your call. We received your voicemail about wanting to frame a wedding picture. There is no need to print the photo yourself. We prefer that you e-mail us a digital copy. So, to answer your question, you can complete the whole order online. Just visit our Web site, where you'll fill in your choices for photo size and the frame and upload your photo. And for a small extra cost, we'll guarantee to replace your frame in case of damage. Please be sure to check that box when you order.", textWithBlanks: "Good morning, this is Brandon from Dakota Framing Company, ____ your call. We ____ your voicemail about ____ to frame a ____ picture. There is no need to ____ the photo yourself. We ____ that you e-mail us a ____ copy. So, to answer your question, you can ____ the whole order online. Just ____ our Web site, where you'll fill in your ____ for photo size and the frame and ____ your photo. And for a small extra ____, we'll ____ to replace your frame in case of ____. Please be sure to check that box when you order.", missingWords: ["returning", "received", "wanting", "wedding", "print", "prefer", "digital", "complete", "visit", "choices", "upload", "cost", "guarantee", "damage"] };
const t2p4q77_79 = { id: 2403, title: "Questions 77-79", audioSrc: "", fullText: "Welcome all to this week's training in our series of patient care programs. Our physical therapy center is known for the excellent care we provide to our patients, and that's because of you, our staff. The training today will be about ways to engage the patients who reside in our facility through playing games. I've prepared different types of activities for us to try out, including some games that involve mental stimulation as well as physical exercises. But, I have to let you know that today I must leave at noon. Next week we'll try out more of the games.", textWithBlanks: "Welcome all to this week's ____ in our series of ____ care programs. Our physical ____ center is known for the ____ care we ____ to our patients, and that's because of you, our staff. The training today will be about ways to ____ the patients who ____ in our facility through ____ games. I've ____ different types of ____ for us to try out, including some games that involve ____ stimulation as well as physical ____. But, I have to let you know that today I must ____ at noon. Next week we'll try out more of the games.", missingWords: ["training", "patient", "therapy", "excellent", "provide", "engage", "reside", "playing", "prepared", "activities", "mental", "exercises", "leave"] };
const t2p4q80_82 = { id: 2404, title: "Questions 80-82", audioSrc: "", fullText: "Are you a certified commercial truck driver? Hoffman Oversized Haulers is currently looking for experienced truck drivers to join our team. As our name suggests, we transport oversized cargo throughout the region. With Hoffman, drivers enjoy flexible scheduling. In fact, we're the only company in the region that allows employees to determine their own work hours. If you don't have experience working with oversized loads, training is available. Please check out our Web site to learn more about our open positions. We can't wait to work with you.", textWithBlanks: "Are you a ____ commercial truck driver? Hoffman Oversized Haulers is ____ looking for ____ truck drivers to join our team. As our name ____, we transport ____ cargo throughout the ____. With Hoffman, drivers enjoy ____ scheduling. In fact, we're the only company in the region that ____ employees to ____ their own work hours. If you don't have ____ working with oversized loads, training is ____. Please check out our Web site to learn more about our open ____. We can't wait to work with you.", missingWords: ["certified", "currently", "experienced", "suggests", "oversized", "region", "flexible", "allows", "determine", "experience", "available", "positions"] };
const t2p4q83_85 = { id: 2405, title: "Questions 83-85", audioSrc: "", fullText: "Hi, Jinyu. I have some exciting news! The Farmer's Table television program wants to feature our restaurant in an upcoming episode. They'll be coming on Wednesday to film everyone at work in the kitchen during our dinner service. Since you're the executive chef, I'll need you to come in earlier than usual to get everything prepped and set up. And just as a reminder, I'm still planning to be out of town next week for the Springdale Pastry and Dessert Festival. Thanks!", textWithBlanks: "Hi, Jinyu. I have some ____ news! The Farmer's Table ____ program wants to ____ our restaurant in an ____ episode. They'll be coming on ____ to film everyone at work in the kitchen during our ____ service. Since you're the ____ chef, I'll need you to come in ____ than usual to get everything ____ and set up. And just as a ____, I'm still ____ to be out of town next week for the Springdale Pastry and Dessert Festival. Thanks!", missingWords: ["exciting", "television", "feature", "upcoming", "Wednesday", "dinner", "executive", "earlier", "prepped", "reminder", "planning"] };
const t2p4q86_88 = { id: 2406, title: "Questions 86-88", audioSrc: "", fullText: "Good evening and thank you for watching Channel Four News. I'm here in Rockville, a suburb in the metropolitan area. Rockville was recently chosen as the site of a multimillion-dollar electric vehicle battery factory. This project promises to bring thousands of jobs, both directly and indirectly, to the surrounding community. At a recent well-attended public comment meeting, residents had a chance to voice any opposition to the project. No one made any comments. To learn more about this exciting development, artist-rendered images of the project are on display at the city hall building.", textWithBlanks: "Good evening and thank you for ____ Channel Four News. I'm here in Rockville, a ____ in the metropolitan ____. Rockville was recently ____ as the site of a multimillion-dollar electric vehicle ____ factory. This project ____ to bring thousands of jobs, both ____ and indirectly, to the ____ community. At a recent well-attended public ____ meeting, residents had a ____ to voice any ____ to the project. No one made any comments. To learn more about this ____ development, artist-____ images of the project are on ____ at the city hall building.", missingWords: ["watching", "suburb", "area", "chosen", "battery", "promises", "directly", "surrounding", "comment", "chance", "opposition", "exciting", "rendered", "display"] };
const t2p4q89_91 = { id: 2407, title: "Questions 89-91", audioSrc: "", fullText: "Tired of losing things on your desk because it's too cluttered? If so, the Optimum Space Organizer is the perfect product for you. Designed with office employees like you in mind, this product can make even the messiest of desks look neat again. Best of all, the organizer adjusts to any sized space you may have on your desk. It can be as narrow or as wide as you need it to be-within seconds! If you call in the next ten minutes, you'll receive a 30 percent discount!", textWithBlanks: "Tired of ____ things on your desk because it's too ____? If so, the Optimum Space ____ is the ____ product for you. ____ with office employees like you in mind, this product can make even the ____ of desks look ____ again. Best of all, the organizer ____ to any ____ space you may have on your desk. It can be as ____ or as wide as you need it to be-within ____! If you call in the next ten minutes, you'll ____ a 30 percent ____!", missingWords: ["losing", "cluttered", "Organizer", "perfect", "Designed", "messiest", "neat", "adjusts", "sized", "narrow", "seconds", "receive", "discount"] };
const t2p4q92_94 = { id: 2408, title: "Questions 92-94", audioSrc: "", fullText: "Thanks for listening to this episode of Fabulous Foods. Every week, we discuss a different vegetable and ways to cook with it to maximize flavor. Now, before we get started, I'm excited to announce that I've been collaborating with Cartwell Kitchen Supplies to develop a new line of cookware. It'll be released in November, but it's available for preorder right now. Keep in mind, this product line will not be available for long. OK, let's move on to our program. With us today is renowned chef Rebecca Murray to talk about this week's vegetable: eggplant! Rebecca recently launched a vegetarian restaurant in New York that is getting rave reviews so far.", textWithBlanks: "Thanks for ____ to this ____ of Fabulous Foods. Every week, we ____ a different ____ and ways to cook with it to ____ flavor. Now, before we get started, I'm ____ to announce that I've been ____ with Cartwell Kitchen Supplies to ____ a new line of cookware. It'll be ____ in November, but it's ____ for preorder right now. Keep in ____, this product line will not be available for long. OK, let's move on to our program. With us today is ____ chef Rebecca Murray to talk about this week's vegetable: eggplant! Rebecca recently ____ a ____ restaurant in New York that is getting ____ reviews so far.", missingWords: ["listening", "episode", "discuss", "vegetable", "maximize", "excited", "collaborating", "develop", "released", "available", "mind", "renowned", "launched", "vegetarian", "rave"] };
const t2p4q95_97 = { id: 2409, title: "Questions 95-97", audioSrc: "", fullText: "Attention passengers. Renovation work to upgrade and modernize our train station is underway. We apologize for the inconvenience the construction noise may cause. Please note that regional train schedules are not affected. Train 133 with service to Washington, D.C., will be arriving shortly. All passengers to Washington, please proceed to Track 26B. If you need assistance handling your baggage, please speak to a ticket agent immediately. Train 133's next stop will be Wilmington, followed by Baltimore and then Washington, D.C.", textWithBlanks: "Attention passengers. ____ work to ____ and ____ our train station is ____. We ____ for the ____ the construction ____ may cause. Please note that ____ train schedules are not ____. Train 133 with service to Washington, D.C., will be ____ shortly. All passengers to Washington, please ____ to Track 26B. If you need ____ handling your ____, please speak to a ticket ____ immediately. Train 133's next stop will be Wilmington, ____ by Baltimore and then Washington, D.C.", missingWords: ["Renovation", "upgrade", "modernize", "underway", "apologize", "inconvenience", "noise", "regional", "affected", "arriving", "proceed", "assistance", "baggage", "agent", "followed"] };
const t2p4q98_100 = { id: 2410, title: "Questions 98-100", audioSrc: "", fullText: "Hello, everyone. I'm Carmen Salazar, the airport operations director, and I wanted to thank you for attending this press conference. As of this week, construction on the new regional airport is proceeding on schedule for two of the three terminals. Minor design adjustments to terminal A have put the project slightly behind schedule, and we anticipate about two months will be added to the construction time frame as a result. I'd also like to mention that we now have a 3-D printed model of this project! Please feel free to visit our Web site so you can view it.", textWithBlanks: "Hello, everyone. I'm Carmen Salazar, the airport ____ director, and I ____ to thank you for ____ this press ____. As of this week, ____ on the new regional airport is ____ on schedule for two of the three terminals. Minor design ____ to terminal A have put the project ____ behind schedule, and we ____ about two months will be ____ to the construction time frame as a ____. I'd also like to ____ that we now have a 3-D ____ model of this project! Please feel free to visit our Web site so you can ____ it.", missingWords: ["operations", "wanted", "attending", "conference", "construction", "proceeding", "adjustments", "slightly", "anticipate", "added", "result", "mention", "printed", "view"] };

// TOEIC TEST 3 EXERCISES - PART 4
const t3p4q71_73 = { id: 3401, title: "Questions 71-73", audioSrc: "", fullText: "At Volkov Tire and Auto Service, we're proud to serve the Livingstone Valley area. We offer quality automotive maintenance and repairs at affordable prices. Our mechanics are the best in the industry, and our dedication to customer service shows. Once again, readers of the Livingstone Valley Chronicle have awarded us with the title of Best in the Valley. That's five years in a row! And to celebrate, we're offering ten percent off all oil changes in July. To get this deal, you must schedule an appointment, either by phone or online. Appointments are filling up fast!", textWithBlanks: "At Volkov Tire and Auto Service, we're ____ to serve the Livingstone Valley area. We offer ____ automotive ____ and repairs at ____ prices. Our ____ are the best in the ____, and our ____ to customer service shows. Once again, ____ of the Livingstone Valley Chronicle have ____ us with the ____ of Best in the Valley. That's five years in a row! And to ____, we're offering ten percent off all oil ____ in July. To get this ____, you must ____ an appointment, either by phone or online. Appointments are ____ up fast!", missingWords: ["proud", "quality", "maintenance", "affordable", "mechanics", "industry", "dedication", "readers", "awarded", "title", "celebrate", "changes", "deal", "schedule", "filling"] };
const t3p4q74_76 = { id: 3402, title: "Questions 74-76", audioSrc: "", fullText: "Today's episode of the Financial Parade Podcast is about the possibilities and limitations of marketing on social media. How can businesses improve on their marketing efforts and do a better job of reaching their target audience? To help us answer this, we are joined by Magali Bertrand, Marketing director at Blue Lane Consulting. Ms. Bertrand is a frequent guest on the show because she is good at taking complex business principles and breaking them down to offer clear, simple advice. But first, I'd like to discuss the results of my recent survey where you all shared your approaches to product placement.", textWithBlanks: "Today's ____ of the Financial Parade Podcast is about the ____ and ____ of marketing on social media. How can businesses ____ on their marketing ____ and do a better job of ____ their target ____? To help us answer this, we are ____ by Magali Bertrand, Marketing director at Blue Lane Consulting. Ms. Bertrand is a ____ guest on the show because she is good at taking ____ business ____ and breaking them down to offer ____, simple ____. But first, I'd like to discuss the ____ of my recent ____ where you all shared your ____ to product ____.", missingWords: ["episode", "possibilities", "limitations", "improve", "efforts", "reaching", "audience", "joined", "frequent", "complex", "principles", "clear", "advice", "results", "survey", "approaches", "placement"] };
const t3p4q77_79 = { id: 3403, title: "Questions 77-79", audioSrc: "", fullText: "Next Wednesday, Arlington Landscaping will deliver the potted plants we ordered to brighten up the common areas in our office. Studies have shown that plants are great stress relievers and can increase workplace productivity. We think you'll find that this is a great improvement to our work environment. If you'd like a small plant for your desk, the company will cover the cost. To choose your plant, please check the catalog in the staff room. It has photos and care instructions.", textWithBlanks: "Next Wednesday, Arlington Landscaping will ____ the ____ plants we ordered to ____ up the ____ areas in our office. Studies have ____ that plants are great ____ relievers and can ____ workplace ____. We think you'll find that this is a great ____ to our work ____. If you'd like a small plant for your desk, the company will ____ the cost. To ____ your plant, please check the ____ in the staff room. It has photos and care ____.", missingWords: ["deliver", "potted", "brighten", "common", "shown", "stress", "increase", "productivity", "improvement", "environment", "cover", "choose", "catalog", "instructions"] };
const t3p4q80_82 = { id: 3404, title: "Questions 80-82", audioSrc: "", fullText: "In local news, the abandoned shoe factory in the central business district is finally getting a makeover. The building has been empty for three years since the factory moved to its new, larger space south of town. After hearing many proposals, the town council voted last night to sell the building to developer Matthew Hughes, who will convert it into family housing: ten modern, comfortable units with a parking garage underground. Up next, it looks like the rain is on the way out, giving way to blue skies this weekend. Samantha is here to tell us all about it.", textWithBlanks: "In local news, the ____ shoe factory in the ____ business district is finally getting a ____. The building has been ____ for three years since the factory ____ to its new, larger space south of town. After hearing many ____, the town council ____ last night to ____ the building to developer Matthew Hughes, who will ____ it into family ____: ten modern, ____ units with a parking garage ____. Up next, it looks like the rain is on the way out, giving way to blue skies this weekend. Samantha is here to tell us all about it.", missingWords: ["abandoned", "central", "makeover", "empty", "moved", "proposals", "voted", "sell", "convert", "housing", "comfortable", "underground"] };
const t3p4q83_85 = { id: 3405, title: "Questions 83-85", audioSrc: "", fullText: "Before we end this transportation agency meeting, I want to give you an update on the Springdale bridge replacement project. The project is moving forward. However, we are more than six months past the scheduled completion date. But this is just one of our many projects. Now, this delay is frustrating to residents who are dealing with traffic congestion. Therefore, I strongly recommend that we hold a press conference to address specific concerns.", textWithBlanks: "Before we end this ____ agency meeting, I want to give you an ____ on the Springdale bridge ____ project. The project is ____ forward. However, we are more than six months past the ____ completion date. But this is just one of our many projects. Now, this ____ is ____ to residents who are ____ with traffic ____. Therefore, I ____ recommend that we hold a press ____ to address specific ____.", missingWords: ["transportation", "update", "replacement", "moving", "scheduled", "delay", "frustrating", "dealing", "congestion", "strongly", "conference", "concerns"] };
const t3p4q86_88 = { id: 3406, title: "Questions 86-88", audioSrc: "", fullText: "Attention, everyone. I hope you're enjoying the second day of our weekend workshop on leadership skills for entrepreneurs. During yesterday's session, we conducted a discussion about goal setting, and we did that together as a group. However, today I'll be matching you with a partner for a one-on-one discussion. So, start thinking about any improvements you'd like to make to your communication skills, because that's what you'll be sharing with each other. And later this afternoon, we'll enjoy a prepared lunch, which has been generously donated to us by Blue Star Catering Company. We're grateful to them for their support.", textWithBlanks: "Attention, everyone. I hope you're ____ the second day of our weekend ____ on leadership ____ for entrepreneurs. During yesterday's ____, we ____ a discussion about ____ setting, and we did that together as a group. However, today I'll be ____ you with a partner for a one-on-one discussion. So, start ____ about any ____ you'd like to make to your ____ skills, because that's what you'll be ____ with each other. And later this afternoon, we'll enjoy a ____ lunch, which has been ____ donated to us by Blue Star Catering Company. We're ____ to them for their ____.", missingWords: ["enjoying", "workshop", "skills", "session", "conducted", "goal", "matching", "thinking", "improvements", "communication", "sharing", "prepared", "generously", "grateful", "support"] };
const t3p4q89_91 = { id: 3407, title: "Questions 89-91", audioSrc: "", fullText: "This is Adisa from Car Pro returning your call. In your message, you said your sedan seems sluggish and isn't accelerating well. There are a number of things that could be causing that, and prices vary with the repair. It could be as simple as a clogged oil filter, which is inexpensive to fix. But we'll have to take a look. Oh, by the way, we're closing early tomorrow, but we can get you in the day after. We'll open at eight A. M.", textWithBlanks: "This is Adisa from Car Pro ____ your call. In your ____, you said your sedan seems ____ and isn't ____ well. There are a ____ of things that could be ____ that, and prices ____ with the repair. It could be as ____ as a ____ oil filter, which is ____ to fix. But we'll have to take a look. Oh, by the way, we're ____ early tomorrow, but we can get you in the day after. We'll open at eight A. M.", missingWords: ["returning", "message", "sluggish", "accelerating", "number", "causing", "vary", "simple", "clogged", "inexpensive", "closing"] };
const t3p4q92_94 = { id: 3408, title: "Questions 92-94", audioSrc: "", fullText: "Thanks, everyone, for helping set up the showroom floor with the displays of the new bedroom and living room sets. They look great. Many of you have asked for time off next Wednesday to attend the town parade. I wasn't sure I could grant those requests, but after thinking about it, I realized that that day will probably not be a profitable day for us anyway. I'll post a new employee schedule! Oh, and one more quick announcement-I need all of you to put in an order for a new uniform. It's time we replaced them.", textWithBlanks: "Thanks, everyone, for ____ set up the ____ floor with the ____ of the new bedroom and living room sets. They look ____. Many of you have ____ for time off next Wednesday to ____ the town ____. I wasn't sure I could ____ those requests, but after ____ about it, I ____ that that day will probably not be a ____ day for us anyway. I'll post a new employee ____! Oh, and one more quick ____-I need all of you to put in an order for a new ____. It's time we ____ them.", missingWords: ["helping", "showroom", "displays", "great", "asked", "attend", "parade", "grant", "thinking", "realized", "profitable", "schedule", "announcement", "uniform", "replaced"] };
const t3p4q95_97 = { id: 3409, title: "Questions 95-97", audioSrc: "", fullText: "Hi. This is Emily calling from Speedy Services. I'm picking you up from the central train station today. I see you selected a pickup location near the ticket windows, but there's heavy traffic on that street. Would it be possible to change your pickup location to right outside the station's grand concourse? It's the designated area for rideshare services. Please let me know if you agree with this change by responding to the prompt within the app. Thanks!", textWithBlanks: "Hi. This is Emily calling from Speedy Services. I'm ____ you up from the ____ train station today. I see you ____ a pickup ____ near the ticket windows, but there's ____ traffic on that street. Would it be ____ to change your pickup location to right ____ the station's grand ____? It's the ____ area for ____ services. Please let me know if you ____ with this change by ____ to the prompt within the app. Thanks!", missingWords: ["picking", "central", "selected", "location", "heavy", "possible", "outside", "concourse", "designated", "rideshare", "agree", "responding"] };
const t3p4q98_100 = { id: 3410, title: "Questions 98-100", audioSrc: "", fullText: "Welcome, everyone, to the grand opening of the Wilton Business Center. As the mayor, I'm pleased to see this kind of growth in our city. And the environmentally friendly elements incorporated into the design make this building special. In particular, this building is equipped with a water recycling system and insulation made from repurposed cloth. While today is the grand opening, one part of the building- the recreation center-will not be available for use until next month, as final touches are still being added to that floor.", textWithBlanks: "Welcome, everyone, to the grand ____ of the Wilton Business Center. As the ____, I'm ____ to see this kind of ____ in our city. And the ____ friendly ____ incorporated into the ____ make this building special. In ____, this building is ____ with a water ____ system and ____ made from ____ cloth. While today is the grand opening, one part of the building- the ____ center-will not be ____ for use until next month, as final ____ are still being ____ to that floor.", missingWords: ["opening", "mayor", "pleased", "growth", "environmentally", "elements", "design", "particular", "equipped", "recycling", "insulation", "repurposed", "recreation", "available", "touches", "added"] };

// TOEIC TEST 4 EXERCISES - PART 4
const t4p4q71_73 = { id: 4471, title: "Test 4 - Part 4 - Q71-73", audioSrc: "", fullText: "At Volkov Tire and Auto Service, we're proud to serve the Livingstone Valley area. We offer quality automotive maintenance and repairs at affordable prices. Our mechanics are the best in the industry, and our dedication to customer service shows. Once again, readers of the Livingstone Valley Chronicle have awarded us with the title of Best in the Valley. That's five years in a row! And to celebrate, we're offering ten percent off all oil changes in July. To get this deal, you must schedule an appointment, either by phone or online. Appointments are filling up fast!", textWithBlanks: "At Volkov Tire and Auto Service, we're ____ to serve the Livingstone Valley area. We offer ____ automotive ____ and repairs at ____ prices. Our ____ are the best in the ____, and our ____ to customer service shows. Once again, ____ of the Livingstone Valley Chronicle have ____ us with the ____ of Best in the Valley. That's five years in a row! And to ____, we're offering ten percent off all oil ____ in July. To get this ____, you must ____ an appointment, either by phone or online. Appointments are ____ up fast!", missingWords: ["proud", "quality", "maintenance", "affordable", "mechanics", "industry", "dedication", "readers", "awarded", "title", "celebrate", "changes", "deal", "schedule", "filling"] };
const t4p4q74_76 = { id: 4474, title: "Test 4 - Part 4 - Q74-76", audioSrc: "", fullText: "Today's episode of the Financial Parade Podcast is about the possibilities and limitations of marketing on social media. How can businesses improve on their marketing efforts and do a better job of reaching their target audience? To help us answer this, we are joined by Magali Bertrand, Marketing director at Blue Lane Consulting. Ms. Bertrand is a frequent guest on the show because she is good at taking complex business principles and breaking them down to offer clear, simple advice. But first, I'd like to discuss the results of my recent survey where you all shared your approaches to product placement.", textWithBlanks: "Today's ____ of the Financial Parade Podcast is about the ____ and ____ of marketing on social media. How can businesses ____ on their marketing ____ and do a better job of ____ their target ____? To help us answer this, we are ____ by Magali Bertrand, Marketing director at Blue Lane Consulting. Ms. Bertrand is a ____ guest on the show because she is good at taking ____ business ____ and breaking them down to offer ____, simple ____. But first, I'd like to discuss the ____ of my recent ____ where you all shared your ____ to product ____.", missingWords: ["episode", "possibilities", "limitations", "improve", "efforts", "reaching", "audience", "joined", "frequent", "complex", "principles", "clear", "advice", "results", "survey", "approaches", "placement"] };
const t4p4q77_79 = { id: 4477, title: "Test 4 - Part 4 - Q77-79", audioSrc: "", fullText: "Next Wednesday, Arlington Landscaping will deliver the potted plants we ordered to brighten up the common areas in our office. Studies have shown that plants are great stress relievers and can increase workplace productivity. We think you'll find that this is a great improvement to our work environment. If you'd like a small plant for your desk, the company will cover the cost. To choose your plant, please check the catalog in the staff room. It has photos and care instructions.", textWithBlanks: "Next Wednesday, Arlington Landscaping will ____ the ____ plants we ordered to ____ up the ____ areas in our office. Studies have ____ that plants are great ____ relievers and can ____ workplace ____. We think you'll find that this is a great ____ to our work ____. If you'd like a small plant for your desk, the company will ____ the cost. To ____ your plant, please check the ____ in the staff room. It has photos and care ____.", missingWords: ["deliver", "potted", "brighten", "common", "shown", "stress", "increase", "productivity", "improvement", "environment", "cover", "choose", "catalog", "instructions"] };
const t4p4q80_82 = { id: 4480, title: "Test 4 - Part 4 - Q80-82", audioSrc: "", fullText: "In local news, the abandoned shoe factory in the central business district is finally getting a makeover. The building has been empty for three years since the factory moved to its new, larger space south of town. After hearing many proposals, the town council voted last night to sell the building to developer Matthew Hughes, who will convert it into family housing: ten modern, comfortable units with a parking garage underground. Up next, it looks like the rain is on the way out, giving way to blue skies this weekend. Samantha is here to tell us all about it.", textWithBlanks: "In local news, the ____ shoe factory in the ____ business district is finally getting a ____. The building has been ____ for three years since the factory ____ to its new, larger space south of town. After hearing many ____, the town council ____ last night to ____ the building to developer Matthew Hughes, who will ____ it into family ____: ten modern, ____ units with a parking garage ____. Up next, it looks like the rain is on the way out, giving way to blue skies this weekend. Samantha is here to tell us all about it.", missingWords: ["abandoned", "central", "makeover", "empty", "moved", "proposals", "voted", "sell", "convert", "housing", "comfortable", "underground"] };
const t4p4q83_85 = { id: 4483, title: "Test 4 - Part 4 - Q83-85", audioSrc: "", fullText: "Before we end this transportation agency meeting, I want to give you an update on the Springdale bridge replacement project. The project is moving forward. However, we are more than six months past the scheduled completion date. But this is just one of our many projects. Now, this delay is frustrating to residents who are dealing with traffic congestion. Therefore, I strongly recommend that we hold a press conference to address specific concerns.", textWithBlanks: "Before we end this ____ agency meeting, I want to give you an ____ on the Springdale bridge ____ project. The project is ____ forward. However, we are more than six months past the ____ completion date. But this is just one of our many projects. Now, this ____ is ____ to residents who are ____ with traffic ____. Therefore, I ____ recommend that we hold a press ____ to address specific ____.", missingWords: ["transportation", "update", "replacement", "moving", "scheduled", "delay", "frustrating", "dealing", "congestion", "strongly", "conference", "concerns"] };
const t4p4q86_88 = { id: 4486, title: "Test 4 - Part 4 - Q86-88", audioSrc: "", fullText: "Attention, everyone. I hope you're enjoying the second day of our weekend workshop on leadership skills for entrepreneurs. During yesterday's session, we conducted a discussion about goal setting, and we did that together as a group. However, today I'll be matching you with a partner for a one-on-one discussion. So, start thinking about any improvements you'd like to make to your communication skills, because that's what you'll be sharing with each other. And later this afternoon, we'll enjoy a prepared lunch, which has been generously donated to us by Blue Star Catering Company. We're grateful to them for their support.", textWithBlanks: "Attention, everyone. I hope you're ____ the second day of our weekend ____ on leadership ____ for entrepreneurs. During yesterday's ____, we ____ a discussion about ____ setting, and we did that together as a group. However, today I'll be ____ you with a partner for a one-on-one discussion. So, start ____ about any ____ you'd like to make to your ____ skills, because that's what you'll be ____ with each other. And later this afternoon, we'll enjoy a ____ lunch, which has been ____ donated to us by Blue Star Catering Company. We're ____ to them for their ____.", missingWords: ["enjoying", "workshop", "skills", "session", "conducted", "goal", "matching", "thinking", "improvements", "communication", "sharing", "prepared", "generously", "grateful", "support"] };
const t4p4q89_91 = { id: 4489, title: "Test 4 - Part 4 - Q89-91", audioSrc: "", fullText: "This is Adisa from Car Pro returning your call. In your message, you said your sedan seems sluggish and isn't accelerating well. There are a number of things that could be causing that, and prices vary with the repair. It could be as simple as a clogged oil filter, which is inexpensive to fix. But we'll have to take a look. Oh, by the way, we're closing early tomorrow, but we can get you in the day after. We'll open at eight A. M.", textWithBlanks: "This is Adisa from Car Pro ____ your call. In your ____, you said your sedan seems ____ and isn't ____ well. There are a ____ of things that could be ____ that, and prices ____ with the repair. It could be as ____ as a ____ oil filter, which is ____ to fix. But we'll have to take a look. Oh, by the way, we're ____ early tomorrow, but we can get you in the day after. We'll open at eight A. M.", missingWords: ["returning", "message", "sluggish", "accelerating", "number", "causing", "vary", "simple", "clogged", "inexpensive", "closing"] };
const t4p4q92_94 = { id: 4492, title: "Test 4 - Part 4 - Q92-94", audioSrc: "", fullText: "Thanks, everyone, for helping set up the showroom floor with the displays of the new bedroom and living room sets. They look great. Many of you have asked for time off next Wednesday to attend the town parade. I wasn't sure I could grant those requests, but after thinking about it, I realized that that day will probably not be a profitable day for us anyway. I'll post a new employee schedule! Oh, and one more quick announcement-I need all of you to put in an order for a new uniform. It's time we replaced them.", textWithBlanks: "Thanks, everyone, for ____ set up the ____ floor with the ____ of the new bedroom and living room sets. They look ____. Many of you have ____ for time off next Wednesday to ____ the town ____. I wasn't sure I could ____ those requests, but after ____ about it, I ____ that that day will probably not be a ____ day for us anyway. I'll post a new employee ____! Oh, and one more quick ____-I need all of you to put in an order for a new ____. It's time we ____ them.", missingWords: ["helping", "showroom", "displays", "great", "asked", "attend", "parade", "grant", "thinking", "realized", "profitable", "schedule", "announcement", "uniform", "replaced"] };
const t4p4q95_97 = { id: 4495, title: "Test 4 - Part 4 - Q95-97", audioSrc: "", fullText: "Hi. This is Emily calling from Speedy Services. I'm picking you up from the central train station today. I see you selected a pickup location near the ticket windows, but there's heavy traffic on that street. Would it be possible to change your pickup location to right outside the station's grand concourse? It's the designated area for rideshare services. Please let me know if you agree with this change by responding to the prompt within the app. Thanks!", textWithBlanks: "Hi. This is Emily calling from Speedy Services. I'm ____ you up from the ____ train station today. I see you ____ a pickup ____ near the ticket windows, but there's ____ traffic on that street. Would it be ____ to change your pickup location to right ____ the station's grand ____? It's the ____ area for ____ services. Please let me know if you ____ with this change by ____ to the prompt within the app. Thanks!", missingWords: ["picking", "central", "selected", "location", "heavy", "possible", "outside", "concourse", "designated", "rideshare", "agree", "responding"] };
const t4p4q98_100 = { id: 4498, title: "Test 4 - Part 4 - Q98-100", audioSrc: "", fullText: "Welcome, everyone, to the grand opening of the Wilton Business Center. As the mayor, I'm pleased to see this kind of growth in our city. And the environmentally friendly elements incorporated into the design make this building special. In particular, this building is equipped with a water recycling system and insulation made from repurposed cloth. While today is the grand opening, one part of the building- the recreation center-will not be available for use until next month, as final touches are still being added to that floor.", textWithBlanks: "Welcome, everyone, to the grand ____ of the Wilton Business Center. As the ____, I'm ____ to see this kind of ____ in our city. And the ____ friendly ____ incorporated into the ____ make this building special. In ____, this building is ____ with a water ____ system and ____ made from ____ cloth. While today is the grand opening, one part of the building- the ____ center-will not be ____ for use until next month, as final ____ are still being ____ to that floor.", missingWords: ["opening", "mayor", "pleased", "growth", "environmentally", "elements", "design", "particular", "equipped", "recycling", "insulation", "repurposed", "recreation", "available", "touches", "added"] };

// BASE EXERCISES - PART 4
const part4_q1 = {
    id: 401,
    title: "Question 1",
    audioSrc: "",
    fullText: "Hi, you are calling the Novaland management office information line. Please be aware that there will be maintenance work to repave the entire parking garage adjacent to our building's front entrance on Friday, July third. Vehicles of all Novaland residents are required to be moved before 9AM next Saturday because their parking slots will be changed. After 9AM, any cars left in the parking area will be towed and the owner will be responsible for the expense. Finally, some alternative parking places will be posted in the building reception and I also will email it to all residents this afternoon.",
    textWithBlanks: "Hi, you are ____ the Novaland ____ office ____ line. Please be ____ that there will be ____ work to ____ the ____ parking garage ____ to our building's front ____ on Friday, July third. ____ of all Novaland ____ are ____ to be ____ before 9AM next Saturday because their parking ____ will be ____. After 9AM, any cars left in the ____ area will be ____ and the owner will be ____ for the ____. Finally, some ____ parking places will be ____ in the building ____ and I also will ____ it to all residents this afternoon.",
    missingWords: ["calling", "management", "information", "aware", "maintenance", "repave", "entire", "adjacent", "entrance", "Vehicles", "residents", "required", "moved", "slots", "changed", "parking", "towed", "responsible", "expense", "alternative", "posted", "reception", "email"],
};
const part4_q2 = {
    id: 402,
    title: "Question 2",
    audioSrc: "",
    fullText: "Welcome to House Help Channel. For today's episode, maintaining and making minor repairs to the roof of your home is what we'll go over. To begin, investing in a few special tools is the first thing to do, for example, a trowel and crowbar. Because you'll use them for many years, it's important to choose some that are high quality. You can seal any cracks or chips with your trowel and some roof cement. You can then replace loose shingles with the help of the crowbar after removing them. Now, every year, I highly recommend you take photos of your roof so that you can track its overall condition.",
    textWithBlanks: "Welcome to House Help Channel. For today's ____, ____ and making ____ repairs to the ____ of your home is what we'll go over. To begin, ____ in a few ____ tools is the first thing to do, for example, a ____ and crowbar. Because you'll use them for many years, it's ____ to choose some that are high ____. You can ____ any cracks or ____ with your trowel and some roof ____. You can then ____ loose shingles with the help of the crowbar after ____ them. Now, every year, I ____ recommend you take ____ of your roof so that you can ____ its ____ condition.",
    missingWords: ["episode", "maintaining", "minor", "roof", "investing", "special", "trowel", "important", "quality", "seal", "chips", "cement", "replace", "removing", "highly", "photos", "track", "overall"],
};
const part4_q3 = {
    id: 403,
    title: "Question 3",
    audioSrc: "",
    fullText: "Thanks again for joining the tour of the wonderful New York Conservatory with me today. I hope you enjoyed the species of plants and flowers that you saw and learned about. At the beginning of our tour, I mentioned the world-renowned botanist John Wick. At 2 o’clock, he will be giving a lecture on the care of flowering orchid plants. I highly recommend that you attend his speech because his work was in a famous documentary film named Plant Farmer. The conservatory's online gift shop is selling this, you can purchase it easily. Recently, I’ve learned many new things about the orchid species we have right here at the conservatory after watching this film.",
    textWithBlanks: "Thanks again for ____ the tour of the ____ New York Conservatory with me today. I hope you ____ the ____ of plants and flowers that you saw and ____ about. At the ____ of our tour, I ____ the world-____ botanist John Wick. At 2 o’clock, he will be giving a ____ on the ____ of flowering ____ plants. I highly ____ that you attend his ____ because his work was in a ____ documentary film named Plant Farmer. The conservatory's online ____ shop is ____ this, you can ____ it easily. ____, I’ve learned many new things about the orchid species we have right here at the conservatory after ____ this film.",
    missingWords: ["joining", "wonderful", "enjoyed", "species", "learned", "beginning", "mentioned", "renowned", "lecture", "care", "orchid", "recommend", "speech", "famous", "gift", "selling", "purchase", "Recently", "watching"],
};
const part4_q4 = {
    id: 404,
    title: "Question 4",
    audioSrc: "",
    fullText: "I want to thank you all again for helping the Wonder Community Center before the benefit concert begins. As I mentioned last month, some parts of our facility need to be repaired . In selling tickets, we have got 7000 dollars so far, but we still need more to achieve our target. Therefore, I highly recommend you buy some snacks or soda drinks in the concession stand before entering the concert. We will use 90 percent of the proceeds from this to cover the construction at our Wonder Community Center. I hope you have a great day!",
    textWithBlanks: "I want to ____ you all again for ____ the Wonder Community Center before the ____ concert begins. As I ____ last month, some parts of our ____ need to be ____ . In ____ tickets, we have got 7000 dollars so far, but we still need more to ____ our ____. Therefore, I highly ____ you buy some snacks or soda drinks in the ____ stand before ____ the concert. We will use 90 ____ of the ____ from this to ____ the construction at our Wonder Community Center. I hope you have a ____ day!",
    missingWords: ["thank", "helping", "benefit", "mentioned", "facility", "repaired", "selling", "achieve", "target", "recommend", "concession", "entering", "percent", "proceeds", "cover", "great"],
};
const part4_q5 = {
    id: 405,
    title: "Question 5",
    audioSrc: "",
    fullText: "We appreciate you all being here for today's workshop. This session will be led by Thomas Frank and myself, and our focus will be on business owners using their time efficiently. For business success, planning and spending your time wisely is the key. In the packet we have handed to you during your arrival, there are some documents I’ll be referring to for the topic of our presentation today. If you haven't got one yet, Thomas is right at the green chair. Alright, to begin, I have an exercise to help us get to know one another better.",
    textWithBlanks: "We ____ you all being here for today's ____. This ____ will be led by Thomas Frank and myself, and our ____ will be on business ____ using their time ____. For business ____, planning and ____ your time ____ is the key. In the ____ we have ____ to you during your ____, there are some documents I’ll be ____ to for the ____ of our presentation today. If you haven't got one yet, Thomas is right at the green chair. Alright, to ____, I have an ____ to help us get to know one another ____.",
    missingWords: ["appreciate", "workshop", "session", "focus", "owners", "efficiently", "success", "spending", "wisely", "packet", "handed", "arrival", "referring", "topic", "begin", "exercise", "better"],
};
const part4_q6 = {
    id: 406,
    title: "Question 6",
    audioSrc: "",
    fullText: "Archaeologists at this site have uncovered the remains of an eleventh-century marketplace, including colorful mosaic tiles on the walls. Even after all these centuries, you'll notice the vibrant colors. This is the most important part of these ruins. In the artists’ pictures, you can easily see the intricate details from daily life scenes. A roof has been constructed over the area, making the lights dim to protect these mosaics now. Also, no photos are allowed due to flash damage to the tiles. As we move forward, please use the handrails on both sides for staying on the path and protecting the surrounding ruins.",
    textWithBlanks: "____ at this site have ____ the remains of an eleventh-century ____, including ____ mosaic ____ on the walls. Even after all these ____, you'll notice the ____ colors. This is the most ____ part of these ____. In the artists’ pictures, you can ____ see the ____ details from daily life scenes. A ____ has been ____ over the area, making the lights ____ to protect these mosaics now. Also, no photos are ____ due to ____ damage to the tiles. As we move forward, please use the ____ on both sides for ____ on the path and ____ the surrounding ruins.",
    missingWords: ["Archaeologists", "uncovered", "marketplace", "colorful", "tiles", "centuries", "vibrant", "important", "ruins", "easily", "intricate", "roof", "constructed", "dim", "allowed", "flash", "handrails", "staying", "protecting"],
};
const part4_q7 = {
    id: 407,
    title: "Question 7",
    audioSrc: "",
    fullText: "As you all know, our agency finally won the important advertising contract with McDonald Fast Food Company. What we need to develop is 5 advertisements in total. Three 45-second ads for a local supermarket to be released next two weeks and four additional 25-second ads for the next month. Although the schedule looks very tight, I know, we must prioritize this because it is the biggest contract for this year. The client has begun internal work, so we have a rough ad available for editing. Let’s focus on that now.",
    textWithBlanks: "As you all know, our ____ finally ____ the important ____ contract with McDonald Fast Food Company. What we need to ____ is 5 advertisements in ____. Three 45-second ads for a local ____ to be ____ next two weeks and four ____ 25-second ads for the next month. Although the ____ looks very ____, I know, we must ____ this because it is the ____ contract for this year. The client has ____ internal work, so we have a ____ ad ____ for editing. Let’s ____ on that now.",
    missingWords: ["agency", "won", "advertising", "develop", "total", "supermarket", "released", "additional", "schedule", "tight", "prioritize", "biggest", "begun", "rough", "available", "focus"],
};
const part4_q8 = {
    id: 408,
    title: "Question 8",
    audioSrc: "",
    fullText: "Excuse me, nurses. Your attention please. I've been receiving complaints about the free snacks in the hospital break rooms. Some people have mentioned that they don't like the selection of snacks, and some have said that they don't get to eat them at all because they're gone by the time the evening shift starts. So I was thinking about putting some money into each of your staff spending accounts every month so that you can buy the snacks you want at the hospital cafeteria. That will require management approval, but I'll keep you posted.",
    textWithBlanks: "Excuse me, nurses. Your ____ please. I've been ____ complaints about the ____ snacks in the hospital ____ rooms. Some people have ____ that they don't like the ____ of snacks, and some have said that they don't get to eat them at all because they're ____ by the time the evening ____ starts. So I was ____ about putting some money into each of your staff ____ accounts every month so that you can ____ the snacks you want at the hospital ____. That will ____ management ____, but I'll keep you ____.",
    missingWords: ["attention", "receiving", "free", "break", "mentioned", "selection", "gone", "shift", "thinking", "spending", "buy", "cafeteria", "require", "approval", "posted"],
};
const part4_q9 = {
    id: 409,
    title: "Question 9",
    audioSrc: "",
    fullText: "Hi all, it’s me again, the mayor of Hanoi city. I’m glad you are here to celebrate the recent renovation of Hanoi National Mountain in our town. The mountain has many new areas to explore. Therefore, we will take a long hike here. First, we will visit the biggest zoo and then will hike on the top of the mountain. Finally, we will end our tour at the picnic area in the middle of the stream. There we’ll have some free cookies and pies. If you take pictures, please put them on the city's website. We'd like to have a commemoration of this special day.",
    textWithBlanks: "Hi all, it’s me again, the ____ of Hanoi city. I’m ____ you are here to ____ the recent ____ of Hanoi National Mountain in our town. The mountain has many new areas to ____. Therefore, we will take a long ____ here. First, we will ____ the biggest zoo and then will hike on the ____ of the mountain. Finally, we will ____ our tour at the ____ area in the middle of the ____. There we’ll have some free ____ and pies. If you take ____, please put them on the city's website. We'd like to have a ____ of this ____ day.",
    missingWords: ["mayor", "glad", "celebrate", "renovation", "explore", "hike", "visit", "top", "end", "picnic", "stream", "cookies", "pictures", "commemoration", "special"],
};
const part4_q10 = {
    id: 410,
    title: "Question 10",
    audioSrc: "",
    fullText: "Thank you all for being here at today's free public lecture, which is sponsored by the Springfield Farmers' Association. Many of you have asked for information about how to grow a fruit garden. People are interested in learning how to maintain their garden's health and achieve the fruits they want. First, we suggest starting with regular soil testing. Now we are in January, it’s important that all soil samples collected in the next few months come from the same depth, as shown on this chart. And don’t forget to sign up for our monthly email list before you leave, so you can receive updates on upcoming lectures.",
    textWithBlanks: "Thank you all for being here at today's free public ____, which is ____ by the Springfield Farmers' ____. Many of you have ____ for information about how to ____ a fruit garden. People are ____ in learning how to ____ their garden's ____ and ____ the fruits they want. First, we ____ starting with ____ soil testing. Now we are in January, it’s ____ that all soil ____ collected in the next few months come from the same ____, as ____ on this chart. And don’t ____ to sign up for our ____ email list before you leave, so you can ____ updates on ____ lectures.",
    missingWords: ["lecture", "sponsored", "Association", "asked", "grow", "interested", "maintain", "health", "achieve", "suggest", "regular", "important", "samples", "depth", "shown", "forget", "monthly", "receive", "upcoming"],
};

export const dictationPart4Data: DictationPart = {
    id: 4,
    title: "Part 4: Short Talks",
    description: "Listen to short talks by a single speaker and answer related questions.",
    tests: [
        { id: 1, title: "Test 1", exercises: [
            part4_q1, part4_q2, part4_q3, part4_q4, 
            part4_q5, part4_q6, part4_q7, part4_q8, 
            part4_q9, part4_q10
        ] },
        { id: 2, title: "Test 2", exercises: [
            t2p4q71_73, t2p4q74_76, t2p4q77_79, t2p4q80_82, t2p4q83_85, t2p4q86_88, t2p4q89_91,
            t2p4q92_94, t2p4q95_97, t2p4q98_100
        ] },
        { id: 3, title: "Test 3", exercises: [
            t3p4q71_73, t3p4q74_76, t3p4q77_79, t3p4q80_82, t3p4q83_85, t3p4q86_88, t3p4q89_91,
            t3p4q92_94, t3p4q95_97, t3p4q98_100
        ] },
        { id: 4, title: "Test 4", exercises: [
            t4p4q71_73, t4p4q74_76, t4p4q77_79, t4p4q80_82, t4p4q83_85, t4p4q86_88, t4p4q89_91,
            t4p4q92_94, t4p4q95_97, t4p4q98_100
        ] },
        { id: 5, title: "Test 5", exercises: [
            t5p4q71_73, t5p4q74_76, t5p4q77_79, t5p4q80_82, t5p4q83_85, t5p4q86_88, t5p4q89_91,
            t5p4q92_94, t5p4q95_97, t5p4q98_100
        ] },
        { id: 6, title: "Test 6", exercises: [
            t2p4q71_73, t2p4q74_76, t2p4q77_79, t2p4q80_82, t2p4q83_85, t2p4q86_88, t2p4q89_91,
            t2p4q92_94, t2p4q95_97, t2p4q98_100
        ] },
        { id: 7, title: "Test 7", exercises: [
            t3p4q71_73, t3p4q74_76, t3p4q77_79, t3p4q80_82, t3p4q83_85, t3p4q86_88, t3p4q89_91,
            t3p4q92_94, t3p4q95_97, t3p4q98_100
        ] },
        { id: 8, title: "Test 8", exercises: [
            t4p4q71_73, t4p4q74_76, t4p4q77_79, t4p4q80_82, t4p4q83_85, t4p4q86_88, t4p4q89_91,
            t4p4q92_94, t4p4q95_97, t4p4q98_100
        ] },
    ]
};
