import { VocabularyPart, VocabularyTest } from '../types';

export const vocabularyData: VocabularyPart[] = [
    {
        id: 5,
        title: "Vocabulary - Part 5",
        description: "Focus on words commonly found in incomplete sentences.",
        tests: [
            {
                id: 1, title: "Test 1", words: [
                    { word: "acquire", definition: "To get or buy something.", example: "The company will acquire several smaller firms this year." },
                    { word: "comply", definition: "To act according to an order, set of rules, or request.", example: "All employees must comply with the new safety regulations." },
                    { word: "delegate", definition: "To give a particular job, duty, or responsibility to someone else.", example: "A good manager knows when to delegate tasks to their team." },
                    { word: "endorse", definition: "To make a public statement of your approval or support for something or someone.", example: "The popular athlete was paid to endorse the new sports drink." },
                    { word: "facilitate", definition: "To make something possible or easier.", example: "The new software will facilitate better communication between departments." },
                    { word: "implement", definition: "To start using a plan or system.", example: "The changes to the company policy will be implemented next month." },
                    { word: "jeopardize", definition: "To put something such as a plan or system in danger of being harmed or damaged.", example: "Failing to meet the deadline could jeopardize the entire project." },
                    { word: "liaise", definition: "To speak to people in other organizations in order to exchange information with them.", example: "You will need to liaise with the marketing team to finalize the campaign." },
                    { word: "negotiate", definition: "To have formal discussions with someone in order to reach an agreement.", example: "The union is preparing to negotiate a new contract with the management." },
                    { word: "optimize", definition: "To make something as good or effective as possible.", example: "We need to optimize our workflow to increase efficiency." },
                ]
            },
            {
                id: 2, title: "Test 2", words: [
                    { word: "allocate", definition: "To give something to someone as their share of a total amount, to use in a particular way.", example: "The government has allocated £10 million for health education." },
                    { word: "authorize", definition: "To give official permission for something to happen, or to give someone official permission to do something.", example: "Only managers are authorized to sign checks." },
                    { word: "collaborate", definition: "To work with someone else for a special purpose.", example: "The two companies will collaborate on the development of a new product." },
                    { word: "diagnose", definition: "To recognize and name the exact character of a disease or a problem, by examining it.", example: "The mechanic diagnosed the problem with the car's engine." },
                    { word: "enhance", definition: "To improve the quality, amount, or strength of something.", example: "These scandals will not enhance the organization's reputation." },
                    { word: "generate", definition: "To cause something to exist.", example: "The new factory is expected to generate more than 200 jobs." },
                    { word: "innovate", definition: "To introduce changes and new ideas.", example: "The company must constantly innovate to stay ahead of its competitors." },
                    { word: "modify", definition: "To change something, usually to improve it.", example: "The design was modified to increase the product's lifespan." },
                    { word: "rectify", definition: "To correct something or make something right.", example: "We must take steps to rectify the error." },
                    { word: "streamline", definition: "To improve the effectiveness of an organization by using new methods.", example: "The company is streamlining its operations to reduce costs." },
                ]
            },
            // Simplified for brevity
            { id: 3, title: "Test 3", words: [ { word: "convene", definition: "To bring together a group of people for a meeting.", example: "The committee will convene at 11:30 next Friday." } ] },
            { id: 4, title: "Test 4", words: [ { word: "diversify", definition: "To start to produce a range of different things or to invest in a range of different assets.", example: "Farmers are being encouraged to diversify into other crops." } ] },
            { id: 5, title: "Test 5", words: [ { word: "outsource", definition: "To pay to have part of its work done by another company.", example: "The company decided to outsource its IT support." } ] },
        ]
    },
    {
        id: 6,
        title: "Vocabulary - Part 6",
        description: "Learn words and phrases often used in text completion passages.",
        tests: [
            {
                id: 1, title: "Test 1", words: [
                    { word: "consequently", definition: "As a result.", example: "She failed her exams and, consequently, was unable to go to university." },
                    { word: "furthermore", definition: "In addition; more importantly.", example: "The house is beautiful. Furthermore, it's in a great location." },
                    { word: "however", definition: "Used to introduce a statement that contrasts with or seems to contradict something that has been said previously.", example: "He was feeling very ill. However, he went to work." },
                    { word: "likewise", definition: "In the same way.", example: "Just water these plants twice a week, and likewise the ones in the bedroom." },
                    { word: "meanwhile", definition: "In the period of time between two events.", example: "The flight will be announced soon. Meanwhile, you can get a coffee." },
                    { word: "nevertheless", definition: "Despite what has just been said or referred to.", example: "I knew a lot about the subject already, but her talk was interesting nevertheless." },
                    { word: "subsequently", definition: "After something else.", example: "He was badly injured in the crash and subsequently died." },
                    { word: "therefore", definition: "For that reason.", example: "We were unable to get funding and therefore had to abandon the project." },
                    { word: "whereas", definition: "Compared with the fact that; but.", example: "He must be about 60, whereas his wife looks about 30." },
                    { word: "in fact", definition: "Used to emphasize the truth of a statement, especially one that is surprising or contrary to what has been said.", example: "He looks very young, but in fact he's almost 50." },
                ]
            },
             // Simplified for brevity
            { id: 2, title: "Test 2", words: [ { word: "additionally", definition: "Also; in addition.", example: "Additionally, we request a deposit on all rentals." } ] },
            { id: 3, title: "Test 3", words: [ { word: "nonetheless", definition: "In spite of that; nevertheless.", example: "The hike was difficult, but enjoyable nonetheless." } ] },
            { id: 4, title: "Test 4", words: [ { word: "similarly", definition: "In a similar way.", example: "The two cars are similarly priced." } ] },
            { id: 5, title: "Test 5", words: [ { word: "ultimately", definition: "Finally, after a series of things have happened.", example: "Ultimately, he had to agree that she was right." } ] },
        ]
    },
    {
        id: 7,
        title: "Vocabulary - Part 7",
        description: "Master vocabulary from reading comprehension texts like articles and emails.",
        tests: [
            {
                id: 6, title: "Test 1 - 147-150", words: [
                    { word: "purchasing", definition: "mua sắm, mua hàng", example: "" },
                    { word: "unpacking", definition: "mở hộp, tháo gói", example: "" },
                    { word: "verify", definition: "xác minh, kiểm tra", example: "" },
                    { word: "components", definition: "các bộ phận, linh kiện", example: "" },
                    { word: "included", definition: "bao gồm", example: "" },
                    { word: "place", definition: "đặt, để", example: "" },
                    { word: "safe", definition: "an toàn", example: "" },
                    { word: "avoid", definition: "tránh, né", example: "" },
                    { word: "loss", definition: "mất mát, hư hỏng", example: "" },
                    { word: "damage", definition: "hư hỏng, làm hỏng", example: "" },
                    { word: "assemble", definition: "lắp ráp, lắp đặt", example: "" },
                    { word: "soft", definition: "mềm", example: "" },
                    { word: "flattened", definition: "làm phẳng, bị ép phẳng", example: "" },
                    { word: "empty", definition: "trống rỗng", example: "" },
                    { word: "assembly", definition: "sự lắp ráp", example: "" },
                    { word: "main", definition: "chính", example: "" },
                    { word: "side", definition: "mặt, bên", example: "" },
                    { word: "never", definition: "không bao giờ", example: "" },
                    { word: "overtighten", definition: "vặn quá chặt", example: "" },
                    { word: "screws", definition: "ốc vít", example: "" },
                    { word: "bolts", definition: "bu lông", example: "" },
                    { word: "wood", definition: "gỗ", example: "" },
                    { word: "cushioning", definition: "đệm, lót đệm", example: "" },
                    { word: "obtain", definition: "đạt được, lấy được", example: "" },
                    { word: "maintenance", definition: "bảo trì, bảo dưỡng", example: "" },
                    { word: "register", definition: "đăng ký", example: "" },
                    { word: "product", definition: "sản phẩm", example: "" },
                    { word: "warranty", definition: "bảo hành", example: "" },
                    { word: "coverage", definition: "phạm vi, sự bao phủ", example: "" },
                    { word: "staff", definition: "nhân viên", example: "" },
                    { word: "keep", definition: "giữ, giữ lại", example: "" },
                    { word: "copy", definition: "bản sao, bản in", example: "" },
                    { word: "schedule", definition: "lịch trình, thời gian biểu", example: "" },
                    { word: "desks", definition: "bàn làm việc", example: "" },
                    { word: "quick", definition: "nhanh, nhanh chóng", example: "" },
                    { word: "reference", definition: "tham khảo, tài liệu tham khảo", example: "" },
                    { word: "interoffice", definition: "nội bộ văn phòng", example: "" },
                    { word: "meetings", definition: "các cuộc họp", example: "" },
                    { word: "whenever", definition: "bất cứ khi nào", example: "" },
                    { word: "possible", definition: "có thể", example: "" },
                    { word: "underlined", definition: "được gạch chân", example: "" },
                    { word: "hours", definition: "giờ, khoảng thời gian", example: "" },
                    { word: "conference", definition: "hội nghị, cuộc họp", example: "" },
                    { word: "firm", definition: "công ty, hãng", example: "" },
                    { word: "administrative", definition: "thuộc về hành chính", example: "" },
                    { word: "assistants", definition: "trợ lý", example: "" },
                    { word: "preferred", definition: "được ưu tiên, được yêu thích", example: "" }
                ]
            },
            {
                id: 7, title: "Test 1 - 151-152", words: [
                    { word: "premier", definition: "hàng đầu, tốt nhất", example: "" },
                    { word: "spaces", definition: "các không gian", example: "" },
                    { word: "a hill", definition: "một ngọn đồi", example: "" },
                    { word: "expansive", definition: "rộng lớn, bao quát", example: "" },
                    { word: "sweeping", definition: "rộng lớn, bao quát (thường dùng với tầm nhìn)", example: "" },
                    { word: "adjacent", definition: "liền kề, gần kề", example: "" },
                    { word: "botanical", definition: "thuộc về thực vật, thực vật học", example: "" },
                    { word: "renovation", definition: "sự cải tạo, nâng cấp", example: "" },
                    { word: "accommodate", definition: "chứa đựng, đáp ứng", example: "" },
                    { word: "guests", definition: "khách mời", example: "" },
                    { word: "receptions", definition: "tiệc chiêu đãi", example: "" },
                    { word: "office parties", definition: "tiệc văn phòng", example: "" },
                    { word: "panel", definition: "thuộc về hội thảo, diễn đàn", example: "" },
                    { word: "presentations", definition: "bài thuyết trình", example: "" },
                    { word: "marble", definition: "làm bằng đá cẩm thạch", example: "" },
                    { word: "floors", definition: "sàn nhà", example: "" },
                    { word: "cathedral", definition: "thuộc về nhà thờ lớn", example: "" },
                    { word: "ceiling", definition: "trần nhà", example: "" },
                    { word: "stunning", definition: "tuyệt đẹp, gây ấn tượng", example: "" },
                    { word: "artwork", definition: "tác phẩm nghệ thuật", example: "" },
                    { word: "ideal", definition: "lý tưởng", example: "" },
                    { word: "gathering", definition: "sự tụ họp, buổi gặp mặt", example: "" },
                    { word: "on-site", definition: "tại chỗ", example: "" },
                    { word: "restaurant", definition: "nhà hàng", example: "" },
                    { word: "caters", definition: "phục vụ (thức ăn, đồ uống)", example: "" },
                    { word: "operates", definition: "hoạt động, điều hành", example: "" },
                    { word: "dietary", definition: "thuộc về chế độ ăn uống", example: "" },
                    { word: "revolutionized", definition: "cách mạng hóa, thay đổi hoàn toàn", example: "" },
                    { word: "local", definition: "địa phương", example: "" },
                    { word: "scene", definition: "bối cảnh, khu vực", example: "" },
                    { word: "residents", definition: "cư dân", example: "" },
                    { word: "reserve", definition: "đặt trước, giữ chỗ", example: "" },
                    { word: "reservation", definition: "sự đặt trước, sự giữ chỗ", example: "" },
                    { word: "snores", definition: "ngủ ngáy", example: "" },
                    { word: "solely", definition: "duy nhất, chỉ", example: "" },
                    { word: "corporate", definition: "thuộc về công ty", example: "" },
                    { word: "international", definition: "quốc tế", example: "" },
                    { word: "limited", definition: "hạn chế", example: "" },
                    { word: "offers", definition: "cung cấp", example: "" },
                    { word: "funded", definition: "được tài trợ", example: "" },
                    { word: "charitable", definition: "từ thiện", example: "" },
                    { word: "popular", definition: "phổ biến, nổi tiếng", example: "" }
                ]
            },
            {
                id: 8, title: "Test 1 - 153-157", words: [
                    { word: "almost", definition: "hầu như, gần như", example: "" },
                    { word: "field measurements", definition: "các phép đo thực địa", example: "" },
                    { word: "afraid", definition: "sợ, e rằng", example: "" },
                    { word: "without", definition: "không có", example: "" },
                    { word: "site coordinates", definition: "tọa độ địa điểm", example: "" },
                    { word: "correct", definition: "chính xác", example: "" },
                    { word: "double-checked", definition: "đã kiểm tra lại một lần nữa", example: "" },
                    { word: "season", definition: "của mùa vụ", example: "" },
                    { word: "excellent", definition: "tuyệt vời", example: "" },
                    { word: "weather", definition: "thời tiết", example: "" },
                    { word: "yielded", definition: "đã mang lại, đã tạo ra", example: "" },
                    { word: "substantial", definition: "đáng kể", example: "" },
                    { word: "harvest", definition: "vụ mùa, thu hoạch", example: "" },
                    { word: "growers", definition: "người trồng trọt", example: "" },
                    { word: "buyers", definition: "người mua", example: "" },
                    { word: "wishing", definition: "mong muốn", example: "" },
                    { word: "donate", definition: "quyên góp, hiến tặng", example: "" },
                    { word: "surplus", definition: "số dư, thặng dư", example: "" },
                    { word: "produce", definition: "nông sản", example: "" },
                    { word: "community", definition: "cộng đồng", example: "" },
                    { word: "organizations", definition: "các tổ chức", example: "" },
                    { word: "list", definition: "danh sách", example: "" },
                    { word: "instead", definition: "thay vào đó", example: "" },
                    { word: "contact", definition: "liên hệ", example: "" },
                    { word: "reach out", definition: "tiếp cận, liên hệ", example: "" },
                    { word: "independent", definition: "độc lập", example: "" },
                    { word: "truck drivers", definition: "các tài xế xe tải", example: "" },
                    { word: "kindly", definition: "vui lòng, tử tế", example: "" },
                    { word: "volunteered", definition: "đã tình nguyện", example: "" },
                    { word: "transport", definition: "vận chuyển", example: "" },
                    { word: "distribute", definition: "phân phát, phân phối", example: "" },
                    { word: "vetted", definition: "đã được kiểm tra, xác minh", example: "" },
                    { word: "insights", definition: "sự hiểu biết sâu sắc", example: "" },
                    { word: "related", definition: "liên quan", example: "" },
                    { word: "region", definition: "vùng, khu vực", example: "" },
                    { word: "caused", definition: "đã gây ra", example: "" },
                    { word: "frequently", definition: "thường xuyên", example: "" },
                    { word: "beneficial", definition: "có lợi", example: "" }
                ]
            },
            {
                id: 9, title: "Test 1 - 158-160", words: [
                    { word: "delighted", definition: "rất vui mừng, hài lòng", example: "" },
                    { word: "joining", definition: "đang tham gia", example: "" },
                    { word: "adhere", definition: "tuân thủ, tuân theo", example: "" },
                    { word: "following", definition: "sau đây, tiếp theo", example: "" },
                    { word: "guidelines", definition: "các hướng dẫn", example: "" },
                    { word: "ensure", definition: "đảm bảo", example: "" },
                    { word: "attendees", definition: "những người tham dự", example: "" },
                    { word: "enjoyable", definition: "thú vị, có thể tận hưởng", example: "" },
                    { word: "venue", definition: "địa điểm", example: "" },
                    { word: "electronic", definition: "điện tử", example: "" },
                    { word: "devices", definition: "các thiết bị", example: "" },
                    { word: "silent mode", definition: "chế độ im lặng", example: "" },
                    { word: "distracting", definition: "gây xao lãng", example: "" },
                    { word: "performers", definition: "các nghệ sĩ biểu diễn", example: "" },
                    { word: "fellow", definition: "cùng, đồng", example: "" },
                    { word: "audience", definition: "khán giả", example: "" },
                    { word: "members", definition: "thành viên", example: "" },
                    { word: "allowed", definition: "được phép", example: "" },
                    { word: "recording", definition: "sự ghi âm, ghi hình", example: "" },
                    { word: "aisles", definition: "lối đi", example: "" },
                    { word: "pose", definition: "gây ra, đặt ra", example: "" },
                    { word: "concern", definition: "mối quan ngại", example: "" },
                    { word: "fit", definition: "vừa vặn", example: "" },
                    { word: "properly", definition: "đúng cách", example: "" },
                    { word: "storing", definition: "đang cất giữ", example: "" },
                    { word: "locker", definition: "tủ khóa", example: "" },
                    { word: "attendants", definition: "người phục vụ", example: "" },
                    { word: "gladly", definition: "một cách vui vẻ, sẵn lòng", example: "" },
                    { word: "assist", definition: "giúp đỡ", example: "" },
                    { word: "cooperation", definition: "sự hợp tác", example: "" },
                    { word: "concert hall", definition: "phòng hòa nhạc", example: "" },
                    { word: "post office", definition: "bưu điện", example: "" },
                    { word: "locked", definition: "được khóa", example: "" },
                    { word: "inspected", definition: "đã được kiểm tra", example: "" }
                ]
            },
            {
                id: 10, title: "Test 1 - 161-164", words: [
                    { word: "selecting", definition: "đang chọn", example: "" },
                    { word: "baked", definition: "đã được nướng", example: "" },
                    { word: "goods", definition: "hàng hóa", example: "" },
                    { word: "conference", definition: "hội nghị", example: "" },
                    { word: "chosen", definition: "đã chọn", example: "" },
                    { word: "in a row", definition: "liên tiếp", example: "" },
                    { word: "custom-baked", definition: "được nướng theo yêu cầu", example: "" },
                    { word: "multilayer", definition: "nhiều lớp", example: "" },
                    { word: "billed", definition: "đã được lập hóa đơn", example: "" },
                    { word: "attached", definition: "được đính kèm", example: "" },
                    { word: "form", definition: "mẫu đơn", example: "" },
                    { word: "return", definition: "gửi lại", example: "" },
                    { word: "within", definition: "trong vòng", example: "" },
                    { word: "Regarding", definition: "liên quan đến, về", example: "" },
                    { word: "pastry", definition: "bánh ngọt", example: "" },
                    { word: "produce", definition: "sản xuất, làm ra", example: "" },
                    { word: "specifications", definition: "các thông số kỹ thuật", example: "" },
                    { word: "recipe", definition: "công thức", example: "" },
                    { word: "fresh", definition: "tươi", example: "" },
                    { word: "raspberry", definition: "quả mâm xôi", example: "" },
                    { word: "judged", definition: "đã đánh giá, đã phán xét", example: "" },
                    { word: "delectable", definition: "ngon, hấp dẫn", example: "" },
                    { word: "treat", definition: "món ăn đặc biệt", example: "" },
                    { word: "concerns", definition: "các mối quan ngại", example: "" },
                    { word: "value", definition: "đánh giá cao", example: "" },
                    { word: "request", definition: "yêu cầu", example: "" },
                    { word: "confirmation", definition: "sự xác nhận", example: "" },
                    { word: "adjust", definition: "điều chỉnh", example: "" },
                    { word: "delivery", definition: "sự giao hàng", example: "" },
                    { word: "announce", definition: "thông báo", example: "" },
                    { word: "expansion", definition: "sự mở rộng", example: "" },
                    { word: "promote", definition: "quảng bá", example: "" },
                    { word: "dessert", definition: "món tráng miệng", example: "" },
                    { word: "products", definition: "các sản phẩm", example: "" },
                    { word: "professional", definition: "chuyên nghiệp", example: "" },
                    { word: "award", definition: "giải thưởng", example: "" },
                    { word: "client", definition: "khách hàng", example: "" },
                    { word: "positive", definition: "tích cực", example: "" },
                    { word: "recommendation", definition: "sự giới thiệu, đề xuất", example: "" },
                    { word: "best-selling", definition: "bán chạy nhất", example: "" },
                    { word: "annually", definition: "hàng năm", example: "" },
                    { word: "expensive", definition: "đắt tiền", example: "" },
                    { word: "flavor", definition: "hương vị", example: "" },
                    { word: "combination", definition: "sự kết hợp", example: "" }
                ]
            },
            {
                id: 11, title: "Test 1 - 165-167", words: [
                    { word: "dishwasher", definition: "máy rửa bát", example: "" },
                    { word: "remodeling", definition: "đang sửa sang", example: "" },
                    { word: "kitchen", definition: "nhà bếp", example: "" },
                    { word: "had", definition: "đã có", example: "" },
                    { word: "compact", definition: "nhỏ gọn", example: "" },
                    { word: "choice", definition: "sự lựa chọn", example: "" },
                    { word: "pricier", definition: "đắt hơn", example: "" },
                    { word: "models", definition: "các mẫu", example: "" },
                    { word: "extra", definition: "thêm", example: "" },
                    { word: "decided", definition: "đã quyết định", example: "" },
                    { word: "decision", definition: "quyết định", example: "" },
                    { word: "sparkling", definition: "lấp lánh, sáng bóng", example: "" },
                    { word: "clean", definition: "sạch", example: "" },
                    { word: "designed", definition: "được thiết kế", example: "" },
                    { word: "efficiently", definition: "một cách hiệu quả", example: "" },
                    { word: "important", definition: "quan trọng", example: "" },
                    { word: "available", definition: "có sẵn", example: "" },
                    { word: "rated", definition: "được đánh giá", example: "" },
                    { word: "brand", definition: "nhãn hiệu", example: "" },
                    { word: "operating", definition: "đang hoạt động", example: "" },
                    { word: "recently", definition: "gần đây", example: "" },
                    { word: "bought", definition: "đã mua", example: "" },
                    { word: "remodeled", definition: "đã sửa sang", example: "" },
                    { word: "professionally", definition: "một cách chuyên nghiệp", example: "" }
                ]
            },
            {
                id: 12, title: "Test 1 - 168-171", words: [
                    { word: "employs", definition: "tuyển dụng", example: "" },
                    { word: "world", definition: "thế giới", example: "" },
                    { word: "growing", definition: "đang phát triển", example: "" },
                    { word: "fast", definition: "nhanh", example: "" },
                    { word: "positions", definition: "các vị trí (công việc)", example: "" },
                    { word: "background", definition: "nền tảng, kinh nghiệm", example: "" },
                    { word: "probably", definition: "có lẽ", example: "" },
                    { word: "employees", definition: "các nhân viên", example: "" },
                    { word: "perks", definition: "các phúc lợi", example: "" },
                    { word: "discount", definition: "chiết khấu, giảm giá", example: "" },
                    { word: "enables", definition: "cho phép", example: "" },
                    { word: "destinations", definition: "các điểm đến", example: "" },
                    { word: "fraction", definition: "một phần nhỏ", example: "" },
                    { word: "upward", definition: "hướng lên", example: "" },
                    { word: "global", definition: "toàn cầu", example: "" },
                    { word: "mobility", definition: "sự di chuyển, tính di động", example: "" },
                    { word: "tuition", definition: "học phí", example: "" },
                    { word: "reimbursement", definition: "sự hoàn trả", example: "" },
                    { word: "mentorship", definition: "sự cố vấn", example: "" },
                    { word: "generous", definition: "hào phóng", example: "" },
                    { word: "compensation", definition: "sự đền bù, bồi thường", example: "" },
                    { word: "work-life", definition: "công việc và cuộc sống", example: "" },
                    { word: "balance", definition: "sự cân bằng", example: "" },
                    { word: "no wonder", definition: "chẳng có gì đáng ngạc nhiên", example: "" },
                    { word: "job seekers", definition: "người tìm việc", example: "" },
                    { word: "educational", definition: "thuộc về giáo dục", example: "" },
                    { word: "expenses", definition: "chi phí", example: "" },
                    { word: "opportunities", definition: "các cơ hội", example: "" },
                    { word: "paid", definition: "được trả lương", example: "" },
                    { word: "days", definition: "các ngày", example: "" },
                    { word: "off", definition: "nghỉ", example: "" },
                    { word: "merge", definition: "sáp nhập", example: "" },
                    { word: "praised", definition: "đã được ca ngợi", example: "" },
                    { word: "trade", definition: "thuộc về ngành, thương mại", example: "" },
                    { word: "publication", definition: "ấn phẩm", example: "" },
                    { word: "replaced", definition: "đã thay thế", example: "" },
                    { word: "openings", definition: "các vị trí trống", example: "" },
                    { word: "broad", definition: "rộng", example: "" },
                    { word: "range", definition: "phạm vi", example: "" },
                    { word: "skill", definition: "kỹ năng", example: "" },
                    { word: "sets", definition: "các bộ, nhóm", example: "" }
                ]
            },
            {
                id: 13, title: "Test 1 - 172-175", words: [
                    { word: "highlight", definition: "làm nổi bật", example: "" },
                    { word: "multiple", definition: "nhiều", example: "" },
                    { word: "locations", definition: "các địa điểm", example: "" },
                    { word: "attend", definition: "tham dự", example: "" },
                    { word: "smoothly", definition: "một cách suôn sẻ", example: "" },
                    { word: "notified", definition: "đã được thông báo", example: "" },
                    { word: "upcoming", definition: "sắp tới", example: "" },
                    { word: "amateur", definition: "nghiệp dư", example: "" },
                    { word: "athlete", definition: "vận động viên", example: "" },
                    { word: "product", definition: "sản phẩm", example: "" },
                    { word: "researcher", definition: "nhà nghiên cứu", example: "" },
                    { word: "advertising", definition: "quảng cáo", example: "" },
                    { word: "executive", definition: "giám đốc điều hành", example: "" },
                    { word: "line", definition: "dòng, loại", example: "" },
                    { word: "partner", definition: "đối tác", example: "" },
                    { word: "on track", definition: "đúng tiến độ", example: "" },
                    { word: "missing", definition: "thiếu", example: "" },
                    { word: "elements", definition: "các yếu tố", example: "" },
                    { word: "mainly", definition: "chủ yếu", example: "" },
                    { word: "development", definition: "sự phát triển", example: "" },
                    { word: "overlook", definition: "bỏ qua, quên", example: "" },
                    { word: "expedite", definition: "xúc tiến, đẩy nhanh", example: "" },
                    { word: "summary", definition: "bản tóm tắt", example: "" },
                    { word: "assuming", definition: "giả sử rằng", example: "" },
                    { word: "incorporate", definition: "kết hợp", example: "" },
                    { word: "findings", definition: "các phát hiện", example: "" },
                    { word: "trial", definition: "thử nghiệm", example: "" },
                    { word: "necessary", definition: "cần thiết", example: "" }
                ]
            }
        ]
    }
];

export const getVocabularyPart = (partId: number): VocabularyPart | null => {
    return vocabularyData.find(part => part.id === partId) || null;
}

export const getVocabularyTest = (partId: number, testId: number): VocabularyTest | null => {
    const part = getVocabularyPart(partId);
    return part?.tests.find(test => test.id === testId) || null;
}