import { VocabularyPart, VocabItem } from '../../types';

const test1_176_185_words: VocabItem[] = [
    { word: "establishment", definition: "sự thành lập, cơ sở", example: "" },
    { word: "variety", definition: "sự đa dạng, chủng loại", example: "" },
    { word: "option", definition: "sự lựa chọn, tùy chọn", example: "" },
    { word: "ideal", definition: "lý tưởng, hoàn hảo", example: "" },
    { word: "fewer", definition: "ít hơn (dùng cho danh từ đếm được)", example: "" },
    { word: "transactions", definition: "giao dịch", example: "" },
    { word: "frequently", definition: "thường xuyên", example: "" },
    { word: "customers", definition: "khách hàng", example: "" },
    { word: "attractive", definition: "hấp dẫn, thu hút", example: "" },
    { word: "interest", definition: "tiền lãi, sự quan tâm", example: "" },
    { word: "savings", definition: "tiền tiết kiệm", example: "" },
    { word: "teenager", definition: "thanh thiếu niên", example: "" },
    { word: "involve", definition: "liên quan, bao gồm", example: "" },
    { word: "initiate", definition: "bắt đầu, khởi xướng", example: "" },
    { word: "registration", definition: "sự đăng ký", example: "" },
    { word: "drop by", definition: "ghé qua, tạt qua", example: "" },
    { word: "commercial", definition: "Thương mại, thuộc về thương mại", example: "" },
    { word: "comply", definition: "Tuân thủ, chấp hành", example: "" },
    { word: "regulations", definition: "Quy định, điều lệ", example: "" },
    { word: "restrictions", definition: "Sự hạn chế, giới hạn", example: "" },
    { word: "individual", definition: "Cá nhân, riêng lẻ", example: "" },
    { word: "complete", definition: "Hoàn chỉnh, đầy đủ", example: "" },
    { word: "enforcement", definition: "Sự thi hành, sự cưỡng chế", example: "" },
    { word: "load", definition: "Tải trọng, hàng hóa (trên xe)", example: "" },
    { word: "limits", definition: "Giới hạn, mức tối đa", example: "" },
    { word: "weigh", definition: "Cân (xác định trọng lượng)", example: "" },
    { word: "pull over", definition: "Tấp vào lề, dừng xe (ở lề đường)", example: "" },
    { word: "conduct", definition: "Tiến hành, thực hiện", example: "" },
    { word: "visual", definition: "Thuộc về thị giác, bằng mắt", example: "" },
    { word: "inspections", definition: "Sự kiểm tra, thanh tra", example: "" },
    { word: "ensure", definition: "Đảm bảo, chắc chắn", example: "" },
    { word: "measures", definition: "Biện pháp, phương sách", example: "" },
    { word: "determines", definition: "Xác định, quyết định", example: "" },
    { word: "sensors", definition: "Cảm biến, bộ cảm ứng", example: "" },
    { word: "installed", definition: "Lắp đặt, cài đặt", example: "" },
    { word: "blinks", definition: "Nháy mắt, chớp nháy (đèn)", example: "" },
    { word: "fined", definition: "Bị phạt tiền", example: "" },
    { word: "traffic jams", definition: "Tắc đường, kẹt xe", example: "" },
    { word: "on account of", definition: "Bởi vì, do", example: "" },
    { word: "numerous", definition: "Nhiều, vô số", example: "" },
    { word: "accurately", definition: "Một cách chính xác", example: "" },
    { word: "suffer", definition: "Chịu đựng, trải qua (điều tồi tệ)", example: "" },
    { word: "signify", definition: "Biểu thị", example: "" },
];

const test1_186_200_words: VocabItem[] = [
    { word: "preserved", definition: "bảo tồn, giữ gìn", example: "" },
    { word: "appeared", definition: "đã xuất hiện, dường như", example: "" },
    { word: "complimentary", definition: "miễn phí, ca ngợi", example: "" },
    { word: "Features", definition: "có tính năng, nổi bật", example: "" },
    { word: "finest", definition: "tốt nhất, chất lượng cao nhất", example: "" },
    { word: "dining", definition: "việc ăn uống, dùng bữa", example: "" },
    { word: "specialties", definition: "đặc sản, món đặc trưng", example: "" },
    { word: "pier", definition: "cầu tàu, bến tàu", example: "" },
    { word: "Decorated", definition: "được trang trí, được trang hoàng", example: "" },
    { word: "ranch", definition: "trang trại (chăn nuôi gia súc)", example: "" },
    { word: "region", definition: "vùng, khu vực", example: "" },
    { word: "distracted", definition: "bị phân tâm, mất tập trung", example: "" },
    { word: "casual", definition: "bình thường, không trang trọng", example: "" },
    { word: "atmosphere", definition: "bầu không khí, môi trường", example: "" },
    { word: "incredible", definition: "không thể tin được, tuyệt vời", example: "" },
    { word: "hearty", definition: "thịnh soạn, ấm cúng, chân thành", example: "" },
    { word: "must", definition: "điều bắt buộc, sự cần thiết", example: "" },
    { word: "taste", definition: "vị, sự nếm; khiếu thẩm mỹ", example: "" },
    { word: "establishment", definition: "cơ sở, sự thành lập", example: "" },
    { word: "dining", definition: "Ăn uống, dùng bữa", example: "" },
    { word: "down", definition: "Xuống, phía dưới, dọc theo", example: "" },
    { word: "waterfront", definition: "Bờ sông, bờ hồ, bờ biển (khu vực ven nước)", example: "" },
    { word: "return", definition: "Trở về, quay lại", example: "" },
    { word: "excursion", definition: "Chuyến đi chơi, chuyến tham quan ngắn", example: "" },
    { word: "label", definition: "Nhãn, nhãn mác", example: "" },
    { word: "misspelling", definition: "Lỗi chính tả", example: "" },
    { word: "rectified", definition: "Đã sửa, đã chỉnh sửa", example: "" },
    { word: "charges", definition: "Tính phí, đòi tiền", example: "" },
    { word: "affix", definition: "Dán, đính kèm, gắn vào", example: "" },
    { word: "emergency", definition: "Tình trạng khẩn cấp", example: "" },
    { word: "solve", definition: "Giải quyết, hóa giải", example: "" },
    { word: "reduce", definition: "Giảm, cắt giảm", example: "" },
    { word: "handle", definition: "Xử lý, giải quyết", example: "" },
    { word: "Ingredients", definition: "Thành phần", example: "" },
    { word: "Manufactured", definition: "Đã sản xuất, đã chế tạo", example: "" },
    { word: "Distributed", definition: "Đã phân phối", example: "" },
    { word: "amount", definition: "Số lượng", example: "" },
    { word: "submissions", definition: "Các bài nộp, hồ sơ dự thầu", example: "" },
    { word: "narrowed", definition: "Thu hẹp, giới hạn lại", example: "" },
    { word: "impressive", definition: "Ấn tượng, gây cảm phục", example: "" },
    { word: "in person", definition: "Trực tiếp, đích thân", example: "" },
    { word: "matter", definition: "Vấn đề, sự việc", example: "" },
    { word: "redesign", definition: "Thiết kế lại", example: "" },
    { word: "individuals", definition: "Cá nhân", example: "" },
    { word: "measurements", definition: "Số đo, kích thước", example: "" },
    { word: "fine dining", definition: "Ẩm thực cao cấp", example: "" },
    { word: "diners", definition: "Thực khách", example: "" },
    { word: "imagining", definition: "Tưởng tượng, hình dung", example: "" },
    { word: "exclusive", definition: "Độc quyền, riêng biệt", example: "" },
    { word: "dishes", definition: "Món ăn", example: "" },
    { word: "bid", definition: "Đấu thầu; trả giá", example: "" },
];


export const readingPart7IntenseVocabularyData: VocabularyPart = {
    id: 9,
    title: "Reading Part 7 nâng - Lớp cấp tốc",
    description: "Vocabulary from advanced TOEIC Reading Part 7 passages for intensive classes.",
    tests: [
        { id: 901, title: "Test 1 (176-185)", words: test1_176_185_words },
        { id: 902, title: "Test 1 (186-200)", words: test1_186_200_words },
    ]
};