import { VocabularyPart, VocabItem } from '../../types';

const test1_176_185_words: VocabItem[] = [
    { word: "establishment", definition: "sự thành lập, cơ sở", example: "" },
    { word: "variety", definition: "sự đa dạng, chủng loại", example: "" },
    { word: "option", definition: "sự lựa chọn, tùy chọn", example: "" },
    { word: "ideal", definition: "lý tưởng, hoàn hảo", example: "" },
    { word: "fewer", definition: "ít hơn (dùng cho danh từ đếm được)", example: "" },
    { word: "transactions", definition: "giao dịch", example: "" },
    { word: "frequently", definition: "thường xuyên", example: "" },
    { word: "customers", definition: "khách hàng", example: "" },
    { word: "attractive", definition: "hấp dẫn, thu hút", example: "" },
    { word: "interest", definition: "tiền lãi, sự quan tâm", example: "" },
    { word: "savings", definition: "tiền tiết kiệm", example: "" },
    { word: "teenager", definition: "thanh thiếu niên", example: "" },
    { word: "involve", definition: "liên quan, bao gồm", example: "" },
    { word: "initiate", definition: "bắt đầu, khởi xướng", example: "" },
    { word: "registration", definition: "sự đăng ký", example: "" },
    { word: "drop by", definition: "ghé qua, tạt qua", example: "" },
    { word: "commercial", definition: "Thương mại, thuộc về thương mại", example: "" },
    { word: "comply", definition: "Tuân thủ, chấp hành", example: "" },
    { word: "regulations", definition: "Quy định, điều lệ", example: "" },
    { word: "restrictions", definition: "Sự hạn chế, giới hạn", example: "" },
    { word: "individual", definition: "Cá nhân, riêng lẻ", example: "" },
    { word: "complete", definition: "Hoàn chỉnh, đầy đủ", example: "" },
    { word: "enforcement", definition: "Sự thi hành, sự cưỡng chế", example: "" },
    { word: "load", definition: "Tải trọng, hàng hóa (trên xe)", example: "" },
    { word: "limits", definition: "Giới hạn, mức tối đa", example: "" },
    { word: "weigh", definition: "Cân (xác định trọng lượng)", example: "" },
    { word: "pull over", definition: "Tấp vào lề, dừng xe (ở lề đường)", example: "" },
    { word: "conduct", definition: "Tiến hành, thực hiện", example: "" },
    { word: "visual", definition: "Thuộc về thị giác, bằng mắt", example: "" },
    { word: "inspections", definition: "Sự kiểm tra, thanh tra", example: "" },
    { word: "ensure", definition: "Đảm bảo, chắc chắn", example: "" },
    { word: "measures", definition: "Biện pháp, phương sách", example: "" },
    { word: "determines", definition: "Xác định, quyết định", example: "" },
    { word: "sensors", definition: "Cảm biến, bộ cảm ứng", example: "" },
    { word: "installed", definition: "Lắp đặt, cài đặt", example: "" },
    { word: "blinks", definition: "Nháy mắt, chớp nháy (đèn)", example: "" },
    { word: "fined", definition: "Bị phạt tiền", example: "" },
    { word: "traffic jams", definition: "Tắc đường, kẹt xe", example: "" },
    { word: "on account of", definition: "Bởi vì, do", example: "" },
    { word: "numerous", definition: "Nhiều, vô số", example: "" },
    { word: "accurately", definition: "Một cách chính xác", example: "" },
    { word: "suffer", definition: "Chịu đựng, trải qua (điều tồi tệ)", example: "" },
    { word: "signify", definition: "Biểu thị", example: "" },
];

const test1_186_200_words: VocabItem[] = [
    { word: "preserved", definition: "bảo tồn, giữ gìn", example: "" },
    { word: "appeared", definition: "đã xuất hiện, dường như", example: "" },
    { word: "complimentary", definition: "miễn phí, ca ngợi", example: "" },
    { word: "Features", definition: "có tính năng, nổi bật", example: "" },
    { word: "finest", definition: "tốt nhất, chất lượng cao nhất", example: "" },
    { word: "dining", definition: "việc ăn uống, dùng bữa", example: "" },
    { word: "specialties", definition: "đặc sản, món đặc trưng", example: "" },
    { word: "pier", definition: "cầu tàu, bến tàu", example: "" },
    { word: "Decorated", definition: "được trang trí, được trang hoàng", example: "" },
    { word: "ranch", definition: "trang trại (chăn nuôi gia súc)", example: "" },
    { word: "region", definition: "vùng, khu vực", example: "" },
    { word: "distracted", definition: "bị phân tâm, mất tập trung", example: "" },
    { word: "casual", definition: "bình thường, không trang trọng", example: "" },
    { word: "atmosphere", definition: "bầu không khí, môi trường", example: "" },
    { word: "incredible", definition: "không thể tin được, tuyệt vời", example: "" },
    { word: "hearty", definition: "thịnh soạn, ấm cúng, chân thành", example: "" },
    { word: "must", definition: "điều bắt buộc, sự cần thiết", example: "" },
    { word: "taste", definition: "vị, sự nếm; khiếu thẩm mỹ", example: "" },
    { word: "establishment", definition: "cơ sở, sự thành lập", example: "" },
    { word: "down", definition: "Xuống, phía dưới, dọc theo", example: "" },
    { word: "waterfront", definition: "Bờ sông, bờ hồ, bờ biển (khu vực ven nước)", example: "" },
    { word: "return", definition: "Trở về, quay lại", example: "" },
    { word: "excursion", definition: "Chuyến đi chơi, chuyến tham quan ngắn", example: "" },
    { word: "label", definition: "Nhãn, nhãn mác", example: "" },
    { word: "misspelling", definition: "Lỗi chính tả", example: "" },
    { word: "rectified", definition: "Đã sửa, đã chỉnh sửa", example: "" },
    { word: "charges", definition: "Tính phí, đòi tiền", example: "" },
    { word: "affix", definition: "Dán, đính kèm, gắn vào", example: "" },
    { word: "emergency", definition: "Tình trạng khẩn cấp", example: "" },
    { word: "solve", definition: "Giải quyết, hóa giải", example: "" },
    { word: "reduce", definition: "Giảm, cắt giảm", example: "" },
    { word: "handle", definition: "Xử lý, giải quyết", example: "" },
    { word: "Ingredients", definition: "Thành phần", example: "" },
    { word: "Manufactured", definition: "Đã sản xuất, đã chế tạo", example: "" },
    { word: "Distributed", definition: "Đã phân phối", example: "" },
    { word: "amount", definition: "Số lượng", example: "" },
    { word: "submissions", definition: "Các bài nộp, hồ sơ dự thầu", example: "" },
    { word: "narrowed", definition: "Thu hẹp, giới hạn lại", example: "" },
    { word: "impressive", definition: "Ấn tượng, gây cảm phục", example: "" },
    { word: "in person", definition: "Trực tiếp, đích thân", example: "" },
    { word: "matter", definition: "Vấn đề, sự việc", example: "" },
    { word: "redesign", definition: "Thiết kế lại", example: "" },
    { word: "individuals", definition: "Cá nhân", example: "" },
    { word: "measurements", definition: "Số đo, kích thước", example: "" },
    { word: "fine dining", definition: "Ẩm thực cao cấp", example: "" },
    { word: "diners", definition: "Thực khách", example: "" },
    { word: "imagining", definition: "Tưởng tượng, hình dung", example: "" },
    { word: "exclusive", definition: "Độc quyền, riêng biệt", example: "" },
    { word: "dishes", definition: "Món ăn", example: "" },
    { word: "bid", definition: "Đấu thầu; trả giá", example: "" },
];

const test2_176_185_words: VocabItem[] = [
    { word: "pleasure", definition: "Niềm vinh dự, niềm vui, sự hân hạnh", example: "" },
    { word: "proposal", definition: "Đề xuất, kiến nghị", example: "" },
    { word: "Impressed", definition: "Bị ấn tượng, thán phục", example: "" },
    { word: "cover issues", definition: "Giải quyết/đề cập các vấn đề", example: "" },
    { word: "releasing", definition: "Giải ngân, cấp phát", example: "" },
    { word: "engaging", definition: "Tham gia, bắt đầu (dự án)", example: "" },
    { word: "intend", definition: "Dự định, có ý định", example: "" },
    { word: "arrangements", definition: "Sự sắp xếp, kế hoạch", example: "" },
    { word: "elected", definition: "Được bầu cử", example: "" },
    { word: "undergoing", definition: "Đang trải qua, đang được tiến hành", example: "" },
    { word: "platforms", definition: "Cương lĩnh, chương trình hành động", example: "" },
    { word: "livable", definition: "Đáng sống, có thể ở được", example: "" },
    { word: "enhancements", definition: "Sự cải thiện, nâng cấp", example: "" },
    { word: "infrastructure", definition: "Cơ sở hạ tầng", example: "" },
    { word: "wider variety", definition: "Đa dạng hơn, nhiều loại hơn", example: "" },
    { word: "emphasized", definition: "Nhấn mạnh, làm nổi bật", example: "" },
    { word: "clearly evident", definition: "Rõ ràng, hiển nhiên", example: "" },
    { word: "flocking", definition: "Tụ tập, đổ xô đến", example: "" },
    { word: "benefitted", definition: "Được hưởng lợi", example: "" },
    { word: "city hall", definition: "Tòa thị chính", example: "" },
    { word: "lending", definition: "Cho vay, cho mượn", example: "" },
    { word: "appreciate", definition: "Đánh giá cao, cảm kích", example: "" },
    { word: "inform", definition: "Thông báo, cho biết", example: "" },
    { word: "containing", definition: "Chứa đựng, bao gồm", example: "" },
    { word: "importing", definition: "Nhập khẩu", example: "" },
    { word: "college", definition: "Trường đại học/cao đẳng", example: "" },
    { word: "pass along", definition: "Chuyển tiếp, truyền lại", example: "" },
    { word: "get in touch", definition: "Liên lạc, giữ liên lạc", example: "" },
    { word: "reached", definition: "Liên lạc, đến, đạt tới", example: "" },
    { word: "wound up", definition: "Cuối cùng thì (kết thúc ở một tình huống/địa điểm bất ngờ)", example: "" },
    { word: "diploma", definition: "Bằng cấp (sau khi tốt nghiệp)", example: "" },
    { word: "engineer", definition: "Kỹ sư", example: "" },
    { word: "decided", definition: "Quyết định", example: "" },
    { word: "main", definition: "Chính, chủ yếu", example: "" },
    { word: "disappointed", definition: "Thất vọng", example: "" },
    { word: "native land", definition: "Quê hương, xứ sở", example: "" },
    { word: "appropriately", definition: "Một cách thích hợp, hợp lý", example: "" },
    { word: "thoroughly", definition: "Hoàn toàn, kỹ lưỡng", example: "" },
    { word: "overcooked", definition: "Nấu quá chín", example: "" },
    { word: "exceptional", definition: "Nổi bật, xuất sắc", example: "" },
    { word: "authentic", definition: "Đúng kiểu, chính thống, xác thực", example: "" },
    { word: "title", definition: "Tiêu đề, danh hiệu", example: "" },
    { word: "acquainted", definition: "Quen biết", example: "" },
];

const test2_186_200_words: VocabItem[] = [
    { word: "strive", definition: "phấn đấu, cố gắng", example: "" },
    { word: "professional", definition: "chuyên nghiệp, thuộc về nghề nghiệp", example: "" },
    { word: "skills", definition: "kĩ năng", example: "" },
    { word: "endeavor", definition: "nỗ lực, sự cố gắng", example: "" },
    { word: "job-related", definition: "liên quan đến công việc", example: "" },
    { word: "accredited", definition: "được công nhận chính thức", example: "" },
    { word: "reimbursed", definition: "được hoàn lại tiền, được bồi hoàn", example: "" },
    { word: "determine", definition: "xác định, quyết định", example: "" },
    { word: "financial", definition: "(thuộc về) tài chính", example: "" },
    { word: "assistance", definition: "sự hỗ trợ, sự giúp đỡ", example: "" },
    { word: "obtained", definition: "đạt được, giành được", example: "" },
    { word: "textbooks", definition: "sách giáo khoa", example: "" },
    { word: "conducted", definition: "được tiến hành, được thực hiện", example: "" },
    { word: "enroll", definition: "đăng ký, ghi danh", example: "" },
    { word: "upcoming", definition: "sắp tới", example: "" },
    { word: "semester", definition: "học kỳ", example: "" },
    { word: "has yet to", definition: "vẫn chưa", example: "" },
    { word: "register", definition: "đăng ký", example: "" },
    { word: "alternative", definition: "thay thế, lựa chọn khác", example: "" },
    { word: "entirely", definition: "toàn bộ", example: "" },
    { word: "satisfied", definition: "Hài lòng, thoả mãn", example: "" },
    { word: "lighter", definition: "Nhạt hơn, nhẹ hơn", example: "" },
    { word: "play", definition: "Vở kịch", example: "" },
    { word: "bulk rate", definition: "Giá sỉ, giá số lượng lớn", example: "" },
    { word: "aside", definition: "Để qua một bên, sang một bên", example: "" },
    { word: "front row tickets", definition: "Vé hàng ghế đầu", example: "" },
    { word: "theater", definition: "Nhà hát, rạp hát", example: "" },
    { word: "brochure", definition: "Tờ quảng cáo, sách mỏng", example: "" },
    { word: "performance", definition: "Buổi biểu diễn, sự trình diễn", example: "" },
    { word: "included", definition: "Đã bao gồm, đã đính kèm", example: "" },
    { word: "look over", definition: "Xem qua, kiểm tra", example: "" },
    { word: "mistakes", definition: "Sai sót, lỗi", example: "" },
    { word: "wish", definition: "Mong muốn, muốn", example: "" },
    { word: "initiate", definition: "Bắt đầu, khởi xướng", example: "" },
    { word: "invoice", definition: "Hoá đơn", example: "" },
    { word: "pair", definition: "Một cặp, đôi", example: "" },
    { word: "cast", definition: "Dàn diễn viên", example: "" },
    { word: "altered", definition: "Đã thay đổi, đã sửa đổi", example: "" },
    { word: "vacation season", definition: "mùa nghỉ mát, mùa du lịch", example: "" },
    { word: "approaching", definition: "đang đến gần", example: "" },
    { word: "regarding", definition: "về việc, liên quan đến", example: "" },
    { word: "vital", definition: "quan trọng, thiết yếu", example: "" },
    { word: "immediate", definition: "trực tiếp, ngay lập tức", example: "" },
    { word: "supervisor", definition: "người giám sát, quản lý", example: "" },
    { word: "aware", definition: "ý thức, nhận thức", example: "" },
    { word: "time off", definition: "thời gian nghỉ ngơi", example: "" },
    { word: "granted", definition: "được chấp thuận, được cấp", example: "" },
    { word: "duties", definition: "nhiệm vụ, công việc", example: "" },
    { word: "coworker", definition: "đồng nghiệp", example: "" },
    { word: "handling", definition: "xử lý, giải quyết", example: "" },
    { word: "calendar", definition: "lịch", example: "" },
    { word: "replacements", definition: "người thay thế, vật thay thế", example: "" },
    { word: "cloth", definition: "vải", example: "" },
    { word: "several", definition: "một vài, một số", example: "" },
    { word: "bolts", definition: "cuộn (vải)", example: "" },
    { word: "fabric", definition: "vải, chất liệu", example: "" },
    { word: "rush", definition: "khẩn cấp, vội vã", example: "" },
    { word: "respond", definition: "phản hồi, trả lời", example: "" },
    { word: "textile", definition: "hàng dệt may, dệt", example: "" },
    { word: "tailor", definition: "thợ may; điều chỉnh", example: "" },
    { word: "multiple", definition: "nhiều, đa", example: "" },
    { word: "branches", definition: "chi nhánh, cành cây", example: "" },
    { word: "speak with", definition: "nói chuyện với", example: "" },
];

const test3_176_185_words: VocabItem[] = [
    { word: "eligible", definition: "Đủ điều kiện, hội đủ tiêu chuẩn", example: "" },
    { word: "adjacent", definition: "Kề bên, liền kề", example: "" },
    { word: "volunteers", definition: "Tình nguyện viên", example: "" },
    { word: "Jewelry", definition: "Trang sức, đồ trang sức", example: "" },
    { word: "forklift", definition: "Xe nâng", example: "" },
    { word: "personally", definition: "Cá nhân, đích thân", example: "" },
    { word: "previous", definition: "Trước, trước đây", example: "" },
    { word: "taken part", definition: "Đã tham gia", example: "" },
    { word: "reserve", definition: "Đặt trước, giữ chỗ", example: "" },
    { word: "freight elevator", definition: "Thang máy chở hàng", example: "" },
    { word: "guarantee", definition: "Bảo đảm, sự bảo đảm", example: "" },
    { word: "first-come, first-served", definition: "Ai đến trước được phục vụ trước", example: "" },
    { word: "event coordinator", definition: "Điều phối viên sự kiện", example: "" },
    { word: "regarding", definition: "Về, liên quan đến", example: "" },
    { word: "acceptance", definition: "Sự chấp nhận", example: "" },
    { word: "rejection", definition: "Sự từ chối", example: "" },
    { word: "rental fee", definition: "Phí thuê", example: "" },
    { word: "available", definition: "Có sẵn, rảnh", example: "" },
    { word: "booth", definition: "Gian hàng, buồng", example: "" },
    { word: "antique", definition: "Cổ, đồ cổ", example: "" },
    { word: "redo", definition: "Làm lại, trang trí lại", example: "" },
    { word: "interior", definition: "Nội thất, bên trong", example: "" },
    { word: "capable", definition: "Có khả năng, có năng lực", example: "" },
    { word: "realize", definition: "Nhận ra, hiểu ra", example: "" },
    { word: "avoid", definition: "Tránh, né tránh", example: "" },
    { word: "specializing", definition: "Chuyên môn hóa, chuyên về", example: "" },
    { word: "residential", definition: "Thuộc về khu dân cư, nhà ở", example: "" },
    { word: "simply", definition: "Đơn giản chỉ là, chỉ", example: "" },
    { word: "desire", definition: "Mong muốn, khao khát", example: "" },
    { word: "budget", definition: "Ngân sách", example: "" },
    { word: "tasteful", definition: "Có thẩm mỹ, trang nhã", example: "" },
    { word: "under no circumstances", definition: "Dưới bất kỳ trường hợp nào cũng không", example: "" },
    { word: "criteria", definition: "Tiêu chí, chuẩn mực", example: "" },
    { word: "unfortunately", definition: "Không may thay", example: "" },
    { word: "fulfill", definition: "Hoàn thành, đáp ứng", example: "" },
    { word: "conditions", definition: "Điều kiện, yêu cầu", example: "" },
    { word: "consumer", definition: "Khách hàng, người tiêu dùng", example: "" },
    { word: "recent", definition: "Gần đây", example: "" },
    { word: "expert", definition: "Chuyên gia, chuyên viên", example: "" },
    { word: "on staff", definition: "Là nhân viên chính thức, có trong đội ngũ", example: "" },
    { word: "staffers", definition: "Nhân viên, thành viên", example: "" },
    { word: "stock brokerage", definition: "Công ty môi giới chứng khoán", example: "" },
    { word: "quoted", definition: "Được báo giá, được định giá", example: "" },
    { word: "indicated", definition: "Chỉ ra, cho biết", example: "" },
    { word: "various", definition: "Khác nhau, đa dạng", example: "" },
];

const test3_186_200_words: VocabItem[] = [
    { word: "insurance", definition: "Bảo hiểm", example: "" },
    { word: "coverage", definition: "Phạm vi bảo hiểm", example: "" },
    { word: "extra", definition: "Thêm, phụ", example: "" },
    { word: "unlimited", definition: "Không giới hạn", example: "" },
    { word: "mileage", definition: "Quãng đường (tính bằng dặm)", example: "" },
    { word: "additional", definition: "Bổ sung, thêm", example: "" },
    { word: "valid", definition: "Hợp lệ, có giá trị", example: "" },
    { word: "pick up", definition: "Đón, nhận xe", example: "" },
    { word: "drop-off", definition: "Điểm trả xe, việc trả xe", example: "" },
    { word: "involved in", definition: "Liên quan đến, dính líu vào", example: "" },
    { word: "assessed", definition: "Đã được tính/định giá", example: "" },
    { word: "renter", definition: "Người thuê, bên thuê", example: "" },
    { word: "inquiries", definition: "Các câu hỏi, thắc mắc", example: "" },
    { word: "unauthorized", definition: "không được phép, trái phép", example: "" },
    { word: "permit", definition: "cho phép", example: "" },
    { word: "security guard", definition: "nhân viên bảo vệ", example: "" },
    { word: "on duty", definition: "đang làm nhiệm vụ, đang trực", example: "" },
    { word: "refuse", definition: "từ chối", example: "" },
    { word: "expecting", definition: "đang mong đợi, đang chờ", example: "" },
    { word: "usage", definition: "sự sử dụng, mức sử dụng", example: "" },
    { word: "adequate", definition: "đủ, đầy đủ", example: "" },
    { word: "detergent", definition: "chất tẩy rửa (bột giặt, nước rửa)", example: "" },
    { word: "manufacturer", definition: "nhà sản xuất", example: "" },
    { word: "press", definition: "nhấn, ấn", example: "" },
    { word: "with regard to", definition: "liên quan đến, về việc", example: "" },
    { word: "High-Capacity", definition: "sức chứa lớn", example: "" },
    { word: "Presoak", definition: "ngâm trước", example: "" },
    { word: "amounts", definition: "số lượng, lượng", example: "" },
    { word: "similar", definition: "tương tự, giống nhau", example: "" },
    { word: "own", definition: "sở hữu", example: "" },
    { word: "complex", definition: "khu phức hợp", example: "" },
    { word: "furnished", definition: "được trang bị nội thất", example: "" },
    { word: "tenant", definition: "người thuê nhà", example: "" },
    { word: "outstanding", definition: "xuất sắc, nổi bật", example: "" },
    { word: "loads", definition: "mẻ (giặt/rửa), tải trọng", example: "" },
    { word: "commented", definition: "bình luận, nhận xét", example: "" },
    { word: "barely", definition: "hầu như không, vừa đủ", example: "" },
    { word: "operating", definition: "đang vận hành, đang hoạt động", example: "" },
    { word: "units", definition: "căn hộ, đơn vị", example: "" },
    { word: "Activate", definition: "kích hoạt", example: "" },
    { word: "mechanism", definition: "cơ chế, bộ máy", example: "" },
    { word: "Utilize", definition: "tận dụng, sử dụng", example: "" },
    { word: "Rinse off", definition: "xả sạch, rửa trôi", example: "" },
    { word: "dirty", definition: "bẩn, dơ", example: "" },
    { word: "Malfunctioning", definition: "bị trục trặc, hỏng hóc", example: "" },
    { word: "extremely", definition: "Cực kỳ, vô cùng", example: "" },
    { word: "diners", definition: "Thực khách", example: "" },
    { word: "refunded", definition: "Đã hoàn tiền", example: "" },
    { word: "making up (for)", definition: "Bù đắp, đền bù (cho)", example: "" },
    { word: "bulk", definition: "Số lượng lớn, sỉ", example: "" },
    { word: "route", definition: "Tuyến đường, lộ trình", example: "" },
    { word: "dairy", definition: "(Sản phẩm từ) sữa", example: "" },
    { word: "combined", definition: "(Được) kết hợp, gộp lại", example: "" },
    { word: "charged", definition: "Đã tính phí", example: "" },
    { word: "reimburse", definition: "Hoàn lại, bồi hoàn", example: "" },
    { word: "on a regular basis", definition: "Một cách thường xuyên, đều đặn", example: "" },
    { word: "physical store", definition: "Cửa hàng vật lý, cửa hàng truyền thống", example: "" },
    { word: "point out", definition: "Chỉ ra, lưu ý", example: "" },
    { word: "overnight", definition: "Qua đêm, trong một đêm; nhanh chóng", example: "" },
];


export const readingPart7IntenseVocabularyData: VocabularyPart = {
    id: 9,
    title: "Reading Part 7 nâng - Lớp cấp tốc",
    description: "Vocabulary from advanced TOEIC Reading Part 7 passages for intensive classes.",
    tests: [
        { id: 901, title: "Test 1 (176-185)", words: test1_176_185_words },
        { id: 902, title: "Test 1 (186-200)", words: test1_186_200_words },
        { id: 903, title: "Test 2 (176-185)", words: test2_176_185_words },
        { id: 904, title: "Test 2 (186-200)", words: test2_186_200_words },
        { id: 905, title: "Test 3 (176-185)", words: test3_176_185_words },
        { id: 906, title: "Test 3 (186-200)", words: test3_186_200_words },
    ]
};